### ISSUE TITLE
SRL model produces wrong outputs on the same examples taken from the official demo

### ISSUE THREAD

**Issue by plroit** [allenai/allennlp#4803] opened 2020-11-18 16:24 UTC
- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log]
- [x] I have included in the "Related issues or possible duplicates" 
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description
Hello, 
I use AllenNLP version: 1.2.1 and I follow instructions for the SRL predictor (based on BERT)
in the demo: https://demo.allennlp.org/semantic-role-labeling/
The srl model I load is stored in this path:
https://storage.googleapis.com/allennlp-public-models/bert-base-srl-2020.03.24.tar.gz
and I load the predictor locally, following the usage instructions in the demo. 
When I input the sentence, taken from the demo to my local predictor (on my machine, not the demo website, obviously)
the predictions get very weird, very different than the model advertised in the demo, and not inline with the high scores that I know this model has. 

sentence:
> However, voters decided that if the stadium was such a good idea someone would build it himself, and rejected it 59% to 41%.

I get the following predictions:
**decided**: 
> 'description': '[ARGM-PRD: However ,] [ARG0: voters] [V: decided] [ARG1: that if the stadium] was such a good idea someone would build it himself , and rejected it 59 % to 41 %

**would**
> However , voters decided that [ARG1: if the stadium was such a good idea] someone [V: would] [ARGM-TMP: build it himself ,] and rejected it 59 % to 41 % .

**build**
> However , voters decided that if the stadium was such a good idea someone would [V: build] [ARG1: it himself] , and rejected it 59 % to 41 %

**rejected**
> However , voters decided that if the stadium was such a good idea someone would build it himself , and [V: rejected] it 59 % to 41 % .

## Related issues or possible duplicates
#3166

**Comment by dirkgr** [comment] 2020-11-19 00:52
I think the problem is that we do constrained decoding on the word pieces, but we want to do it on tokens. I seem to remember this from a discussion with @DeNeutoy a long time ago.

**Comment by dirkgr** [comment] 2020-11-19 01:13
I'm actually not seeing that problem in the output this time. I'll investigate if simply re-training turns out not to fix this.

**Comment by dirkgr** [comment] 2020-11-19 18:27
The version we're advertising in the demo is curiously old. I'm getting much better results (though not identical ones) with a newer model. I made a pull request here: https://github.com/allenai/allennlp-demo/pull/629

As a workaround, you should be able to get good results by using `https://storage.googleapis.com/allennlp-public-models/bert-base-srl-2020.11.19.tar.gz` as your model URL.

**Comment by dirkgr** [comment] 2020-11-19 19:15
That PR is now merged. Let me know if you find it still broken! I didn't test things exhaustively, just with your example.

**Closed by dirkgr** 2020-11-19 19:15 UTC
Labels: bug

**Comment by dirkgr** [comment] 2022-02-22 21:57
Yes, please make a new issue about this.
