### ISSUE TITLE
Make training files universal, cut dependency on Beaker

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#397] opened 2017-10-11 20:08 UTC
Presently the training files have hard coded paths on mounted Beaker datasets.

https://github.com/allenai/allennlp/blob/master/experiment_config/bidaf.json

This makes our experiments un-trainable to people outside AI2 without using Beaker.  I think we should instead use paths to folders in S3.  This way, people external to AI2 can easily retrain our models and training inside Beaker.

This also would help us make our [`run_with_beaker.sh`](https://github.com/allenai/allennlp/blob/master/scripts/ai2-internal/run_with_beaker.sh) script less BiDAF-specific.  Presently it mounts in squad and glove, which is not needed for all training jobs.

Very concretely, for BiDAF I propose uploading the datasets to our s3 bucket.

* `/squad/train-v1.1.json` -> `s3://allennlp/datasets/squad/train-v1.1.json`
* `/squad/dev-v1.1.json` -> `s3://allennlp/datasets/squad/dev-v1.1.json`
* `/glove/glove.6B.100d.txt.gz` -> `s3://allennlp/datasets/glove/glove.6B.100d.txt.gz`

And then similarly updating those paths in [the experiment config](https://github.com/allenai/allennlp/blob/master/experiment_config/bidaf.json
).

**Comment by schmmd** [comment] 2017-10-11 20:24
@matt-gardner @DeNeutoy @joelgrus I'm curious to your thoughts.  This would integrate less tightly with Beaker, but I think that it would help our external collaborators.  In discussing with @OyvindTafjord I think it would help him run trainings locally.

I'm pretty strongly in favor of this change as it makes AllenNLP easier for external people to use and reduces adoption friction.  I think it would have helped our user on https://github.com/allenai/allennlp/issues/378.

If we have this change, I would add one-liners to retrain our models (when possible) to http://allennlp.org/models.

**Comment by OyvindTafjord** [comment] 2017-10-11 20:33
This isn't a big deal for me to deal with, but maybe makes it easier for new users to get up and running. I'd worry a bit about dataset versioning here though.

**Comment by matt-gardner** [comment] 2017-10-11 20:45
If I were actively using these experiment config files for my research, I'd think this change was pretty annoying.  But I'm not, and don't have any plans to, so this doesn't bother me.  I think it's sensible to have the public configs be immediately usable when possible.

This actually creates issues with beaker, because it'd be faster with beaker to mount the dataset as it currently does, instead of downloading the dataset from S3 using our caching code.  But, as we discussed on slack earlier today, I think we'll be moving to a different repo for active research, anyway, so again this particular change isn't really a problem.

**Comment by schmmd** [comment] 2017-10-11 20:49
I think it's crucial to make this work easily for new users--but I'm completely open to other ideas on how to make it happen!

We discussed in the past moving inputs to CLI arguments rather than paths in the experiment configurations.  This arrangement would support both use cases.  `run_on_beaker.sh` could simply pass in Beaker paths, and training on the CLI could use http paths.

I'll check with the Aristo group to see what they recommend.

**Comment by schmmd** [comment] 2017-10-11 21:03
Joel and I spoke briefly and are going to keep thinking of this.  One idea we had was that if we supported overrides, it would be easy to support both Beaker and CLI runs.

Beaker downloads datasets from S3, so I doubt it would be dramatically faster but Marc says some tuning went into it.

**Comment by matt-gardner** [comment] 2017-10-11 21:22
What I would recommend: the config files we have checked in to the repo are for our demo models, and aren't for use with active AI2 experiments.  So they should have URLs (when possible), not beaker paths, or anything else.  `experiment_config/` probably isn't the right name for the place to store them, either.  Then, if someone wants to actively work on something, they copy that config file to somewhere that makes sense for them, and change paths to whatever makes the most sense for what they're doing.

**Comment by schmmd** [comment] 2017-10-13 18:12
Trying various things out, I came up with the following three options:

1.  Storing S3 URLs in configuration files for our pre-trained models.

2.  Using environment variables to specify the paths for inputs.  This would leave our Beaker workflow virtually unchanged, but allow us to use the same experiment.jsons for training models outside of Beaker.

3.  Using an `--overrides` flag which takes a HOCON configuration to override the paths when running trainings outside of Beaker.  I am not a fan of this option.

My preference is for 2, for which I have an example in https://github.com/allenai/allennlp/pull/402.

**Comment by matt-gardner** [comment] 2017-10-13 18:22
I have a pretty strong preference for 1 - you've already got a config file; why is there another way to specify configuration?  Which things go in the file and which things go as environment variables?

**Comment by schmmd** [comment] 2017-10-13 18:24
Paths go in environment variables--as they are system specific and we want to be able to run experiments inside and outside of Beaker.  Essentially, paths are variables presently in https://github.com/allenai/allennlp/blob/master/experiment_config/bidaf.json, so I don't see 2 as a change from the status-quo.

**Comment by schmmd** [comment] 2017-10-13 18:26
Note that no code needs to be written to support environment variables--HOCON already supports this.

**Comment by matt-gardner** [comment] 2017-10-13 18:36
If HOCON already supports environment variables, then anyone that wants to run experiments this way can use them to do it, and that's fine.  The question is what configuration files should be checked into our repo, and why?  I think the answer is that they are records of how to reproduce (as closely as possible) the models that are served by our demo, and an example that can be easily modified to do something related.  And for that, 1 seems pretty clearly to me to be the best solution.  I know I gave the name `experiment_config/` for where they are stored, but I think that's the wrong name - that's not what these files should be.

**Comment by schmmd** [comment] 2017-10-16 20:11
@matt-gardner we'll have to continue this discussion in person with Joel.  One problem is that we need to decide what to enter for paths for SRL, where we cannot share the dataset.  I'm still weakly in favor of 2.  Hopefully the three of us can make a decision quickly as it's going slowly with separate 1-1 conversations.

**Closed** 2017-10-19 20:57 UTC
