### ISSUE TITLE
Unable to `pip install allennlp-models`. Torch version and blis compile issues.

### ISSUE THREAD

**Issue by brochington** [allenai/allennlp#5616] opened 2022-04-05 18:02 UTC
## Checklist

- [X] I have verified that the issue exists against the `main` branch of AllenNLP.
- [X] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [X] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [X] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/main/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/main) to find out if the bug was already fixed in the main branch.
- [X] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [X] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [X] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [X] I have included in the "Environment" section below the output of `pip freeze`.
- [X] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

After installing Pytorch (1.11) and AllenNLP (2.9.2), via pip in a conda env, I am unable to `pip install allennlp-models`.  I get one of two errors, detailed below.

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
## Error 1

ERROR: Cannot install allennlp-models==1.2.1, allennlp-models==1.2.2, allennlp-models==1.3.0, allennlp-models==1.4.0, allennlp-models==1.4.1, allennlp-models==1.5.0, allennlp-models==2.0.0, allennlp-models==2.0.1, allennlp-models==2.1.0, allennlp-models==2.2.0, allennlp-models==2.3.0, allennlp-models==2.4.0, allennlp-models==2.5.0, allennlp-models==2.6.0, allennlp-models==2.7.0, allennlp-models==2.8.0 and allennlp-models==2.9.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    allennlp-models 2.9.0 depends on torch<1.11.0 and >=1.7.0
    allennlp-models 2.8.0 depends on torch<1.11.0 and >=1.7.0
    allennlp-models 2.7.0 depends on torch<1.10.0 and >=1.7.0
    allennlp-models 2.6.0 depends on torch<1.10.0 and >=1.7.0
    allennlp-models 2.5.0 depends on torch<1.9.0 and >=1.7.0
    allennlp-models 2.4.0 depends on torch<1.9.0 and >=1.7.0
    allennlp-models 2.3.0 depends on torch<1.9.0 and >=1.7.0
    allennlp-models 2.2.0 depends on torch<1.9.0 and >=1.7.0
    allennlp-models 2.1.0 depends on torch<1.8.0 and >=1.7.0
    allennlp-models 2.0.1 depends on torch<1.8.0 and >=1.7.0
    allennlp-models 2.0.0 depends on torch<1.8.0 and >=1.7.0
    allennlp-models 1.5.0 depends on torch<1.8.0 and >=1.7.0
    allennlp-models 1.4.1 depends on torch<1.8.0 and >=1.7.0
    allennlp-models 1.4.0 depends on torch<1.8.0 and >=1.7.0
    allennlp-models 1.3.0 depends on torch<1.8.0 and >=1.7.0
    allennlp-models 1.2.2 depends on torch<1.8.0 and >=1.7.0
    allennlp-models 1.2.1 depends on torch<1.8.0 and >=1.7.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

## Error 2

Compiler gcc
            building 'blis.cy' extension
            creating build/temp.linux-x86_64-3.10
            creating build/temp.linux-x86_64-3.10/blis
            gcc -pthread -B /home/brochstilley/miniforge3/envs/allennlp-api/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/brochstilley/miniforge3/envs/allennlp-api/include -fPIC -O2 -isystem /home/brochstilley/miniforge3/envs/allennlp-api/include -fPIC -I/tmp/pip-install-_etaqpbt/blis_322118b0f1e54b949f5124bb925aef68/include -I/tmp/pip-install-_etaqpbt/blis_322118b0f1e54b949f5124bb925aef68/blis/_src/include/linux-x86_64 -I/home/brochstilley/miniforge3/envs/allennlp-api/include/python3.10 -c blis/cy.c -o build/temp.linux-x86_64-3.10/blis/cy.o -std=c99
            gcc: error: blis/cy.c: No such file or directory
            gcc: fatal error: no input files
            compilation terminated.
            error: command '/usr/bin/gcc' failed with exit code 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> blis
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: Linux (KDE Neon (ubuntu))

Python version: 3.10.4

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
allennlp==2.9.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
attrs==21.4.0
backcall==0.2.0
backports.csv==1.0.7
base58==2.1.1
beautifulsoup4==4.10.0
bleach==4.1.0
blis==0.7.7
boto3==1.21.33
botocore==1.24.33
cached-path==1.1.1
cachetools==5.0.0
catalogue==2.0.7
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.12
checklist==0.0.11
cheroot==8.6.0
CherryPy==18.6.1
click==8.0.4
cryptography==36.0.2
cymem==2.0.6
debugpy==1.6.0
decorator==5.1.1
defusedxml==0.7.1
dill==0.3.4
docker-pycreds==0.4.0
entrypoints==0.4
executing==0.8.3
fairscale==0.4.6
fastjsonschema==2.15.3
feedparser==6.0.8
filelock==3.6.0
Flask==2.1.1
future==0.18.2
gitdb==4.0.9
GitPython==3.1.27
google-api-core==2.7.1
google-auth==2.6.2
google-cloud-core==2.2.3
google-cloud-storage==2.2.1
google-crc32c==1.3.0
google-resumable-media==2.3.2
googleapis-common-protos==1.56.0
h5py==3.6.0
huggingface-hub==0.4.0
idna==3.3
iniconfig==1.1.1
ipykernel==6.12.1
ipython==8.2.0
ipython-genutils==0.2.0
ipywidgets==7.7.0
iso-639==0.4.5
itsdangerous==2.1.2
jaraco.classes==3.2.1
jaraco.collections==3.5.1
jaraco.context==4.1.1
jaraco.functools==3.5.0
jaraco.text==3.7.0
jedi==0.18.1
Jinja2==3.1.1
jmespath==1.0.0
joblib==1.1.0
jsonnet==0.18.0
jsonschema==4.4.0
jupyter==1.0.0
jupyter-client==7.2.1
jupyter-console==6.4.3
jupyter-core==4.9.2
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.1.0
langcodes==3.3.0
lmdb==1.3.0
lxml==4.8.0
MarkupSafe==2.1.1
matplotlib-inline==0.1.3
mistune==0.8.4
more-itertools==8.12.0
munch==2.5.0
murmurhash==1.0.6
nbclient==0.5.13
nbconvert==6.4.5
nbformat==5.3.0
nest-asyncio==1.5.5
nltk==3.7
notebook==6.4.10
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1649059883087/work
packaging==21.3
pandocfilters==1.5.0
parso==0.8.3
pathtools==0.1.2
pathy==0.6.1
patternfork-nosql==3.6
pdfminer.six==20220319
pexpect==4.8.0
pickleshare==0.7.5
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1648857107578/work
pluggy==1.0.0
portend==3.1.0
preshed==3.0.6
prometheus-client==0.13.1
promise==2.3
prompt-toolkit==3.0.29
protobuf==3.20.0
psutil==5.9.0
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pydantic==1.8.2
Pygments==2.11.2
pyparsing==3.0.7
pyrsistent==0.18.1
pytest==7.1.1
python-dateutil==2.8.2
python-docx==0.8.11
pytz==2022.1
PyYAML==6.0
pyzmq==22.3.0
qtconsole==5.3.0
QtPy==2.0.1
regex==2022.3.15
requests==2.27.1
rsa==4.8
s3transfer==0.5.2
sacremoses==0.0.49
scikit-learn==1.0.2
scipy==1.8.0
Send2Trash==1.8.0
sentencepiece==0.1.96
sentry-sdk==1.5.8
setproctitle==1.2.2
sgmllib3k==1.0.0
shortuuid==1.0.8
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
smart-open==5.2.1
smmap==5.0.0
soupsieve==2.3.1
spacy==3.2.4
spacy-legacy==3.0.9
spacy-loggers==1.0.2
srsly==2.4.2
stack-data==0.2.0
tempora==5.0.1
tensorboardX==2.5
termcolor==1.1.0
terminado==0.13.3
testpath==0.6.0
thinc==8.0.15
threadpoolctl==3.1.0
tokenizers==0.11.6
tomli==2.0.1
torch==1.11.0
torchaudio==0.11.0
torchvision==0.12.0
tornado==6.1
tqdm==4.63.2
traitlets==5.1.1
transformers==4.17.0
typer==0.4.1
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1644850595256/work
urllib3==1.26.9
wandb==0.12.11
wasabi==0.9.1
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.1.1
widgetsnbextension==3.6.0
yaspin==2.1.0
zc.lockfile==2.0

```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
pip install allennlp
pip install allennlp[all]
pip install allennlp-models
```

</p>
</details>

**Comment by dirkgr** [comment] 2022-04-08 18:39
This is clearly a problem, though Python 3.10 is not part of our test matrix yet. It works with older versions.

**Comment by dirkgr** [comment] 2022-04-08 18:50
The pip error is confusing. The problem is that allennlp-models depends on torch<1.11.0, but torch==1.11.0 was the first version that's available on Python 3.10.

**Comment by dirkgr** [comment] 2022-04-08 18:50
This will be fixed when we make a release.

**Comment by brochington** [comment] 2022-04-08 19:15
Thanks for the update. I will use python 3.8 for the time being.

**Comment by dirkgr** [comment] 2022-04-14 22:50
New release is out. This should be fixed now.

**Closed by dirkgr** 2022-04-14 22:50 UTC
Labels: bug
