### ISSUE TITLE
How to get confidence score in WikitableQuestions Semantic Parser?

### ISSUE THREAD

**Issue by dummybot123** [allenai/allennlp#2634] opened 2019-03-21 08:32 UTC
I am using WikitableQuestions Semantic Parser model for answering questions based on tabular data. I used the source code from https://github.com/allenai/allennlp. I am wondering how to get confidence score for the answer.

**Comment by matt-gardner** [comment] 2019-03-21 15:13
This is a duplicate of https://github.com/allenai/allennlp/issues/2596.  I'm closing this, feel free to comment further if you have more questions.  Also feel free to submit a PR adding the confidence score to the returned values.

**Closed by matt-gardner** 2019-03-21 15:13 UTC

**Comment by dummybot123** [comment] 2019-03-22 02:53
I am not getting how to extract the score from the dict best_final_states.

**Comment by matt-gardner** [comment] 2019-03-22 03:11
`best_final_states[i][0].score[0]`

**Comment by matt-gardner** [comment] 2019-03-22 03:17
The i is for the batch index, the first 0 is the best state for that batch index, and the second 0 is the first (and only) score in that state (states can be grouped, but they aren't at the end of a search).

**Comment by matt-gardner** [comment] 2019-03-22 03:18
We should maybe consider differentiating between a single state and a grouped state, that might make things easier to understand. Maybe...
