### ISSUE TITLE
SimpleSeq2Seq always CUDA out of memory

### ISSUE THREAD

**Issue by zhengliz** [allenai/allennlp#2569] opened 2019-03-06 23:11 UTC
**Describe the bug**
I always run into CUDA out of memory after training `SimpleSeq2Seq` for a while.
At early training stage, it only takes around 3GB when stable. However, it will gradually (in jumping steps) reach CUDA OOM in the middle of an epoch after several thousands of iterations.
I've set `biggest_batch_first`, `max_decoding_steps` and *truncated* training sentences when read in *lazily*.
```
loss: 5.0901 ||: : 8613it [27:42,  5.34it/s]Traceback (most recent call last):                                                      
  File "paranmt5m_elmo.py", line 279, in <module>
    main(args)
  File "paranmt5m_elmo.py", line 211, in main
    trainer.train()
  File "/home/zhengliz/anaconda2/envs/allennlp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 465, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/zhengliz/anaconda2/envs/allennlp/lib/python3.7/site-packages/allennlp/training/trainer.py", line 311, in _train_epoch
    loss.backward()
  File "/home/zhengliz/anaconda2/envs/allennlp/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/zhengliz/anaconda2/envs/allennlp/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 1.44 GiB (GPU 0; 10.91 GiB total capacity; 3.45 GiB already allocated; 725.38 MiB free; 67.37 MiB cached)
```

Even after I added `torch.cuda.empty_cache()` within [the training loop of the Trainer](https://github.com/allenai/allennlp/blob/master/allennlp/training/trainer.py#L299-L377), it still runs into OOM, but at a higher iteration (always at 44526it x 64bs w `Trainer.shuffle`).

**To Reproduce**
It has to be running for a while. Then within an epoch, it will reach CUDA OOM.
Might be similiar issues as in #2515, but I'm using `SimpleSeq2Seq` off the shelf. 

**Expected behavior**
CUDA memory usage should be kind of stable after running a while, especially with `biggest_batch_first`, `max_decoding_steps` and training sentences *truncated* when read in *lazily*.

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.7.2
 - AllenNLP version: 0.8.2
 - PyTorch version: 1.0.1
 - GPU: GeForce GTX 1080 Ti, 11GB

**Additional context**
```python
# encode 'source_tokens' w ELMo
elmo_tokenizer = MosesTokenizer()
elmo_token_indexers = {'tokens': ELMoTokenCharactersIndexer()}
elmo_embedding = ElmoTokenEmbedder(options_file, weight_file)
elmo_embedder = BasicTextFieldEmbedder({'tokens': elmo_embedding})

# encode 'target_tokens' w Embedding(30000x256) hard-coded in SimpleSeq2Seq
vocab = Vocabulary.from_instances(
    instances=train_dataset,
    max_vocab_size={'target_tokens': 30000})

iterator = BucketIterator(
    sorting_keys=[('source_tokens', 'num_tokens'), ('target_tokens', 'num_tokens')],
    biggest_batch_first=True,
    batch_size=64)
iterator.index_with(vocab)

encoder = StackedSelfAttentionEncoder(
    input_dim=elmo_embedder.get_output_dim(), # 256
    hidden_dim=256,
    projection_dim=256,
    feedforward_hidden_dim=256,
    num_layers=3,
    num_attention_heads=8)

model = SimpleSeq2Seq(
    vocab=vocab,
    source_embedder=elmo_embedder,
    encoder=encoder,
    max_decoding_steps=30, # training sentences also truncated to 30 when read in
    attention=DotProductAttention(),
    beam_size=8,
    target_namespace='target_tokens',
    target_embedding_dim=256,
    use_bleu=True)
model.cuda()

optimizer = optim.Adam(model.parameters())

trainer = Trainer(
    model=model,
    optimizer=optimizer,
    iterator=iterator,
    train_dataset=train_dataset,
    num_epochs=10,
    cuda_device='0',
    grad_norm=5.0,
    grad_clipping=5.0)
```

**Comment by epwalsh** [comment] 2019-03-06 23:51
I'm not super familiar with how the iterators work, so if I'm misunderstanding this some please let me know. But if I understand correctly, the first batch (the "biggest" batch) would be the batch with the most *source* tokens, but not necessarily the most *target* tokens. So I'm wondering if you have another batch that gets hit later on in the epoch that has relatively few source tokens, but a large number of target tokens which is causing the OOM error?

**Comment by zhengliz** [comment] 2019-03-06 23:57
@epwalsh Thank you for the pointer. I've truncated both source and target sentences to length 30. So even if that is the case, I think it shouldn't bring in too much difference that causing OOM, given the initial memory usage.

**Comment by epwalsh** [comment] 2019-03-07 00:05
@zhengliz oh I see, I missed that initially. I've seen similar issues with training seq2seq models: large jumps in memory at some point during an epoch. Are you able to fit the entire dataset in memory? I'm just wondering if you tried with `lazy = False` in your dataset reader?

**Comment by zhengliz** [comment] 2019-03-07 00:11
@epwalsh My training data is about 7G so I didn't try `lazy=False`. The code runs fine on sample toy dataset though (which I think just hasn't reached the limit with enough iterations yet)

**Comment by epwalsh** [comment] 2019-03-07 00:23
@zhengliz hmm and have you tried setting `max_instances_in_memory` in the iterator?

**Comment by zhengliz** [comment] 2019-03-07 10:06
@epwalsh It doesn't work. I tried to set `max_instances_in_memory` to `2*batch_size` and `8*batch_size` both just now. It still reached OOM at the exact same number of iterations.

**Comment by matt-gardner** [comment] 2019-03-07 14:21
Is there a way to figure out which instance it's failing on?

**Comment by zhengliz** [comment] 2019-03-08 18:12
@matt-gardner I dumped [`batch_group`](https://github.com/allenai/allennlp/blob/master/allennlp/training/trainer.py#L299-L311) when OOM happens, and mapped indices back to characters/words. The instances look normal to me.

**Comment by matt-gardner** [comment] 2019-03-08 18:31
Is it feasible to try loading the whole data into memory?  Do you have a machine with enough RAM?  I'm not sure why that would affect GPU memory, though...  Sorry, I don't have a lot of experience with this model, and I'm not really sure what could be the cause here.

**Comment by schmmd** [comment] 2019-03-15 22:50
We suggest using a smaller batch size or moving to a larger GPU.  That's probably the easiest solution to your problem.

**Closed by schmmd** 2019-03-15 22:50 UTC

**Comment by schmmd** [comment] 2019-03-15 22:51
@DeNeutoy also suggest that the `maximum_samples_per_batch` parameter might help out (on the iterator).

**Comment by uganyasavur** [comment] 2019-03-21 21:34
@zhengliz, did you able to solve this issue? I have the same problem. Your model size is bigger than mine and my GPU is 12gb. I tried everything mentioned in this thread it just delays OOM message. 

I am actually coming from OpenNMT-py. I don't believe issue reported here related to GPU size or batch size. I was using significantly more complex and larger models in OpenNMT-py, the memory usage was a fraction of Simple_Seq2Seq in AllenNLP.

**Comment by zhengliz** [comment] 2019-03-21 21:45
@uganyasavur I wasn't able to solve this yet.

**Comment by joelgrus** [comment] 2019-03-21 21:55
my three usual culprits for GPU OOM are

(1) batch size too big (it sounds like you've checked that)
(2) metrics leaking memory by accumulating results but not detaching them from the computation graph (but if you're only using the library's metrics that shouldn't happen)
(3) instances that are secretly / unexpectedly very large (e.g. a "sentence" that has 10k words). 

I know you said you're truncating everywhere, but can you double-check that (3) isn't somehow happening to you?

**Comment by matt-gardner** [comment] 2019-03-21 22:06
One thing to be sure of: make sure you're using the "attention" argument instead of the "attention_function" argument to the model.  The latter was bad attempt to make something general, and just ended up using way too much memory.  This probably wouldn't explain an OOM later on during training, but switching would definitely decrease your memory usage.

**Comment by zhengliz** [comment] 2019-03-27 03:16
Thanks for all the pointers. I've tried out all these suggestions. I'll update if I figure out where the problem is later.
