### ISSUE TITLE
error of from allennlp.data import Token

### ISSUE THREAD

**Issue by Tianxu-Jia** [allenai/allennlp#538] opened 2017-11-24 11:16 UTC
File "/home/work/venv/py35/lib/python3.5/site-packages/allennlp-0.2.1-py3.5.egg/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset import Dataset
  File "/home/work/venv/py35/lib/python3.5/site-packages/allennlp-0.2.1-py3.5.egg/allennlp/data/dataset.py", line 34
    all_instance_fields_and_types: List[Dict[str, str]] = [{k: v.__class__.__name__

what is wrong of it?

**Comment by matt-gardner** [comment] 2017-11-24 15:17
You need to use python 3.6, not python 3.5.  Not sure if that's the cause of your problem or not, but it seems likely.

**Comment by matt-gardner** [comment] 2017-11-24 15:18
@joelgrus, @schmmd, is there a way to check the version of python that's running in `run.py`, and crash with an error if it's not the right version?

**Comment by joelgrus** [comment] 2017-11-24 15:20
yes, it's easy to do, I'll take it

**Comment by joelgrus** [comment] 2017-11-24 16:35
closed via https://github.com/allenai/allennlp/pull/539

Feel free to re-open if python 3.6 doesn't solve your problem (and if it doesn't, please include the full stack trace, makes it easier to debug)

**Closed by joelgrus** 2017-11-24 16:35 UTC

**Comment by Tianxu-Jia** [comment] 2017-11-25 15:03
Thanks all
This problem has been solved after I install python3.6.

But, there is other problem:
>>> from allennlp.data import Token
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Token'

Maybe there is problem with 'Token', I will view the source code

**Comment by antgr** [comment] 2019-04-14 18:38
I have similar issues. For example
from allennlp.data.vocabulary import Vocabulary
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-13-3f6dff7c6b9a> in <module>
----> 1 from allennlp.data.vocabulary import Vocabulary

ModuleNotFoundError: No module named 'allennlp.data'

During installation, the only suspected errors are

* fastai 1.0.51 requires nvidia-ml-py3, which is not installed. *
Installing collected packages: editdistance, h5py, scikit-learn, parsimonious, msgpack, jmespath, docutils, botocore, s3transfer, boto3, xmltodict, boto, PyYAML, pyaml, jsondiff, pbr, mock, jsonpickle, aws-xray-sdk, websocket-client, docker-pycreds, docker, future, pycryptodome, ecdsa, python-jose, moto, pytorch-pretrained-bert, protobuf, tensorboardX, pyasn1, rsa, colorama, awscli, jsonnet, greenlet, gevent, sphinxcontrib-devhelp, sphinxcontrib-jsmath, sphinxcontrib-qthelp, sphinxcontrib-serializinghtml, snowballstemmer, babel, sphinxcontrib-htmlhelp, imagesize, alabaster, sphinxcontrib-applehelp, sphinx, numpydoc, conllu, ftfy, sqlparse, allennlp
  Found existing installation: msgpack 0.6.1
    Uninstalling msgpack-0.6.1:
      Successfully uninstalled msgpack-0.6.1
  Found existing installation: PyYAML 5.1
 * Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine  *which files belong to it which would lead to only a partial uninstall.

**Comment by matt-gardner** [comment] 2019-04-15 04:23
It looks like you did not successfully install allennlp; the system gave up after being unable to uninstall PyYAML.

**Comment by Tortoise17** [comment] 2019-07-26 13:12
I also have same issue. !!
