### ISSUE TITLE
Is there any recommended way to log the predictions during evaluation?

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#3767] opened 2020-02-12 03:26 UTC
The `evaluate` command can only output the metrics to file, but not the predictions. 

First of all, it's trivial to output the results to a file. I can insert several lines anywhere in my model, but it may make the structure of my project very inconsistent and inelegant. So what I am seeking for is an elegant way that should be used with AllenNLP.

For now to solve the problem, I am hard coding several lines in my model to output the predictions. The basic idea is to determine whether to output based on `self.training` (if it is `False`, then output).<br> However, doing this have at least 2 obvious drawbacks. 
Firstly, `self.training` can also be `False` during training (i.e., when doing validation), as a result it also outputs the predictions during validation in training, which is not what I want. 
Secondly, what I am doing now is kind of clumsy, and I believe there should be a more elegant way to handle it (e.g., maybe there are some features provided by AllenNLP that I haven't explored). 

I know `predictor` can output the predictions for us, but based on my understanding, the purpose for predictor is more about doing demos or products rather than evaluation. 

Is there any recommended way by AllenNLP to log the predictions? My advisor has mentioned
multiple times that saving the predictions for every experiment is very important (that's why I believe there should be a better way to logging the predictions)... I really want to seek for an elegant solution for this. Currently I am doing it in an expedient way (i.e., hard coding something in my model). Making my code messy really makes me feel uncomfortable!

**Comment by viking-sudo-rm** [comment] 2020-02-12 19:06
I don't think there is any fully native way to do this, but one less hacky method is to write a `LogPredictionsModel` that wraps another `Model`.

The `LogPredictionsModel` would take another model as an argument. In the forward pass, it would call `result_dict = self.model.forward(*args, **kwargs)`. Then you can insert whatever code you have that logs the predictions in `result_dict` to a file. Finally, you can return `result_dict` to conform to the training API. Does this accomplish what you have in mind?

**Comment by entslscheia** [comment] 2020-02-12 20:31
> I don't think there is any fully native way to do this, but one less hacky method is to write a `LogPredictionsModel` that wraps another `Model`.
> 
> The `LogPredictionsModel` constructor would take another model as an argument. In the forward pass, it would call `result_dict = self.model.forward(*args, **kwargs)`. Then you can insert whatever code you have that logs the predictions in `result_dict` to a file. Finally, you can return `result_dict` to conform to the training API. Does this accomplish what you have in mind?

Thanks for the response. 
This should be a workaround. So there is no direct support (i.e., via configuration over a single parameter) in AllenNLP to log the predictions?

**Comment by viking-sudo-rm** [comment] 2020-02-12 21:36
> This should be a workaround. So there is no direct support (i.e., via configuration over a single parameter) in AllenNLP to log the predictions?

Not to my knowledge.

> using different classes for training and evaluation will introduce new problems (the saved file model.tar.gz passed to evaluate is generated by training). If I am writing my own scripts, then it's gonna be much more flexible to do this.

One way would be to have `LogPredictionsModel` only write out predictions if `not self.training`. If you do this, you can just directly specify `LogPredictionsModel` in your training config:

```jsonnet
  "model": {
    "type": "log-predictions",
    "model": {
       // Your model here.
    }
   }
```

The wrapper will do nothing at train time, and then it will get reused at evaluation time and become activated.

**Comment by entslscheia** [comment] 2020-02-13 01:10
> Actually, have you looked at the `allennlp predict` command using a custom `Predictor`?
> 
> https://github.com/allenai/allennlp/blob/master/allennlp/predictors/predictor.py
> 
> It seems like this may fit your use case better than using `allennlp evaluate`.

I think the right way should be put the all the predictions to the output dictionary in `Model.decode`. I am still trying to figure out how `Model.decode` is used.

**Comment by entslscheia** [comment] 2020-02-13 03:50
It looks like `Predictor` is the only place that AllenNLP uses `Model.decode`. I think if what I want is just to output the human readable predictions, using `Predictor` is unnecessarily complicated. Maybe I should just call `Model.decode` in `Model.forward`, which is essentially the same as what I am doing now (i.e., manually add printing to `Model.forward`).

**Comment by viking-sudo-rm** [comment] 2020-02-14 08:59
Assuming your model `forward()` returns the data you care about, I think you can accomplish the logging quite easily just using the `allennlp predict` command **just using the default `Predictor`**. Something like the following should do the trick:

```shell
allennlp predict /PATH/TO/MODEL /PATH/TO/TEST/SET --output-file=/PATH/TO/OUTPUT
```

This will log all the predictions returned by the model in JSON format.

**Comment by entslscheia** [comment] 2020-02-14 17:26
Thanks! That is helpful.

**Comment by brendan-ai2** [comment] 2020-02-14 23:11
I think this is a duplicate with https://github.com/allenai/allennlp/issues/3218. We should do this...

**Comment by dirkgr** [comment] 2020-02-21 23:21
I'm closing this since it's a duplicate of #3218.

**Closed by dirkgr** 2020-02-21 23:21 UTC
