### ISSUE TITLE
v0.8.4 doesn't register srl-bert

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#3162] opened 2019-08-16 14:55 UTC
From a direct email:

I'm a researcher from Zhejiang University and I noticed that the newest SRL model had been changed to the bert-based-srl but the newest version of allennlp v0.8.4 seems to have no registration of srl-bert as it is configured in the config file. So are there any code implementation of this in allennlp frame available now? Since the paper was not published with codes.

**Comment by joelgrus** [comment] 2019-08-16 14:57
this is because we need to do a release

duplicate of #3159

**Closed by joelgrus** 2019-08-16 14:57 UTC

**Comment by DeNeutoy** [comment] 2019-08-16 17:00
In the meantime, to use the SRL model, you will need to install from master 😄
