### ISSUE TITLE
Using evaluate with overrides

### ISSUE THREAD

**Issue by dimidd** [allenai/allennlp#1121] opened 2018-04-24 16:01 UTC
Hi,

I've implemented a custom dataset reader, 
```
@DatasetReader.register("tei_txt")
class TEITextDatasetReader(DatasetReader):
[...]
```
and trying to evaluate a model which was trained on a standard dataset.

`python3 -m allennlp.run evaluate ~/test_allen/crf_connl/model.tar.gz --evaluation-data-file all_test.txt --overrides '{ "dataset_reader": { "type": "tei_txt" } }'  --include-package allennlp.data.dataset_readers`

Which results in:
```value = self.params.pop(key)
KeyError: 'type'
[...]
raise ConfigurationError("key \"{}\" is required at location \"{}\"".format(key, self.history))
allennlp.common.checks.ConfigurationError: 'key "type" is required at location "dataset_reader."'
```
Am I using the `overrides` argument wrong?

**Comment by DeNeutoy** [comment] 2018-04-24 16:43
Can you post the full stack trace please?

**Comment by dimidd** [comment] 2018-04-24 18:51
Sure

```
2018-04-24 18:55:42,487 - INFO - allennlp.models.archival - extracting archive file /Users/dimidd/test_allen/crf_connl/model.tar.gz to temp dir /var/folders/sc/2zd_v0qn76gdq5sdg63_jx4r0000gn/T/tmp48fr26ki
2018-04-24 18:55:42,800 - INFO - allennlp.data.vocabulary - Loading token dictionary from /var/folders/sc/2zd_v0qn76gdq5sdg63_jx4r0000gn/T/tmp48fr26ki/vocabulary.
2018-04-24 21:49:45,131 - INFO - allennlp.models.archival - extracting archive file ~/test_allen/crf_connl/model.tar.gz to temp dir /var/folders/sc/2zd_v0qn76gdq5sdg63_jx4r0000gn/T/tmpsqd2in2j
2018-04-24 21:49:45,360 - INFO - allennlp.data.vocabulary - Loading token dictionary from /var/folders/sc/2zd_v0qn76gdq5sdg63_jx4r0000gn/T/tmpsqd2in2j/vocabulary.
2018-04-24 21:49:45,521 - INFO - allennlp.common.checks - Pytorch version: 0.3.1
Traceback (most recent call last):
  File "~/allennlp/allennlp/common/params.py", line 94, in pop
    value = self.params.pop(key)
KeyError: 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "~/allennlp/allennlp/commands/__init__.py", line 65, in main
    args.func(args)
  File "~/allennlp/allennlp/commands/evaluate.py", line 122, in evaluate_from_args
    dataset_reader = DatasetReader.from_params(config.pop('dataset_reader'))
  File "~/allennlp/allennlp/data/dataset_readers/dataset_reader.py", line 113, in from_params
    return cls.by_name(choice).from_params(params)
  File "~/allennlp/allennlp/data/dataset_readers/dataset_reader.py", line 112, in from_params
    choice = params.pop_choice('type', cls.list_available())
  File "~/allennlp/allennlp/common/params.py", line 179, in pop_choice
    value = self.pop(key, default)
  File "~/allennlp/allennlp/common/params.py", line 96, in pop
    raise ConfigurationError("key \"{}\" is required at location \"{}\"".format(key, self.history))
allennlp.common.checks.ConfigurationError: 'key "type" is required at location "dataset_reader."'
```

**Comment by schmmd** [comment] 2018-04-24 23:34
What you have looks fine to me.  When I used your `--overrides` command on a bidaf evaluation, I got an exception that `tei_txt` wasn't a known dataset reader--as expected.

```
$ python -m allennlp.run evaluate https://s3-us-west-2.amazonaws.com/allennlp/models/bidaf-model-2017.09.15-charpad.tar.gz --evaluation-data-file https://s3-us-west-2.amazonaws.com/allennlp/datasets/squad/squad-dev-v1.1.json --overrides '{ "dataset_reader": { "type": "tei_txt" } }'
/Users/michaels/miniconda3/envs/allennlp/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/Users/michaels/miniconda3/envs/allennlp/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
2018-04-24 16:33:29,169 - INFO - allennlp.models.archival - extracting archive file /Users/michaels/.allennlp/datasets/aHR0cHM6Ly9zMy11cy13ZXN0LTIuYW1hem9uYXdzLmNvbS9hbGxlbm5scC9tb2RlbHMvYmlkYWYtbW9kZWwtMjAxNy4wOS4xNS1jaGFycGFkLnRhci5neg==.bc6cc08ed491c6ac831bf363f7312fc1-6 to temp dir /var/folders/7k/vb0c56bx6_g5w4pf3qmwnscc0000gp/T/tmpzlxlyejx
2018-04-24 16:33:29,679 - INFO - allennlp.data.vocabulary - Loading token dictionary from /var/folders/7k/vb0c56bx6_g5w4pf3qmwnscc0000gp/T/tmpzlxlyejx/vocabulary.
2018-04-24 16:33:30,328 - INFO - allennlp.common.checks - Pytorch version: 0.3.1
Traceback (most recent call last):
  File "/Users/michaels/miniconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/michaels/miniconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/michaels/hack/allenai/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/Users/michaels/hack/allenai/allennlp/allennlp/commands/__init__.py", line 65, in main
    args.func(args)
  File "/Users/michaels/hack/allenai/allennlp/allennlp/commands/evaluate.py", line 121, in evaluate_from_args
    dataset_reader = DatasetReader.from_params(config.pop('dataset_reader'))
  File "/Users/michaels/hack/allenai/allennlp/allennlp/data/dataset_readers/dataset_reader.py", line 112, in from_params
    choice = params.pop_choice('type', cls.list_available())
  File "/Users/michaels/hack/allenai/allennlp/allennlp/common/params.py", line 183, in pop_choice
    raise ConfigurationError(message)
allennlp.common.checks.ConfigurationError: "tei_txt not in acceptable choices for dataset_reader.type: ['conll2003', 'coref', 'winobias', 'language_modeling', 'ptb_trees', 'squad', 'triviaqa', 'srl', 'seq2seq', 'sequence_tagging', 'snli', 'sst_tokens']"
```

**Comment by dimidd** [comment] 2018-04-25 09:26
Thanks, my code can be found here, I'll be grateful if you could take a look.
https://github.com/dimidd/allennlp/commit/3dbc66ac5e0b1742a0dfc69244ec41759fb7fab5

**Comment by joelgrus** [comment] 2018-04-25 15:27
I haven't managed to reproduce your error, but one thing that looks not quite right is your `--include-package` argument. by specifying `allennlp.data.dataset_readers`, you're only managing to import classes that are "known to" that top level module; i.e. known in `allennlp.data.dataset_readers.__init__.py`

you need to either add an import for your dataset reader to that file, or change the import package to `allennlp.data.dataset_readers.tei_text`.

I don't think that will fix your problem, but it would create a different one if you didn't have yours.

also, can you share the config file that your model was trained with? I don't see it in your repo.

**Comment by joelgrus** [comment] 2018-04-25 18:25
ok, cool, I've managed to reproduce, which hopefully means I should have a solution shortly 😀

**Comment by joelgrus** [comment] 2018-04-25 18:43
ok, here's the issue:

your dataset_reader needs a `from_params` method, something like

```python
    @classmethod
    def from_params(cls, params: Params) -> 'TeiTextDatasetReader':
        token_indexers = TokenIndexer.dict_from_params(params.pop('token_indexers', {}))
        lazy = params.pop('lazy', False)
        return TEITextDatasetReader(token_indexers=token_indexers, lazy=lazy)
```

I believe that will fix it.

*longer explanation*

the way classes get instantiated from configuration is that the base class from_params pops off the `type` parameter and uses it to delegate to a subclass implementation.

here, `DatasetReader.from_params` pops off `type`, sees `tei_text` and (in essence) calls `TEITextDatasetReader.from_params` with the remaining params. But `TEITextDatasetReader` doesn't define `from_params`, so it drops back to the base class method, which tries to pop off `type` *again*, which it can't, since it was already popped off.

closing, let me know if this doesn't fix your issue, but I think it should.

**Closed** 2018-04-25 18:43 UTC

**Comment by matt-gardner** [comment] 2018-04-25 18:47
Wow, that's hard to find.  Can we give a better error message in this case?  Like, catch the error in `DatasetReader.from_params`, and raise with a new message pointing to a possible like of `YourDatasetReader.from_params`?

**Comment by joelgrus** [comment] 2018-04-25 18:50
great minds think alike #1127

**Comment by dimidd** [comment] 2018-04-26 06:35
Great, thanks so much!
