### ISSUE TITLE
Loading pre-trained NER fine-grained model gives error

### ISSUE THREAD

**Issue by mchari** [allenai/allennlp#4276] opened 2020-05-22 01:24 UTC
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
from allennlp.predictors.predictor import Predictor
import allennlp_models.ner.crf_tagger
predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/fine-grained-ner-model-elmo-2020.02.10.tar.gz")

gives the following error stack trace :
Traceback (most recent call last):
File “allennlp_ner.py”, line 7, in
predictor = Predictor.from_path(“https://storage.googleapis.com/allennlp-public-models/fine-grained-ner-model-elmo-2020.02.10.tar.gz”)
File “/anaconda3/lib/python3.7/site-packages/allennlp/predictors/predictor.py”, line 274, in from_path
load_archive(archive_path, cuda_device=cuda_device),
File “/anaconda3/lib/python3.7/site-packages/allennlp/models/archival.py”, line 197, in load_archive
opt_level=opt_level,
File “/anaconda3/lib/python3.7/site-packages/allennlp/models/model.py”, line 387, in load
return model_class._load(config, serialization_dir, weights_file, cuda_device, opt_level)
File “/anaconda3/lib/python3.7/site-packages/allennlp/models/model.py”, line 332, in _load
model.load_state_dict(model_state)
File “/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py”, line 847, in load_state_dict
self.class.name, “\n\t”.join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CrfTagger:
Missing key(s) in state_dict: “encoder._module.forward_layer_0.cell.input_linearity.weight”, “encoder._module.forward_layer_0.cell.state_linearity.weight”, “encoder._module.forward_layer_0.cell.state_linearity.bias”, “encoder._module.backward_layer_0.cell.input_linearity.weight”, “encoder._module.backward_layer_0.cell.state_linearity.weight”, “encoder._module.backward_layer_0.cell.state_linearity.bias”, “encoder._module.forward_layer_1.cell.input_linearity.weight”, “encoder._module.forward_layer_1.cell.state_linearity.weight”, “encoder._module.forward_layer_1.cell.state_linearity.bias”, “encoder._module.backward_layer_1.cell.input_linearity.weight”, “encoder._module.backward_layer_1.cell.state_linearity.weight”, “encoder._module.backward_layer_1.cell.state_linearity.bias”.
Unexpected key(s) in state_dict: “encoder._module.forward_layer_0.input_linearity.weight”, “encoder._module.forward_layer_0.state_linearity.weight”, “encoder._module.forward_layer_0.state_linearity.bias”, “encoder._module.backward_layer_0.input_linearity.weight”, “encoder._module.backward_layer_0.state_linearity.weight”, “encoder._module.backward_layer_0.state_linearity.bias”, “encoder._module.forward_layer_1.input_linearity.weight”, “encoder._module.forward_layer_1.state_linearity.weight”, “encoder._module.forward_layer_1.state_linearity.bias”, “encoder._module.backward_layer_1.input_linearity.weight”, “encoder._module.backward_layer_1.state_linearity.weight”, “encoder._module.backward_layer_1.state_linearity.bias”.
size mismatch for text_field_embedder.token_embedder_token_characters._embedding._module.weight: copying a param with shape torch.Size([119, 25]) from checkpoint, the shape in current model is torch.Size([57007, 25]).

**Comment by dirkgr** [comment] 2020-05-22 21:41
This is a duplicate of #4011.

**Closed by dirkgr** 2020-05-22 21:41 UTC

**Comment by mchari** [comment] 2020-05-23 04:40
Is there a new fine-grained NER model that I need to load or has

"
https://storage.googleapis.com/allennlp-public-models/fine-grained-ner-model-elmo-2020.02.10.tar.gz
"

been updated ?


thanks!

**Comment by nikoletta-toth** [comment] 2020-06-16 08:25
Hi

I also want to use the fine grained ner model, but I cannot load it in. <br>
Can you give me some information how should I load this model? Or which model I should use?

To install AllenNLP I use:
`pip install allennlp==1.0.0rc5 allennlp-models==1.0.0rc5`

And to load the model:
`
from allennlp.predictors.predictor import Predictor`
`predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/fine-grained-ner-model-elmo-2018.12.21.tar.gz")
`

It downloads the model, but then fails on the from_path() with this error:
`
Traceback (most recent call last):
  File "..PycharmProjects/NamedEntityRecs/allennlp_test.py", line 23, in <module>
    predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/fine-grained-ner-model-elmo-2018.12.21.tar.gz")`
  `File "../python3.6/site-packages/allennlp/predictors/predictor.py", line 275, in from_path
    load_archive(archive_path, cuda_device=cuda_device),`
  `File "../python3.6/site-packages/allennlp/models/archival.py", line 197, in load_archive
    opt_level=opt_level,`
 ` File "../python3.6/site-packages/allennlp/models/model.py", line 398, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device, opt_level)`
  `File "../python3.6/site-packages/allennlp/models/model.py", line 295, in _load
    model = Model.from_params(vocab=vocab, params=model_params)`
`  File "../python3.6/site-packages/allennlp/common/from_params.py", line 580, in from_params
    **extras,`
`  File "../python3.6/site-packages/allennlp/common/from_params.py", line 609, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)`
 ` File "../python3.6/site-packages/allennlp/common/from_params.py", line 181, in create_kwargs
    cls.__name__, param_name, annotation, param.default, params, **extras`
  `File "../python3.6/site-packages/allennlp/common/from_params.py", line 287, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)`
 ` File "../python3.6/site-packages/allennlp/common/from_params.py", line 321, in construct_arg
    return annotation.from_params(params=popped_params, **subextras)`
 ` File "../python3.6/site-packages/allennlp/common/from_params.py", line 533, in from_params
    "from_params was passed a `params` object that was not a `Params`. This probably "
allennlp.common.checks.ConfigurationError: from_params was passed a `params` object that was not a `Params`. This probably indicates malformed parameters in a configuration file, where something that should have been a dictionary was actually a list, or something else. This happened when constructing an object of type <class 'allennlp.nn.regularizers.regularizer_applicator.RegularizerApplicator'>.
`

Thanks!!
