### ISSUE TITLE
Efficient predictions on GPU

### ISSUE THREAD

**Issue by AvivWn** [allenai/allennlp#2714] opened 2019-04-13 16:50 UTC
- OS: OSX 10.14.3
 - Python version: 3.6.8
 - AllenNLP version: v0.7.1

I am using the trained "Constituency Parsing" model as written in https://allennlp.org/models.

from allennlp.predictors.predictor import Predictor
predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/elmo-constituency-parser-2018.03.14.tar.gz")
predictor.predict(
  sentence="If I bring 10 dollars tomorrow, can you buy me lunch?"
)

I want to use the same model on a large amount of sentences. Currently, I loop over the sentences and use predictor.predict for each single sentence.
Is there more efficient way (in run time) to do those predictions when running on GPU? like batch prediction or something like that?

Thanks in advance

**Comment by joelgrus** [comment] 2019-04-15 14:07
this is basically the request in #2576 but unfortunately no one has implemented it yet

**Comment by matt-gardner** [comment] 2019-04-15 14:38
There is also `predict_batch_instance` on a `Predictor`, which will batch things for you and run them on the GPU: https://github.com/allenai/allennlp/blob/58f386c5a95ea7a771776cad702c3931d7df0acc/allennlp/predictors/predictor.py#L108-L110

We do want this to be available in the `predict` command eventually, but no one is working on that right now.  I'm closing this, as I think this answers the question, and the bit that @joelgrus is talking about is a duplicate of #2576.  Feel free to comment again if you have further questions.

**Closed by matt-gardner** 2019-04-15 14:38 UTC

**Comment by matt-gardner** [comment] 2019-04-15 14:42
Also, for how to call this, if you're only aware of how `parser.predict({sentence="..."})` works: you can see what that code is doing here: https://github.com/allenai/allennlp/blob/58f386c5a95ea7a771776cad702c3931d7df0acc/allennlp/predictors/constituency_parser.py#L69-L80

You can see it's just calling `predict_json` inside.  There's also a `predict_batch_json` which takes a list of these objects and predicts them in a batch: https://github.com/allenai/allennlp/blob/58f386c5a95ea7a771776cad702c3931d7df0acc/allennlp/predictors/predictor.py#L104-L106

So, the easiest change for you is to just make a list of your sentences (each in a dictionary keyed by "sentence") and call `predict_batch_json`.

**Comment by AvivWn** [comment] 2019-04-16 09:16
Thanks!

**Comment by ytfei0327** [comment] 2022-07-29 15:49
Hello, have you solved this problem? I am so confused about the format of input. Is it necessary to create instance for the sentences ?
Thank you very much.
