### ISSUE TITLE
Bert Seq2Seq via config file - tying bert_indexer and target

### ISSUE THREAD

**Issue by ehsankddm** [allenai/allennlp#3300] opened 2019-09-30 08:58 UTC
- OS: Amazon Linux AMI
 - Python version: 3.7.4 (conda 4.7.12)
 - AllenNLP version:  from master
 - PyTorch version: 1.2.0

I am trying to get a simple_seq2seq model to work with Bert as the encoder. However, I am unable at the moment to figure out the right way to tie the source and target embeddings. They are both in the same language.
I get this error for the config file below:

> File “/nlp/git/allennlp/allennlp/models/encoder_decoders/simple_seq2seq.py”, line 218, in forward
> output_dict = self._forward_loop(state, target_tokens)
> File “/nlp/git/allennlp/allennlp/models/encoder_decoders/simple_seq2seq.py”, line 310, in _forward_loop
> targets = target_tokens[“tokens”]
> KeyError: ‘tokens’
```

{
    "dataset_reader": {
        "type": "seq2seq",
	"source_token_indexers": {
            "bert": {
                "type": "pretrained_transformer",
                "model_name": "bert-base-cased",
                "do_lowercase": false
            }
        },
        "source_tokenizer": {
            "type": "pretrained_transformer",
            "model_name": "bert-base-cased",
            "do_lowercase": false
        },

	"target_token_indexers": {
            "bert": {
                "type": "pretrained_transformer",
                "model_name": "bert-base-cased",
                "do_lowercase": false,
		"namespace": "target_tokens"
            }
        },

        "target_tokenizer": {
            "type": "word",
            "word_splitter": {
                "type": "bert-basic",
                "do_lower_case": false
            }
        }
    },
    "train_data_path": "/nlp/Data/small_sent.tsv",
    "validation_data_path": "/nlp/Data/small_sent.tsv",
    "model": {
        "type": "simple_seq2seq",
	"source_embedder": {
            "token_embedders": {
                "bert": {
                    "type": "bert-pretrained",
                    "pretrained_model": "bert-base-cased",
                    "top_layer_only": true,
                    "requires_grad": false
                }
            }
        },
        "encoder": {
		"type": "lstm",
		"num_layers":1,
		"input_size": 768,
		"hidden_size":768
	        },
        "target_namespace": "target_tokens",
	"target_embedding_dim": 256,
	"max_decoding_steps": 80,
        "attention": {
            "type": "dot_product"
        },
        "beam_size": 5
    },
    "iterator": {
        "type": "basic",
        "batch_size": 32
    },
    "trainer": {
        "optimizer": {
            "type": "adam",
            "lr": 0.001
        },
        "patience": 10,
        "num_epochs": 100,
        "num_serialized_models_to_keep": 5,
        "should_log_learning_rate": true
    }
}

```
Any input is much appreciated. Thanks.

**Comment by matt-gardner** [comment] 2019-09-30 15:50
As this is a question, not a bug with allennlp, and you already asked the question [on discourse](https://discourse.allennlp.org/t/bert-seq2seq-via-config-file-tying-bert-indexer-and-target/52), I'm going to close this issue in favor of the discourse version.

**Closed by matt-gardner** 2019-09-30 15:50 UTC
