### ISSUE TITLE
current FromParams is incompatible with PEP 563

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/allennlp#3005] opened 2019-06-25 18:57 UTC
https://www.python.org/dev/peps/pep-0563/#non-typing-usage-of-annotations

Basically, to enable forward references in type hints, this PEP delays evaluations of type hints until they are called, leaving them as strings. This breaks `FromParams` which assumes that it can infer their types by inspecting the class itself. 

Instead, the PEP recommends using `typing.get_type_hints(obj, globalns=None, localns=None)` to get the type hints.

**Comment by matt-gardner** [comment] 2019-06-25 19:29
Thanks for finding this, I hadn't seen this PEP before.  Looks like it's a simple one-line fix: https://stackoverflow.com/a/53439113/1467533.

**Comment by brendan-ai2** [comment] 2019-06-28 22:10
Matt notes that if we need `from __future__ import annotations` this could have implications.

**Comment by brendan-ai2** [comment] 2019-06-28 23:59
@DeNeutoy, do you know how to trigger the behavior that will break our current use of type hints? Simply adding `from __future__ import annotations` to `from_params.py` doesn't break `allennlp/tests/common/from_params_test.py`. (Trying to make sure I actually fix this...)

**Comment by matt-gardner** [comment] 2019-06-29 00:03
This was where it was reported: https://twitter.com/altescy/status/1143442332622057473

**Comment by matt-gardner** [comment] 2019-06-29 00:05
You also might try putting that import somewhere before any code with annotations is run, like in `allennlp/__init__.py`.

**Comment by brendan-ai2** [comment] 2019-07-12 22:03
Thanks for the suggestion @matt-gardner, but that doesn't appear to break the tests either. Any other ideas to repro?

**Comment by matt-gardner** [comment] 2019-07-12 22:27
Nope, I don't have anything other ideas.  We can't really make progress on this without an actual reproducible error.  I'd vote for closing this issue, and when someone actually runs into it and can reproduce the error for us, they can open a new issue.

**Comment by brendan-ai2** [comment] 2019-07-12 23:28
Agreed. Thanks.

**Closed by brendan-ai2** 2019-07-12 23:28 UTC
