### ISSUE TITLE
allennlp.common.checks.ConfigurationError: key "optimizer" is required at location "trainer.learning_rate_scheduler."

### ISSUE THREAD

**Issue by dangne** [allenai/allennlp#5600] opened 2022-03-16 07:20 UTC
## Checklist

- [x] I have verified that the issue exists against the `main` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/main/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/main) to find out if the bug was already fixed in the main branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [ ] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description
I'm using `allennlp train` with the following config
<details>
<summary><b>JSON config:</b></summary>
<p>

```
local args = {
    // dataset_reader args
    dataset_reader_name :: "seq2labels_datareader",
    pretrained_transformer_name :: "roberta-base",
    max_length :: 512,
    delimeters :: {
        "tokens": " ",
        "labels": "SEPL|||SEPR",
        "operations": "SEPL__SEPR",
    },
    skip_correct :: true,
    skip_complex :: 0,
    max_len :: 50,
    test_mode :: false,
    tag_strategy :: "keep_one",
    tn_prob :: 0,
    tp_prob :: 1,
    broken_dot_strategy :: "keep",

    // data path args
    train_data_path :: "data/processed/train/errorified_data_0/train_0.txt",
    validation_data_path :: "data/processed/val/errorified_data_0/val_0.txt",

    // vocab args
    max_vocab_size :: {
        "tokens": 30000, 
        "labels": 5000, 
        "d_tags": 2,
    },
    vocab_path :: "vocabulary",
    tokens_to_add :: {
        "labels": [
            "@@UNKNOWN@@",
            "@@PADDING@@",
        ],
        "d_tags": [
            "@@UNKNOWN@@",
            "@@PADDING@@",
        ],
    },

    // model args
    model_name :: "seq2labels",
    predictor_dropout :: 0.0,
    label_smoothing :: 0.0,

    // data_loader args
    batch_size :: 64,
    num_workers :: 4,
    max_instances_in_memory :: 64 * 4 * 3,

    // trainer args
    trainer_name :: "gec_trainer",
    lr :: 1e-5,
    patience :: 3,
    num_epochs :: 20,
    model_dir :: "models/demo_train_from_configs",
    factor :: 0.1,
    accumulation_size :: 2,
    cold_step_count :: 4,
    cold_lr :: 1e-3,
};

local from_instances_vocab = {
    "type": "from_instances",
    "max_vocab_size": args.max_vocab_size,
    "tokens_to_add": args.tokens_to_add,
};

local from_files_vocab = {
    "type": "from_files",
    "directory": args.vocab_path,
};

{
    "dataset_reader": {
        "type": args.dataset_reader_name,
        "token_indexers": {
            "tokens": {
                "type": "pretrained_transformer",
                "model_name": args.pretrained_transformer_name,
                "max_length": args.max_length,
            },
        },
        "delimeters": args.delimeters,
        "skip_correct": args.skip_correct,
        "skip_complex": args.skip_complex,
        "max_len": args.max_len,
        "test_mode": args.test_mode,
        "tag_strategy": args.tag_strategy,
        "tn_prob": args.tn_prob,
        "tp_prob": args.tp_prob,
        "broken_dot_strategy": args.broken_dot_strategy,
    },
    "train_data_path": args.train_data_path,
    "validation_data_path": args.validation_data_path,
    "vocabulary": from_files_vocab,
    "model": {
        "type": args.model_name,
        "text_field_embedder": {
            "token_embedders": {
                "tokens": {
                    "type": "pretrained_transformer",
                    "model_name": args.pretrained_transformer_name,
                },
            },
        },
        "predictor_dropout": args.predictor_dropout,
        "label_smoothing": args.label_smoothing,
    },
    "data_loader": {
        "batch_sampler": {
            "type": "bucket",
            "batch_size": args.batch_size,
        },
        "num_workers": args.num_workers,
        "max_instances_in_memory": args.max_instances_in_memory,

    },
    "trainer": {
        "type": args.trainer_name,
        "optimizer": {
            "type": "adam",
            "lr": args.lr,
        },
        "learning_rate_scheduler": {
            "type": "reduce_on_plateau",
            "factor": args.factor,
            "patience": args.patience,
        },
        "patience": args.patience,
        "num_epochs": args.num_epochs,
        "num_gradient_accumulation_steps": args.accumulation_size,
        "cold_step_count": args.cold_step_count,
        "cold_lr": args.cold_lr,
    },
    "distributed": {
        "cuda_devices": [0, 1]
    }
}
```

</p>
</details>

In `"trainer"` I specified the `optimizer` and `learning_rate_scheduler`. However, once I run `allennlp train`, it raise the following error:

<details>
<summary><b>Python traceback 1:</b></summary>
<p>

```
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/params.py", line 211, in pop
    value = self.params.pop(key)
KeyError: 'optimizer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/commands/train.py", line 494, in _train_worker
    train_loop = TrainModel.from_params(
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 604, in from_params
    return retyped_subclass.from_params(
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 638, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/commands/train.py", line 786, in from_partial_objects
    trainer_ = trainer.construct(
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/lazy.py", line 82, in construct
    return self.constructor(**contructor_kwargs)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/lazy.py", line 66, in constructor_to_use
    return self._constructor.from_params(  # type: ignore[union-attr]
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 604, in from_params
    return retyped_subclass.from_params(
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 636, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 206, in create_kwargs
    constructed_arg = pop_and_construct_arg(
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 314, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 348, in construct_arg
    result = annotation.from_params(params=popped_params, **subextras)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 604, in from_params
    return retyped_subclass.from_params(
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 636, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 206, in create_kwargs
    constructed_arg = pop_and_construct_arg(
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 310, in pop_and_construct_arg
    popped_params = params.pop(name, default) if default != _NO_DEFAULT else params.pop(name)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/params.py", line 216, in pop
    raise ConfigurationError(msg)
allennlp.common.checks.ConfigurationError: key "optimizer" is required at location "trainer.learning_rate_scheduler."
```

</p>
</details>

But the doc states that I do not need to pass an optimizer key to the learning rate scheduler.

I also did try to pass the `optimizer` inside `learning_rate_scheduler` as follows:
```
"trainer": {
        "type": args.trainer_name,
        "optimizer": {
            "type": "adam",
            "lr": args.lr,
        },
        "learning_rate_scheduler": {
            "type": "reduce_on_plateau",
            "optimizer": {
                "type": "adam",
                "lr": args.lr,
            },
            "factor": args.factor,
            "patience": args.patience,
        },
        ...
}
```
but then it raises an error for missing "model_parameters" key in `learning_rate_scheduler` (see the traceback below).

<details>
<summary><b>Python traceback 2:</b></summary>
<p>

```
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/params.py", line 211, in pop
    value = self.params.pop(key)
KeyError: 'model_parameters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/commands/train.py", line 494, in _train_worker
    train_loop = TrainModel.from_params(
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 604, in from_params
    return retyped_subclass.from_params(
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 638, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/commands/train.py", line 786, in from_partial_objects
    trainer_ = trainer.construct(
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/lazy.py", line 82, in construct
    return self.constructor(**contructor_kwargs)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/lazy.py", line 66, in constructor_to_use
    return self._constructor.from_params(  # type: ignore[union-attr]
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 604, in from_params
    return retyped_subclass.from_params(
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 636, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 206, in create_kwargs
    constructed_arg = pop_and_construct_arg(
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 314, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 348, in construct_arg
    result = annotation.from_params(params=popped_params, **subextras)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 604, in from_params
    return retyped_subclass.from_params(
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 636, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 206, in create_kwargs
    constructed_arg = pop_and_construct_arg(
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 314, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 348, in construct_arg
    result = annotation.from_params(params=popped_params, **subextras)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 604, in from_params
    return retyped_subclass.from_params(
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 636, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 206, in create_kwargs
    constructed_arg = pop_and_construct_arg(
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 310, in pop_and_construct_arg
    popped_params = params.pop(name, default) if default != _NO_DEFAULT else params.pop(name)
  File "/root/miniconda3/envs/arp/lib/python3.8/site-packages/allennlp/common/params.py", line 216, in pop
    raise ConfigurationError(msg)
allennlp.common.checks.ConfigurationError: key "model_parameters" is required at location "trainer.learning_rate_scheduler.optimizer."
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: Ubuntu 18.04.4 LTS

Python version: 3.8.12

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
absl-py==1.0.0
aiohttp==3.8.1
aiosignal==1.2.0
alabaster==0.7.12
allennlp==2.9.0
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
async-timeout==4.0.2
attrs==21.4.0
awscli==1.22.67
Babel==2.9.1
backcall==0.2.0
backports.csv==1.0.7
base58==2.1.1
beautifulsoup4==4.10.0
black==22.1.0
bleach==4.1.0
blis==0.7.6
boto3==1.21.12
botocore==1.24.12
cached-path==1.1.0
cachetools==5.0.0
catalogue==2.0.6
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.12
checklist==0.0.11
cheroot==8.6.0
CherryPy==18.6.1
click==8.0.4
colorama==0.4.3
conllu==0.11
cryptography==36.0.1
cycler==0.11.0
cymem==2.0.6
debugpy==1.5.1
decorator==5.1.1
defusedxml==0.7.1
dill==0.3.4
docker-pycreds==0.4.0
docutils==0.15.2
editdistance==0.6.0
entrypoints==0.4
executing==0.8.3
fairscale==0.4.5
feedparser==6.0.8
filelock==3.4.2
flaky==3.7.0
Flask==2.0.3
Flask-Cors==3.0.10
fonttools==4.29.1
frozenlist==1.3.0
fsspec==2022.2.0
ftfy==6.1.1
future==0.18.2
gevent==21.12.0
gitdb==4.0.9
GitPython==3.1.27
google-api-core==2.6.0
google-auth==2.6.0
google-auth-oauthlib==0.4.6
google-cloud-core==2.2.2
google-cloud-storage==1.44.0
google-crc32c==1.3.0
google-resumable-media==2.3.1
googleapis-common-protos==1.55.0
greenlet==1.1.2
grpcio==1.44.0
h5py==3.6.0
huggingface-hub==0.2.1
idna==3.3
imagesize==1.3.0
importlib-metadata==4.11.2
importlib-resources==5.4.0
iniconfig==1.1.1
ipykernel==6.9.1
ipython==8.1.1
ipython-genutils==0.2.0
ipywidgets==7.6.5
iso-639==0.4.5
itsdangerous==2.1.0
jaraco.classes==3.2.1
jaraco.collections==3.5.1
jaraco.context==4.1.1
jaraco.functools==3.5.0
jaraco.text==3.7.0
jedi==0.18.1
Jinja2==3.0.3
jmespath==0.10.0
joblib==1.1.0
jsonnet==0.18.0
jsonpickle==2.1.0
jsonschema==4.4.0
jupyter==1.0.0
jupyter-client==7.1.2
jupyter-console==6.4.0
jupyter-core==4.9.2
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.2
kiwisolver==1.3.2
langcodes==3.3.0
lmdb==1.3.0
lxml==4.8.0
Markdown==3.3.6
MarkupSafe==2.1.0
matplotlib==3.5.1
matplotlib-inline==0.1.3
mistune==0.8.4
more-itertools==8.12.0
multidict==6.0.2
munch==2.5.0
murmurhash==1.0.6
mypy-extensions==0.4.3
nbclient==0.5.11
nbconvert==6.4.2
nbformat==5.1.3
nest-asyncio==1.5.4
nltk==3.6.5
notebook==6.4.8
numpy==1.22.2
numpydoc==1.2
oauthlib==3.2.0
overrides==3.1.0
packaging==21.3
pandocfilters==1.5.0
parsimonious==0.8.1
parso==0.8.3
pathspec==0.9.0
pathtools==0.1.2
pathy==0.6.1
patternfork-nosql==3.6
pdfminer.six==20211012
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.0.1
plac==0.9.6
platformdirs==2.5.1
pluggy==1.0.0
portend==3.1.0
preshed==3.0.6
prometheus-client==0.13.1
promise==2.3
prompt-toolkit==3.0.28
protobuf==3.19.4
psutil==5.9.0
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pydantic==1.8.2
pyDeprecate==0.3.1
Pygments==2.11.2
pyparsing==3.0.7
pyrsistent==0.18.1
pytest==7.0.1
python-dateutil==2.8.2
python-docx==0.8.11
python-Levenshtein==0.12.1
pytorch-lightning==1.5.10
pytorch-pretrained-bert==0.6.2
pytz==2021.3
PyYAML==5.4.1
pyzmq==22.3.0
qtconsole==5.2.2
QtPy==2.0.1
regex==2022.3.2
requests==2.27.1
requests-oauthlib==1.3.1
responses==0.18.0
rsa==4.7.2
s3transfer==0.5.2
sacremoses==0.0.47
scikit-learn==1.0.2
scipy==1.8.0
Send2Trash==1.8.0
sentencepiece==0.1.96
sentry-sdk==1.5.6
setproctitle==1.2.2
sgmllib3k==1.0.0
shortuuid==1.0.8
six==1.16.0
smart-open==5.2.1
smmap==5.0.0
snowballstemmer==2.2.0
soupsieve==2.3.1
spacy==3.2.3
spacy-legacy==3.0.9
spacy-loggers==1.0.1
Sphinx==4.4.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
sqlparse==0.4.2
srsly==2.4.2
stack-data==0.2.0
tempora==5.0.1
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorboardX==2.5
termcolor==1.1.0
terminado==0.13.2
testpath==0.6.0
thinc==8.0.13
threadpoolctl==3.1.0
tokenizers==0.11.6
tomli==2.0.1
torch==1.10.2
torchmetrics==0.7.2
torchvision==0.11.3
tornado==6.1
tqdm==4.62.3
traitlets==5.1.1
transformers==4.17.0
typer==0.4.0
typing-utils==0.1.0
typing_extensions==4.1.1
Unidecode==1.3.3
urllib3==1.26.8
wandb==0.12.11
wasabi==0.9.0
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.0.3
widgetsnbextension==3.5.2
word2number==1.1
yarl==1.7.2
yaspin==2.1.0
zc.lockfile==2.0
zipp==3.7.0
zope.event==4.5.0
zope.interface==5.4.0
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
```

</p>
</details>

**Comment by epwalsh** [comment] 2022-03-22 00:03
What's the "gec_trainer" that you're using? I suspect it's missing an initialization method that passes the optimizer to the learning rate scheduler as its creating it, like this: https://github.com/allenai/allennlp/blob/18d54b9c9c88f009bd4387ca2b85d764c1693126/allennlp/training/gradient_descent_trainer.py#L1183-L1189

**Comment by dangne** [comment] 2022-03-22 03:38
Hi @epwalsh, thanks for your reply. This is my gec_trainer.

<details>
<summary><b>gec_trainer.py:</b></summary>
<p>


```
import datetime
import logging
import os
import time
from typing import Optional, Union, List, Dict, Tuple, Any

import torch
import torch.distributed as dist

from allennlp.common import util as common_util
from allennlp.common.file_utils import hardlink_or_copy
from allennlp.data.data_loaders.data_loader import DataLoader
from allennlp.models.model import Model
from allennlp.nn.parallel import DdpWrappedModel
from allennlp.nn.util import dist_reduce_sum
from allennlp.training.checkpointer import Checkpointer
from allennlp.training.learning_rate_schedulers.learning_rate_scheduler import (
    LearningRateScheduler,
)
from allennlp.training.momentum_schedulers.momentum_scheduler import MomentumScheduler
from allennlp.training.moving_average import MovingAverage
from allennlp.training.trainer import Trainer
from allennlp.training.callbacks import TrainerCallback
from allennlp.training import util as training_util
from allennlp.training import GradientDescentTrainer

logger = logging.getLogger(__name__)


@Trainer.register("gec_trainer")
class GECTrainer(GradientDescentTrainer):
    """
    An extended GradientDescentTrainer with cold step functionalities.
    """

    def __init__(
        self,
        model: Model,
        optimizer: torch.optim.Optimizer,
        data_loader: DataLoader,
        patience: Optional[int] = None,
        validation_metric: Union[str, List[str]] = "-loss",
        validation_data_loader: DataLoader = None,
        num_epochs: int = 20,
        serialization_dir: Optional[Union[str, os.PathLike]] = None,
        checkpointer: Optional[Checkpointer] = None,
        cuda_device: Optional[Union[int, torch.device]] = None,
        grad_norm: Union[float, bool] = False,
        grad_clipping: Optional[float] = None,
        learning_rate_scheduler: Optional[LearningRateScheduler] = None,
        momentum_scheduler: Optional[MomentumScheduler] = None,
        moving_average: Optional[MovingAverage] = None,
        callbacks: List[TrainerCallback] = None,
        distributed: bool = False,
        local_rank: int = 0,
        world_size: int = 1,
        num_gradient_accumulation_steps: int = 1,
        use_amp: bool = False,
        enable_default_callbacks: bool = True,
        run_confidence_checks: bool = True,
        grad_scaling: bool = True,
        ddp_wrapped_model: Optional[DdpWrappedModel] = None,
        cold_step_count: int = 0,
        cold_lr: float = 1e-3,
        **kwargs,
    ) -> None:
        super().__init__(
            model,
            optimizer,
            data_loader,
            patience,
            validation_metric,
            validation_data_loader,
            num_epochs,
            serialization_dir,
            checkpointer,
            cuda_device,
            grad_norm,
            grad_clipping,
            learning_rate_scheduler,
            momentum_scheduler,
            moving_average,
            callbacks,
            distributed,
            local_rank,
            world_size,
            num_gradient_accumulation_steps,
            use_amp,
            enable_default_callbacks,
            run_confidence_checks,
            grad_scaling,
            ddp_wrapped_model,
            **kwargs,
        )

        self.cold_step_count = cold_step_count
        self.cold_lr = cold_lr

    def _try_train(self) -> Tuple[Dict[str, Any], int]:

        logger.info("Beginning training.")

        val_metrics: Dict[str, float] = {}
        metrics: Dict[str, Any] = {}
        training_start_time = None

        if self.cold_step_count > 0:
            base_lr = self.optimizer.param_groups[0]["lr"]
            for param_group in self.optimizer.param_groups:
                param_group["lr"] = self.cold_lr
            self.model.text_field_embedder._token_embedders["bert"].set_weights(
                freeze=True
            )

        metrics["best_epoch"] = self._metric_tracker.best_epoch
        for key, value in self._metric_tracker.best_epoch_metrics.items():
            metrics["best_validation_" + key] = value

        for epoch in range(self._num_epochs):
            if epoch == self.cold_step_count and epoch != 0:
                for param_group in self.optimizer.param_groups:
                    param_group["lr"] = base_lr
                self.model.text_field_embedder._token_embedders["bert"].set_weights(
                    freeze=False
                )

            epoch_start_time = time.time()
            train_metrics = self._train_epoch(epoch)

            if self._epochs_completed < self._start_after_epochs_completed:
                # We're still catching up with the checkpoint, so we do nothing.
                # Note that we have to call _train_epoch() even when we know the epoch is skipped. We have to
                # read from the data loader, because the data loader and dataset readers might use randomness,
                # and we have to make sure we consume exactly the same instances in exactly the same way every
                # time we train, even when starting from a checkpoint, so that we update the randomness
                # generators in the same way each time.
                self._epochs_completed += 1
                self._batches_in_epoch_completed = 0
                continue
            if training_start_time is None:
                training_start_time = epoch_start_time

            # get peak of memory usage
            for key, value in train_metrics.items():
                if key.startswith("gpu_") and key.endswith("_memory_MB"):
                    metrics["peak_" + key] = max(metrics.get("peak_" + key, 0), value)
                elif key.startswith("worker_") and key.endswith("_memory_MB"):
                    metrics["peak_" + key] = max(metrics.get("peak_" + key, 0), value)

            this_epoch_val_metric: Optional[float] = None
            if (
                self._should_validate_this_epoch
                and self._validation_data_loader is not None
            ):
                with torch.no_grad():
                    # We have a validation set, so compute all the metrics on it.
                    val_loss, val_reg_loss, num_batches = self._validation_loss(epoch)

                    # It is safe again to wait till the validation is done. This is
                    # important to get the metrics right.
                    if self._distributed:
                        dist.barrier()

                    val_loss = dist_reduce_sum(val_loss)
                    num_batches = dist_reduce_sum(num_batches)
                    if val_reg_loss is not None:
                        val_reg_loss = dist_reduce_sum(val_reg_loss)

                    val_metrics = training_util.get_metrics(
                        self.model,
                        val_loss,
                        val_reg_loss,
                        batch_loss=None,
                        batch_reg_loss=None,
                        num_batches=num_batches,
                        reset=True,
                    )

                    # Check validation metric for early stopping
                    this_epoch_val_metric = self._metric_tracker.combined_score(
                        val_metrics
                    )
                    self._metric_tracker.add_metrics(val_metrics)

            # Create overall metrics dict
            training_elapsed_time = time.time() - training_start_time
            metrics["training_duration"] = str(
                datetime.timedelta(seconds=training_elapsed_time)
            )
            metrics["epoch"] = epoch

            for key, value in train_metrics.items():
                metrics["training_" + key] = value
            for key, value in val_metrics.items():
                metrics["validation_" + key] = value

            if (
                self._should_validate_this_epoch
                and self._metric_tracker.is_best_so_far()
            ):
                # Update all the best_ metrics.
                # (Otherwise they just stay the same as they were.)
                metrics["best_epoch"] = epoch
                for key, value in val_metrics.items():
                    metrics["best_validation_" + key] = value

                self._metric_tracker.best_epoch_metrics = val_metrics

            if self._serialization_dir and self._primary:
                common_util.dump_metrics(
                    os.path.join(
                        self._serialization_dir, f"metrics_epoch_{epoch}.json"
                    ),
                    metrics,
                )

            # The Scheduler API is agnostic to whether your schedule requires a validation metric -
            # if it doesn't, the validation metric passed here is ignored.
            if self._learning_rate_scheduler:
                self._learning_rate_scheduler.step(this_epoch_val_metric)
            if self._momentum_scheduler:
                self._momentum_scheduler.step(this_epoch_val_metric)
            for callback in self._callbacks:
                callback.on_epoch(
                    self, metrics=metrics, epoch=epoch, is_primary=self._primary
                )

            self._epochs_completed += 1
            self._batches_in_epoch_completed = 0

            checkpoint_saved = False
            if self._checkpointer is not None:
                # The checkpointer saves state from the learning rate scheduler, momentum scheduler, moving
                # average, and callbacks, so we have to make sure those are updated before we save the
                # checkpoint here.
                checkpoint_saved = self._checkpointer.maybe_save_checkpoint(
                    self, self._epochs_completed, self._batches_in_epoch_completed
                )

                # Wait for each primary process to finish saving the checkpoint
                if self._distributed:
                    dist.barrier()

            if (
                self._should_validate_this_epoch
                and self._serialization_dir
                and self._metric_tracker.is_best_so_far()
            ):
                should_save_model_state: bool
                if (
                    self._ddp_wrapped_model is not None
                    and self._ddp_wrapped_model.is_sharded
                ):
                    # Each worker saves its own shard for now (we combine the shards later).
                    self._best_model_filename = os.path.join(
                        self._serialization_dir, f"best_w{self._rank}.th"
                    )
                    should_save_model_state = True
                else:
                    self._best_model_filename = os.path.join(
                        self._serialization_dir, "best.th"
                    )
                    should_save_model_state = self._primary

                if should_save_model_state:
                    if self._moving_average is None:
                        # If we're not using a moving average and the checkpointer just saved a checkpoint,
                        # we can just copy over that model state checkpoint to the '_best_model_filename'.
                        # Otherwise we need to save the model state on our own.
                        if self._checkpointer is not None and checkpoint_saved:
                            last_checkpoint = (
                                self._checkpointer.find_latest_checkpoint()
                            )
                            assert last_checkpoint is not None
                            model_state_file, _ = last_checkpoint
                            if os.path.exists(self._best_model_filename):
                                os.remove(self._best_model_filename)
                            hardlink_or_copy(
                                model_state_file, self._best_model_filename
                            )
                        else:
                            self._save_model_state(self._best_model_filename)
                    else:
                        self._moving_average.assign_average_value()
                        try:
                            self._save_model_state(self._best_model_filename)
                        finally:
                            self._moving_average.restore()

            # Wait for the primary process to finish saving the best
            if self._distributed:
                dist.barrier()

            epoch_elapsed_time = time.time() - epoch_start_time
            logger.info(
                "Epoch duration: %s", datetime.timedelta(seconds=epoch_elapsed_time)
            )

            if self._metric_tracker.should_stop_early():
                logger.info("Ran out of patience. Stopping training.")
                break

            if epoch < self._num_epochs - 1:
                time_per_epoch = training_elapsed_time / (
                    (epoch + 1) - self._start_after_epochs_completed
                )
                # Note: If the first non-skipped epoch is half skipped (because it was checkpointed half-way
                # through), then this estimate is going to be optimistic.
                estimated_time_remaining = (
                    time_per_epoch * self._num_epochs
                ) - training_elapsed_time
                formatted_time = str(
                    datetime.timedelta(seconds=int(estimated_time_remaining))
                )
                logger.info("Estimated training time remaining: %s", formatted_time)
        else:
            epoch = self._num_epochs - 1

        # Load the best model state before returning
        if self._best_model_filename is None or self._metric_tracker.is_best_so_far():
            self._finalize_model()
        else:
            # The model we're loading here has already been finalized.
            self._load_model_state(self._best_model_filename)

        return metrics, epoch

```

</p>
</details>

**Comment by epwalsh** [comment] 2022-03-22 16:59
Thanks. So in order to make this trainer work from a config file, you'll need to change the types of the `optimizer` and `learning_rate_scheduler` parameters to `Lazy[Optimizer]` and `Optional[Lazy[LearningRateScheduler]]`, respectively (`Lazy` comes from `allennlp.common.lazy`).

Then you'll have to construct those lazy objects before passing them into `super().__init__(...)`. E.g.
```python
optimizer = optimizer.construct(model_parameters=[[n, p] for n, p in model.named_parameters() if p.requires_grad])
learning_rate_scheduler = learning_rate_scheduler.construct(optimizer=optimizer)
```

**Comment by epwalsh** [comment] 2022-03-24 16:53
I'm closing this since it's not a bug, but feel free to continue this thread if you need more help getting your trainer to work. ✌️

**Closed by epwalsh** 2022-03-24 16:53 UTC
Labels: bug
