### ISSUE TITLE
Can't reproduce results moving away from bert_pretrained

### ISSUE THREAD

**Issue by vin-ivar** [allenai/allennlp#4216] opened 2020-05-10 12:50 UTC
**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.8/3.7.7
 - AllenNLP version: v0.9.0/v1.0.0rc3
 - PyTorch version: 1.4.0

**Question**
I've been trying to move away from v0.9.0's use of `bert_pretrained`, which looks like it relies on the older HuggingFace libraries, to `pretrained_transformer`. Unfortunately, my results look a lot poorer, even when I do this programmatically and not via configs. I've contrasted a few different scenarios:

1. Baseline: dependency parser, v0.9.0, `bert_pretrained`. Works fine.
2. Old, custom model: ignored the `text_field_embedder` in (1) and added a custom `BertModel.from_pretrained` to my parser. Poor results.
3. Newer model, config: upgraded to v1.0.0rc3, modified the config to say `pretrained_transformer`. Poor results.
4. Newer model, manual: also v1.0.0rc3, also used a custom `BertModel.from_pretrained`. Poor results.

I'm using mostly the provided dependency parser configuration, together with the provided class (v0.9.0) or with the class from `allennlp-models` (v1.0.0). Tokenisation etc. seem to be fine. Is there something specific I need to do to move on to v1.0.0?

**Comment by matt-gardner** [comment] 2020-05-11 14:46
This is pretty hard for us to debug without a lot more information.  It'd be a lot easier to make progress on this if you could confirm that the problem exists with our implementation of the dependency parser.  If training our dependency parser does indeed get poor results with new code, that is definitely something we want to know about, and it suggests there is some issue in the library, or in our dependencies.  If it gets expected results, then it suggests there's something different going on in your code, and we can try to figure out why.

**Comment by namednil** [comment] 2020-06-20 10:33
Hi,

I encountered a similar issue. In AllenNLP 0.9, a learnt weighted average of the layers was computed, in version 1.0 only the last layer is used. I modified the new code accordingly (see https://gist.github.com/namednil/dae947a52629e7c9bbbb911e541f3126), and first results look very promising. Perhaps that also works for you? Potentially, the option of a weighted average of layers would be nice to have in a future release of AllenNLP?

**Comment by epwalsh** [comment] 2020-06-21 02:03
@namednil I'm not sure when or why this changed in AllenNLP, but I think we should definitely still support it. Would you be interested in making a PR?

**Comment by edchengg** [comment] 2020-06-22 14:31
I encountered a similar issue with Allennlp 1.0 SRL bert model. I can't reproduce the result with config file in both training and evaluation with a fine-tuned model. #4392

**Comment by namednil** [comment] 2020-06-23 09:07
@epwalsh I'll try to find the time in the next couple of days. I don't see immediately how to write unit tests for this though.

**Comment by epwalsh** [comment] 2020-07-08 21:39
Hey @namednil, just thought I'd ping you on this. I can take this over if you're too busy

**Comment by namednil** [comment] 2020-07-09 15:51
Oh, sorry! Yes, I'm quite busy at the moment. That would be great, if you don't mind doing this.

**Comment by epwalsh** [comment] 2020-07-09 16:19
@namednil no worries! I've created a separate feature request to track this by the way: https://github.com/allenai/allennlp/issues/4455

**Comment by epwalsh** [comment] 2020-08-19 16:40
@vin-ivar are you still having issues?

**Comment by epwalsh** [comment] 2020-09-03 17:10
Closing. Will re-open if I hear it's still an issue.

**Closed by epwalsh** 2020-09-03 17:10 UTC
