### ISSUE TITLE
No module named allennlp_models

### ISSUE THREAD

**Issue by DalilaB000** [allenai/allennlp#4657] opened 2020-09-22 18:34 UTC
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [ ] I have included in the "Environment" section below the output of `pip freeze`.
- [ ] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

Installed the latest allennp in its own environment, I have the latest Python 3.7 
I'm trying to run the sample example:
```
 from allennlp.predictors.predictor import Predictor
import allennlp_models.tagging
predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/ner-model-2020.02.10.tar.gz")
predictor.predict(
  sentence="Did Uriah honestly think he could beat The Legend of Zelda in under three hours?"
)
```

but I either get an error that no module allennlp.predictos exists  or no module allennlp_models exists
<summary><b>Python traceback:</b></summary>
<p>

```
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS:

Python version:

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
```

</p>
</details>

**Comment by epwalsh** [comment] 2020-09-23 16:01
Closing because duplicate of https://github.com/allenai/allennlp/issues/4658

**Closed by epwalsh** 2020-09-23 16:01 UTC
Labels: bug
