### ISSUE TITLE
From where can I find pretrained models for the current master ?

### ISSUE THREAD

**Issue by datix-vishu** [allenai/allennlp#4007] opened 2020-03-31 09:56 UTC
@ZhaofengWu @schmmd _, please take a look at this_ 

I downloaded **"fine-grained-ner-model-elmo-2020.02.10.tar"** for the current model and I'm getting a "RuntimeError: Error(s) in loading state_dict for CrfTagger:". 

Is this the right model for the current master or should try a different model ? 

**_Code :_** 
`from allennlp.predictors import Predictor`
`ner_model = Predictor.from_path(".../fine-grained-ner-model-elmo-2020.02.10.tar.gz")`

**_Error :_** 
`RuntimeError: Error(s) in loading state_dict for CrfTagger:
	Missing key(s) in state_dict: "encoder._module.forward_layer_0.cell.input_linearity.weight", "encoder._module.forward_layer_0.cell.state_linearity.weight", "encoder._module.forward_layer_0.cell.state_linearity.bias", "encoder._module.backward_layer_0.cell.input_linearity.weight", "encoder._module.backward_layer_0.cell.state_linearity.weight", "encoder._module.backward_layer_0.cell.state_linearity.bias", "encoder._module.forward_layer_1.cell.input_linearity.weight", "encoder._module.forward_layer_1.cell.state_linearity.weight", "encoder._module.forward_layer_1.cell.state_linearity.bias", "encoder._module.backward_layer_1.cell.input_linearity.weight", "encoder._module.backward_layer_1.cell.state_linearity.weight", "encoder._module.backward_layer_1.cell.state_linearity.bias". 
	Unexpected key(s) in state_dict: "encoder._module.forward_layer_0.input_linearity.weight", "encoder._module.forward_layer_0.state_linearity.weight", "encoder._module.forward_layer_0.state_linearity.bias", "encoder._module.backward_layer_0.input_linearity.weight", "encoder._module.backward_layer_0.state_linearity.weight", "encoder._module.backward_layer_0.state_linearity.bias", "encoder._module.forward_layer_1.input_linearity.weight", "encoder._module.forward_layer_1.state_linearity.weight", "encoder._module.forward_layer_1.state_linearity.bias", "encoder._module.backward_layer_1.input_linearity.weight", "encoder._module.backward_layer_1.state_linearity.weight", "encoder._module.backward_layer_1.state_linearity.bias". 
	size mismatch for text_field_embedder.token_embedder_token_characters._embedding._module.weight: copying a param with shape torch.Size([119, 25]) from checkpoint, the shape in current model is torch.Size([57007, 25]).`

**Comment by schmmd** [comment] 2020-03-31 15:23
@datix-vishu what version of AllenNLP are you using?

**Comment by datix-vishu** [comment] 2020-03-31 15:58
@schmmd its the current master

**Comment by schmmd** [comment] 2020-03-31 16:07
@datix-vishu things are in flux now, but we're going to have a release candidate soon to get out of this mess.  @dirkgr has been working on this and probably knows what the issue is as he's been working on https://github.com/allenai/allennlp-demo/pull/335, but I'm not sure we have an updated NER model.

**Comment by datix-vishu** [comment] 2020-03-31 16:09
@schmmd Is there a version to use the following 3 models in a single version ?

coref : coref-spanbert-large-2020.02.27.tar
NER : fine-grained-ner-model-elmo-2020.02.10.tar
SRL : openie-model.2020.03.26.tar

**Comment by schmmd** [comment] 2020-03-31 16:23
@datix-vishu I'd check out whatever we had on 2020.02.28 and try that...

**Comment by datix-vishu** [comment] 2020-03-31 16:25
It's that I can't change the coref model now, it works really good. So I need to adjust NER.

**Comment by Hacker-VP** [comment] 2020-03-31 21:11
@dirkgr is there any method for NER using which I can get the named entities as a list or in a simpler way other than the standard predict method ?

I just want the names of people from the text

**Comment by dirkgr** [comment] 2020-04-01 00:49
I have a task assigned to me already to bring back the pretrained model calls from https://github.com/allenai/allennlp-hub/blob/master/allennlp_hub/pretrained/allennlp_pretrained.py.

In the meantime, @datix-vishu, you can find URLs for the pre-trained models here: https://github.com/allenai/allennlp-demo/blob/55b05b36bcd1dd234011760e1597e2410b4a6f09/models.json
This is admittedly not the most discoverable place, but I promise, we're fixing it :-) I checked, and the regular NER model works. The fine-tuned in that list does not.

**Comment by dirkgr** [comment] 2020-04-01 00:55
@Hacker-VP, I'll answer your question in #3998.

**Closed** 2020-04-01 06:36 UTC
