### ISSUE TITLE
Remove / move internal transformer implementations

### ISSUE THREAD

**Issue by brendan-ai2** [allenai/allennlp#2270] opened 2019-01-03 20:40 UTC
We currently have a handful of transformer implementations. At least the following:

https://github.com/allenai/allennlp/blob/master/allennlp/modules/seq2seq_encoders/multi_head_self_attention.py
https://github.com/allenai/allennlp/blob/master/allennlp/modules/seq2seq_encoders/bidirectional_language_model_transformer.py#L139
https://github.com/allenai/allennlp/blob/master/allennlp/modules/openai_transformer.py

We should remove these and rely on an external implementation. Perhaps, Pytorch's `nn.Transformer`. This will (very likely) be a breaking change for our existing models.

**Comment by schmmd** [comment] 2019-01-04 21:10
@matt-peters during issue review it came up that you might propose standardizing on the openai transformer (assuming experiments work out).  Is that accurate?

**Comment by nelson-liu** [comment] 2019-05-01 00:22
FWIW, looks like the new PyTorch 1.1 includes a [`torch.nn.MultiheadAttention`](https://pytorch.org/docs/stable/nn.html?highlight=multiheadattention#torch.nn.MultiheadAttention)

**Comment by maxdel** [comment] 2019-05-02 20:25
Moreover, this module was landed as a part of [this WIP Transformer PR](https://github.com/pytorch/pytorch/pull/19274)

**Comment by zhangguanheng66** [comment] 2019-05-02 21:00
Thanks @maxdel, we have put together a PR for Transformer in PyTorch. Feel free to comment. 

The transformer module is supported by torch.nn.MultiheadAttention. We have a plan to improve the efficiency of this operator in the near future. @cpuhrsch.

**Comment by cpuhrsch** [comment] 2019-05-03 18:26
Hey all, please let us know how we can help you guys deduplicate some of your work and better support this library overall!

We're eager to provide a good set of tools or a full implementation of what you need for your Transformers.

Also, if you have more general feature requests, we'd be eager to hear about them as well.

**Comment by sai-prasanna** [comment] 2019-05-04 12:36
@cpuhrsch Need some help figuring out the decoder abstraction - https://github.com/allenai/allennlp/pull/2517 .

**Comment by nelson-liu** [comment] 2019-08-08 18:32
The new version of pytorch includes a [`nn.Transformer`](https://pytorch.org/docs/stable/nn.html?highlight=transformer#torch.nn.Transformer) module

**Comment by zhangguanheng66** [comment] 2019-08-20 21:32
Hello everyone, I just want to check if we could provide any help to apply `nn.Transformer` module. We want to better support AllenNLP and avoid the duplicate work. We could implement more features if you feel necessary to better serve this repo.

**Comment by brendan-ai2** [comment] 2020-01-07 01:06
Updated description to reflect that we don't intend to maintain our own transformer implementation anymore.

**Comment by zhangguanheng66** [comment] 2020-01-07 21:36
If you find any problems and difficulties when mitigating to pytorch transformer/multiheadattention, please ping me @zhangguaheng66 on pytorch Github. We are happy to provide some hands-on help.

**Comment by schmmd** [comment] 2020-01-08 00:20
@zhangguanheng66 fantastic and thanks for reaching back out.  I'm pretty sure we'll be doing this in the next two months.

**Comment by matt-gardner** [comment] 2020-02-10 18:59
What we should do: remove all of our internal implementations of multi-headed attention / self attention, in favor of huggingface and pytorch implementations.  Some of our old models depend on this code, though.  As we split out those models into their own repos, our internal implementations should go with them, when it makes sense.  If we have any implementations that are not used in one of the models that we are putting into their own repo, they should just be removed.

**Comment by zhangguanheng66** [comment] 2020-02-10 19:53
We opened an issue to keep a record of change requests for MHA and transformer. If you have some implementations what are worth landing in pytorch repo, feel free to send requests there. https://github.com/pytorch/pytorch/issues/32590

**Comment by dirkgr** [comment] 2020-03-04 02:09
Notes to self:
 * `BidirectionalLanguageModelTransformer` should go with the model.
 * `StackedSelfAttentionEncoder` can possibly be transparently replaced with a PyTorch implementation if we're careful with the names of the parameters?

**Comment by dirkgr** [comment] 2020-03-04 03:04
I started adding the transformer implementation from PyTorch here: #3898

**Comment by dirkgr** [comment] 2020-04-13 20:24
This is done already.

**Closed by dirkgr** 2020-04-13 20:24 UTC
Labels: 2 Weeks, Breaking change

**Comment by zhangguanheng66** [comment] 2020-04-13 20:30
@dirkgr Nice job for the transformer wrapper.

I saw there is a seq-to-seq encoder [MultiHeadSelfAttention](https://github.com/allenai/allennlp/blob/61ec73b3ad9d8c4524789814bfa687888a71b996/allennlp/modules/seq2seq_encoders/__init__.py#L16). Is there any plan for it?

**Comment by dirkgr** [comment] 2020-04-14 06:30
Despite the name, that module is not strictly a transformer as designed by Devlin et al. Also, it was only used by QaNet, so I moved it there: https://github.com/allenai/allennlp-models/blob/master/allennlp_models/rc/qanet/multi_head_self_attention.py

If you need it, feel free to grab it from there and add it to your own code.

**Comment by zhangguanheng66** [comment] 2020-04-14 14:49
> Despite the name, that module is not strictly a transformer as designed by Devlin et al. Also, it was only used by QaNet, so I moved it there: https://github.com/allenai/allennlp-models/blob/master/allennlp_models/rc/qanet/multi_head_self_attention.py
> 
> If you need it, feel free to grab it from there and add it to your own code.

Thanks @dirkgr . I'm wondering if you plan to wrap up [nn.MultiheadAttention](https://pytorch.org/docs/stable/nn.html?highlight=nn%20multiheadattention#torch.nn.MultiheadAttention) and replace `multi_head_self_attention` function. To me, they are very similar.

**Comment by dirkgr** [comment] 2020-04-15 21:20
`nn.MultiheadAttention` is not a seq2seq module. It implements the attention part of the transformer architecture. The pytorch transformer code (and thus our wrapper of it) uses `nn.MultiheadAttention` internally.

If you need it in your own `forward()` functions, you can just call it! There is no need for AllenNLP to wrap it.
