### ISSUE TITLE
Convert AllenNLP model to transformers model

### ISSUE THREAD

**Issue by PrettyPrettyMeng** [allenai/allennlp#4541] opened 2020-08-06 05:10 UTC
It seems that in current AllenNLP, the model we save and create cannot interact with apis in transformers. (because we have different keys in model.state_dict()) I think it will be highly helpful if we can convert a trained AllenNLP model to a transformers model. This will provide more flexibility in applications and researchs.

**Comment by wj-Mcat** [comment] 2020-08-06 09:07
Waiting for this feature.

**Comment by matt-gardner** [comment] 2020-08-06 14:55
In general, this isn't possible, because, e.g., they don't have coref or SRL models.  We do want to make it easy to do this when it is possible, though.  For instance, you could take the base transformer weights and save them.  This isn't very hard right now, just a few lines in a simple script, but we could document it / make it one line instead.  Can you give more detail on what exactly you want to do?  Which models, and which weights, are you hoping to have be compatible?

For more info on a simple script to do what you want, see [here](https://github.com/allenai/allennlp/issues/4351#issuecomment-649019431).

**Comment by PrettyPrettyMeng** [comment] 2020-08-06 15:09
> In general, this isn't possible, because, e.g., they don't have coref or SRL models. We do want to make it easy to do this when it is possible, though. For instance, you could take the base transformer weights and save them. This isn't very hard right now, just a few lines in a simple script, but we could document it / make it one line instead. Can you give more detail on what exactly you want to do? Which models, and which weights, are you hoping to have be compatible?
> 
> For more info on a simple script to do what you want, see [here](https://github.com/allenai/allennlp/issues/4351#issuecomment-649019431).

Thanks for your quick reply! For example, if I want to run some example scripts from transformers on a trained AllenNLP Roberta model, it seems to be troublesome in my case. It would also be great if there is more example scripts in AllenNLP.

**Comment by matt-gardner** [comment] 2020-08-06 15:15
That's still not enough detail.  What exactly do you want to do?  Which scripts?  "Roberta" isn't a single model.

**Comment by PrettyPrettyMeng** [comment] 2020-08-06 15:25
For example, I have finetuned Roberta to train a text classifier. Based on this, I want to run language modeling on this trained model, using this [https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_language_modeling.py](script). It would be great if we can directly apply an AllenNLP model to scripts like this.

**Comment by AkshitaB** [comment] 2020-08-07 16:13
Closing as a duplicate of #4351

**Closed by AkshitaB** 2020-08-07 16:13 UTC
Labels: Feature request
