### ISSUE TITLE
serialiation_dir existence check is too tight

### ISSUE THREAD

**Issue by cristipp** [allenai/allennlp#1250] opened 2018-05-18 21:54 UTC
AllenNLP refuses to train if the serialization directory exists. When using Beaker to collect the output, the serialization directory is mounted by Beaker[Docker] and can't be deleted.

Currently, the serialization_dir existence check is skipped if it point to `/output`, which leads to confusion if Beaker results directory is set to something else than `/output`. 

Alternatively, the serialiation_dir existence check could be relaxed to "serialization directory exists and is not empty". This would satisfy the intent of the check [do not clobber previous runs], as well as Beaker runs with arbitrary results directory.

**Comment by joelgrus** [comment] 2018-05-18 21:58
duplicate of #1239 😄

**Closed by joelgrus** 2018-05-18 21:58 UTC
