### ISSUE TITLE
Automatic Implementation of from_params fails on Python 3.6.0

### ISSUE THREAD

**Issue by Fritz449** [allenai/allennlp#1660] opened 2018-08-24 05:33 UTC
I tried to train a model for NER using regular config. 
When it tries to initialize components, I get this error:

```python3 -m allennlp.run train tutorials/getting_started/crf_tagger.json -s ~/tmp/model --recover
2018-08-23 15:20:56,396 - INFO - allennlp.common.params - random_seed = 13370
2018-08-23 15:20:56,396 - INFO - allennlp.common.params - numpy_seed = 1337
2018-08-23 15:20:56,396 - INFO - allennlp.common.params - pytorch_seed = 133
2018-08-23 15:20:56,398 - INFO - allennlp.common.checks - Pytorch version: 0.4.1
2018-08-23 15:20:56,400 - INFO - allennlp.commands.train - Recovering from prior training at /Users/fritz/tmp/model.
2018-08-23 15:20:56,425 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.dataset_reader.DatasetReader'> from params {'tag_label': 'ner', 'token_indexers': {'token_characters': {'type': 'characters'}, 'tokens': {'lowercase_tokens': True, 'type': 'single_id'}}, 'type': 'conll2003'} and extras {}
2018-08-23 15:20:56,426 - INFO - allennlp.common.params - dataset_reader.type = conll2003
2018-08-23 15:20:56,426 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.conll2003.Conll2003DatasetReader'> from params {'tag_label': 'ner', 'token_indexers': {'token_characters': {'type': 'characters'}, 'tokens': {'lowercase_tokens': True, 'type': 'single_id'}}} and extras {}
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/fritz/tmp/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/Users/fritz/tmp/allennlp/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/Users/fritz/tmp/allennlp/allennlp/commands/train.py", line 102, in train_model_from_args
    args.recover)
  File "/Users/fritz/tmp/allennlp/allennlp/commands/train.py", line 132, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/Users/fritz/tmp/allennlp/allennlp/commands/train.py", line 261, in train_model
    all_datasets = datasets_from_params(params)
  File "/Users/fritz/tmp/allennlp/allennlp/commands/train.py", line 139, in datasets_from_params
    dataset_reader = DatasetReader.from_params(params.pop('dataset_reader'))
  File "/Users/fritz/tmp/allennlp/allennlp/common/from_params.py", line 246, in from_params
    return subclass.from_params(params=params, **extras)
  File "/Users/fritz/tmp/allennlp/allennlp/common/from_params.py", line 257, in from_params
    kwargs = create_kwargs(cls, params, **extras)
  File "/Users/fritz/tmp/allennlp/allennlp/common/from_params.py", line 113, in create_kwargs
    annotation = remove_optional(param.annotation)
  File "/Users/fritz/tmp/allennlp/allennlp/common/from_params.py", line 81, in remove_optional
    if origin == Union and len(args) == 2 and args[1] == type(None):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 760, in __eq__
    return self._subs_tree() == other
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 760, in __eq__
    return self._subs_tree() == other
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 760, in __eq__
    return self._subs_tree() == other
  [Previous line repeated 241 more times]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 759, in __eq__
    if not isinstance(other, _Union):
RecursionError: maximum recursion depth exceeded in __instancecheck__
```

I also checked that I get the same error if I try to initialize model (bi-LSTM) from that config.
The config is the same as ner.jsonnet from training_configs except data paths.

What do I do wrong?

**Comment by nelson-liu** [comment] 2018-08-24 07:49
are you on the latest release (i.e., `pip install`'d verison) or the master version?

**Comment by Fritz449** [comment] 2018-08-24 07:54
I get this error if I use allennlp 0.6.0 or master version and don't get if I use allennlp 0.5.1

**Comment by nelson-liu** [comment] 2018-08-24 08:05
I see, what version of python are you on (I'm guessing python `3.6.0`? you can check with `python --version`) Looks like this is a bug that was fixed in Python 3.6.1 .  See this message on the Python issue tracker: https://bugs.python.org/issue29246 . I can't reproduce this on Python 3.6.6 , so I'd guess that updating Python should work...

@joelgrus maybe it's worth mentioning that it looks like allennlp actually has a >3.6.0 requirement?

**Comment by nelson-liu** [comment] 2018-08-24 08:07
(the reason why you get it in allennlp 0.6.0 is because in that version, we changed `from_params` to be automatically implemented based on the type hints. See the release notes for more details on this: https://github.com/allenai/allennlp/releases/tag/v0.6.0)

**Comment by Fritz449** [comment] 2018-08-25 05:25
Ok, thank you for the help!

**Comment by joelgrus** [comment] 2018-08-25 11:52
I'm not sure where to put it in our docs, but we should bump the version check here:

https://github.com/allenai/allennlp/blob/master/allennlp/__init__.py#L5

I can do that on Monday

**Closed** 2018-08-27 17:27 UTC
