### ISSUE TITLE
ModuleNotFoundError: No module named '/project/dataset_readers' 

### ISSUE THREAD

**Issue by sfuzhenqiz** [allenai/allennlp#2423] opened 2019-01-23 02:10 UTC
**Describe the bug**
The problem is simple, I can't load my own code.

**To Reproduce**
1. I created a clean anaconda python 3.7 environment
2. I install allennlp via this command 
"pip install --target=/cs/natlang-expts/zhenqiz/pip --no-cache-dir allennlp"
3. Then I cd to "/cs/natlang-expts/zhenqiz/pip" and run "python -m allennlp.run test-install". It seems normal so far.
4. Then I tried to run my own model by "python3 -m allennlp.run train project/config_dec4.json --serialization-dir project/new_checkpoints/ --include-package project/dataset_readers --include-package project/models"

project/config_dec4.json is my config file; project/new_checkpoints/ is where I want to put checkpoint; project/dataset_readers is the folder that contains my dataset reader py script; project/models is the folder that contains my model py script. 

**Expected behavior**
Here comes the error.
Traceback (most recent call last):
  File "/cs/natlang-expts/zhenqiz/tools/anaconda3/envs/allennlp/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cs/natlang-expts/zhenqiz/tools/anaconda3/envs/allennlp/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/cs/natlang-expts/zhenqiz/pip/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/cs/natlang-expts/zhenqiz/pip/allennlp/commands/__init__.py", line 71, in main
    import_submodules(package_name)
  File "/cs/natlang-expts/zhenqiz/pip/allennlp/common/util.py", line 288, in import_submodules
    module = importlib.import_module(package_name)
  File "/cs/natlang-expts/zhenqiz/tools/anaconda3/envs/allennlp/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'project/dataset_readers'

**System (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version: 3.7.2
 - AllenNLP version: 0.8.1
 - PyTorch version: (if you installed it yourself)

**Additional context**
I'm quite new to this thing, so I think it might be due to some configuration problems. Could anyone give a hand? THank you

**Comment by joelgrus** [comment] 2019-01-23 02:53
for `--include-package` you need to supply the package *name*, not the path, so (assuming your module structure is set up this way) you should do something like `--include-package project.models`

**Comment by sfuzhenqiz** [comment] 2019-01-23 03:50
> for `--include-package` you need to supply the package _name_, not the path, so (assuming your module structure is set up this way) you should do something like `--include-package project.models`

Hi Joel thank you for the quick reply.

I tried to move those "models", "dataset_readers" folder out of the "project" directory to the current path, and run this command:"python3 -m allennlp.run train project/config_dec4.json --serialization-dir project/new_checkpoints/ --include-package dataset_readers --include-package models", which to some extents it's something similar to your fix right?
But it gave me this error:
Traceback (most recent call last):
File "/cs/natlang-expts/zhenqiz/tools/anaconda3/envs/allennlp/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/cs/natlang-expts/zhenqiz/tools/anaconda3/envs/allennlp/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/cs/natlang-expts/zhenqiz/pip/allennlp/run.py", line 18, in <module>
main(prog="allennlp")
File "/cs/natlang-expts/zhenqiz/pip/allennlp/commands/init.py", line 71, in main
import_submodules(package_name)
File "/cs/natlang-expts/zhenqiz/pip/allennlp/common/util.py", line 290, in import_submodules
path_string = '' if not path else path[0]
TypeError: '_NamespacePath' object does not support indexing

**Comment by joelgrus** [comment] 2019-01-23 04:13
I *suspect* this error is caused by you not having an __init__.py in your `models` and/or `dataset_readers` folders, and I guess it's maybe sort of a bug in that the library should be more robust to that

**Comment by sfuzhenqiz** [comment] 2019-01-23 06:43
> I _suspect_ this error is caused by you not having an `__init__.py` in your `models` and/or `dataset_readers` folders, and I guess it's maybe sort of a bug in that the library should be more robust to that

Yes, there is no init.py file inside the folder. However, some other guys in my lab can run the model without having the init.py file. Would an empty __init__.py file help?

**Comment by joelgrus** [comment] 2019-01-23 15:02
I can't promise it would help, but my theory on what's happening is that if you call `importlib.import_module` on a package that has an `__init__.py` in it, the resulting module has a `__path__` attribute that's just a list (and in particular can be indexed), but that if you call it on a package that has no `__init__py`, then the module's `__path__` attribute is a `_NamespacePath` object, which can't be indexed, which crashes.

If I'm correct, adding an empty `__init__.py` will solve this problem. It would probably also work if you referenced the module itself rather than the containing package: `--include-package models.my_model`

**Comment by aleSuglia** [comment] 2019-01-24 18:42
I can confirm that seems to be a problem. I am getting the same error as the one reported by the OP when the main library folder doesn't have an `__init__` file. 

By adding an empty `__init__` file the problem is solved.

**Comment by brendan-ai2** [comment] 2019-03-22 22:22
Sounds like this is fixed with an empty `__init__.py`. Please reopen if not!

**Closed by brendan-ai2** 2019-03-22 22:22 UTC

**Comment by zwacm** [comment] 2019-08-11 13:28
I encountered the same problem, have you successfully run your code by adding empty _ _init_ _.py file? @sfuzhenqiz
