### ISSUE TITLE
What's the pause before training starts?

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#3285] opened 2019-09-25 15:55 UTC
Note: copied from https://discourse.allennlp.org/t/why-does-starting-training-take-a-while/43

I've noticed that there's always a pause between when the Trainer says that it starts training, to when training actually begins. This can be seen in the stderr of a training run, like so:

    2019-09-25 02:41:45,616 - INFO - allennlp.training.trainer - Training
      0%|          | 0/1245 [00:00<?, ?it/s]
    span_tag_accuracy: 0.9644, pos_accuracy: 0.0000, loss: 0.1180 ||:   0%|          | 1/1245 [00:35<12:25:58, 35.98s/it]
    span_tag_accuracy: 0.9571, pos_accuracy: 0.0000, loss: 0.2097 ||:   2%|2         | 26/1245 [00:46<8:34:11, 25.31s/it]
    span_tag_accuracy: 0.9588, pos_accuracy: 0.0000, loss: 0.1950 ||:   4%|4         | 51/1245 [00:59<5:55:40, 17.87s/it]
    span_tag_accuracy: 0.9591, pos_accuracy: 0.0000, loss: 0.1972 ||:   6%|5         | 71/1245 [01:12<4:08:42, 12.71s/it]
    span_tag_accuracy: 0.9596, pos_accuracy: 0.0000, loss: 0.1909 ||:   7%|7         | 88/1245 [01:22<2:54:59,  9.07s/it]
    span_tag_accuracy: 0.9601, pos_accuracy: 0.0000, loss: 0.1857 ||:   8%|8         | 105/1245 [01:32<2:04:06,  6.53s/it]
    span_tag_accuracy: 0.9603, pos_accuracy: 0.0000, loss: 0.1824 ||:  10%|9         | 122/1245 [02:11<1:38:13,  5.25s/it]
    span_tag_accuracy: 0.9597, pos_accuracy: 0.0000, loss: 0.1815 ||:  11%|#1        | 142/1245 [02:21<1:10:19,  3.83s/it]
    span_tag_accuracy: 0.9595, pos_accuracy: 0.0000, loss: 0.1819 ||:  13%|#3        | 163/1245 [02:31<51:02,  2.83s/it]  
    span_tag_accuracy: 0.9589, pos_accuracy: 0.0000, loss: 0.1843 ||:  15%|#5        | 190/1245 [02:42<36:49,  2.09s/it]
    span_tag_accuracy: 0.9581, pos_accuracy: 0.0000, loss: 0.1970 ||:  17%|#7        | 217/1245 [02:52<27:02,  1.58s/it]
    span_tag_accuracy: 0.9577, pos_accuracy: 0.0000, loss: 0.2000 ||:  20%|#9        | 244/1245 [03:02<20:22,  1.22s/it]
    span_tag_accuracy: 0.9574, pos_accuracy: 0.0000, loss: 0.2001 ||:  22%|##1       | 270/1245 [03:24<17:58,  1.11s/it]
    span_tag_accuracy: 0.9575, pos_accuracy: 0.0000, loss: 0.1998 ||:  23%|##3       | 291/1245 [03:35<14:43,  1.08it/s]
    span_tag_accuracy: 0.9574, pos_accuracy: 0.0000, loss: 0.2017 ||:  26%|##5       | 320/1245 [03:46<11:45,  1.31it/s]
    span_tag_accuracy: 0.9578, pos_accuracy: 0.0000, loss: 0.1995 ||:  28%|##7       | 347/1245 [04:00<10:26,  1.43it/s]
    span_tag_accuracy: 0.9581, pos_accuracy: 0.0000, loss: 0.1980 ||:  29%|##9       | 366/1245 [04:12<09:46,  1.50it/s]
    span_tag_accuracy: 0.9579, pos_accuracy: 0.0000, loss: 0.1978 ||:  32%|###1      | 393/1245 [04:22<08:14,  1.72it/s]
    span_tag_accuracy: 0.9580, pos_accuracy: 0.0000, loss: 0.1979 ||:  34%|###3      | 420/1245 [04:34<07:27,  1.84it/s]
    span_tag_accuracy: 0.9581, pos_accuracy: 0.0000, loss: 0.1958 ||:  36%|###5      | 443/1245 [04:47<07:13,  1.85it/s]
    span_tag_accuracy: 0.9581, pos_accuracy: 0.0000, loss: 0.1983 ||:  38%|###7      | 469/1245 [04:57<06:30,  1.99it/s]

Note how the first batch takes ~36seconds (time between initialization of tqdm reader and completion of first iteration), and subsequent batches are much faster (so it it/s goes down from there). What causes that pause in the first batch?

Probably relevant section of code: https://github.com/allenai/allennlp/blob/30c4271f7f04babb1cb546ab017a104bda011e7c/allennlp/training/trainer.py#L309

cc @brendan-ai2

**Comment by brendan-ai2** [comment] 2019-09-25 19:08
Hey @nelson-liu! There are many variables to consider. What precisely are you training? Could you provide a config file? If I had to make a guess, I'd say the issue is likely related to the data processing. (Since this starts when the trainer tries to get the first batch.) Possibly either:

1) Caching. Are you using https://github.com/allenai/allennlp/blob/master/allennlp/data/iterators/data_iterator.py#L46 and a non-lazy dataset reader? You can test this by turning off all caching and seeing if every batch becomes slow.

2) Use of the `BucketIterator`. It has to bring a certain amount of instances in memory and sort them before it can produce a single batch. You can test this by switching to the `BasicIterator`.

**Comment by matt-gardner** [comment] 2019-09-25 19:14
Yeah, `BucketIterator` seems like the likely culprit to me.  Is there a way to offload this onto the CPU earlier, so we can get started on training on the GPU faster?

**Comment by brendan-ai2** [comment] 2019-09-26 02:19
Conceivably we could start generating the first batch in a separate process while performing other setup tasks, but that would depend on whether the other setup tasks were particularly slow. (Vocab generation might be?)

One important consideration here is deciding what to measure. @nelson-liu is pointing out a legitimate issue with latency, but outside of tests this isn't something we necessarily care about. And for small fixture data, it shouldn't be an issue regardless. Really we want some kind of throughput metric. And fundamentally we care about time until convergence*. (I'm still learning about this, so if anyone has papers or pointers for this sort of thing, I'd appreciate it!)

*Or considering Green AI, perhaps energy used to converge.

**Comment by matt-gardner** [comment] 2019-09-26 16:25
Yeah, I guess there are larger questions here around throughput, but I think the original question has been reasonably answered - this is almost certainly due to the bucket iterator pre-loading and sorting the batches.  Probably whatever gain could be had by making this better is minimal, as it would increase the time spent during the epoch.  I'm going to close this issue.

**Closed by matt-gardner** 2019-09-26 16:25 UTC
