### ISSUE TITLE
Add a conda install for Mac

### ISSUE THREAD

**Issue by theadammurphy** [allenai/allennlp#5258] opened 2021-06-13 14:11 UTC
There is a [conda-forge](https://anaconda.org/conda-forge/allennlp) install for Linux. Could you please also add one for Mac?

https://conda-forge.org/#add_recipe

**Comment by dirkgr** [comment] 2021-06-21 17:43
@h-vetinari, do you know what it would take to get this done?

**Comment by h-vetinari** [comment] 2021-06-21 20:02
Hey all

Thanks for the ping, I've had a long-standing [PR](https://github.com/conda-forge/allennlp-feedstock/pull/19), but it was then still missing osx-builds for pytorch/torchvision. Those have since arrived, but there are still some errors in the test suite on OSX. Any help fixing those is appreciated. :)

**Comment by dirkgr** [comment] 2021-06-21 20:56
Errors in the AllenNLP test suite, or in the torchvision test suite?

**Comment by h-vetinari** [comment] 2021-06-22 07:03
> 
> 
> Errors in the AllenNLP test suite, or in the torchvision test suite?

The AllenNLP test suite. For details, see the [CI results](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=340307&view=results) from https://github.com/conda-forge/allennlp-feedstock/pull/19

**Comment by dirkgr** [comment] 2021-06-23 21:19
It looks like the problem is that
> the OSX binary of PyTorch does not ship with distributed support.

I don't know why that is, but as long as that's the case, the AllenNLP tests won't run.

It's surprising though, because I'm running it on Mac right now, wit PyTorch installed from Conda, and it all works fine, including the distributed setup. Why doesn't it use this version when it runs the tests?

**Comment by dirkgr** [comment] 2021-08-02 21:04
Have not forgotten. Am waiting for the resolution on https://github.com/conda-forge/allennlp-feedstock/pull/19.

**Comment by h-vetinari** [comment] 2021-08-02 22:09
Which Mac's are we talking about? The processor architecture changed with the M1, so building for pre-M1 is different. I'm currently looking to get the osx-x86_64 build running (equals pre-M1), but since conda-forge does not have M1 CI, we can only cross-compile, and I would need someone to test-run a candidate artefact before we can merge.

**Comment by dirkgr** [comment] 2021-08-03 20:37
I am currently not concerned about the M1 Macs. As far as I know, AllenNLP works fine on those with the official PyTorch conda package, so people running that can use that. Of course it would be better if the conda version of PyTorch also worked, but let's get that to work on x86 first before we worry about M1.

**Comment by h-vetinari** [comment] 2021-08-04 00:05
osx-x86_64 builds are available now. :)

**Comment by dirkgr** [comment] 2021-08-04 00:33
Does that mean we can close this issue?

**Comment by h-vetinari** [comment] 2021-08-04 07:04
We can keep it for the M1 packages if you want.

**Comment by dirkgr** [comment] 2021-08-04 18:31
Too many open issues. We'll wait until someone requests them. By that point, the fine folks at Apple and Facebook might have solved some of the problems we'd otherwise have already.

**Closed by dirkgr** 2021-08-04 18:31 UTC
Labels: Feature request

**Comment by Vladimir-Chan** [comment] 2021-11-27 08:01
@dirkgr Hi, there is a [conda-forge](https://anaconda.org/conda-forge/allennlp) install of version 2.6.0. Could you please upgrade it to the stable version 2.8.0?

**Comment by Vladimir-Chan** [comment] 2021-11-27 08:08
@dirkgr Hi, there is a [conda-forge](https://anaconda.org/conda-forge/allennlp) install of version 2.6.0. Could you please upgrade it to the stable version 2.8.0? If it is difficult to build a install for mac, could you please build it for linux?

**Comment by h-vetinari** [comment] 2021-11-30 02:14
> Hi, there is a [conda-forge](https://anaconda.org/conda-forge/allennlp) install of version 2.6.0. Could you please upgrade it to the stable version 2.8.0? If it is difficult to build a install for mac, could you please build it for linux?

There's an effort [underway](https://github.com/conda-forge/allennlp-feedstock/pull/31) to do that, but due to the new dependencies added in 2.7 & 2.8, this is taking longer than expected. Also, if you have an M1, conda-forge is not building allennlp for osx-arm yet, but that could be done in principle.

PS. Posting on long-closed issues makes it very likely that your comment gets overlooked.

**Comment by h-vetinari** [comment] 2021-12-01 04:38
Allennlp 2.8 is now in conda-forge.

**Comment by dirkgr** [comment] 2021-12-01 07:07
Sweet, thank you!

**Comment by RoyLiberman** [comment] 2022-01-17 12:19
can you please add support for mac M1 systems on conda-forge?
