### ISSUE TITLE
Install fails due to unavailable torch dependency

### ISSUE THREAD

**Issue by tomekkorbak** [allenai/allennlp#1546] opened 2018-07-30 14:22 UTC
**Describe the bug**
`pip install allennlp` fails, beacuse it requires `torch==0.4.0`. Since July 26th PyTorch 0.4.1 is out, but PyTorch folks haven't published PyTorch 0.4.0 wheel yet (cf. pytorch/pytorch#9943) and also `pip install torch==0.4.0` fails. Hence you can't install allennlp from scratch now.

**To Reproduce**
`pip install allennlp` in an empty virtualenv

**Expected behavior**
AllenNLP installs.

**System (please complete the following information):**
 - OS: MacOS 10.13
 - Python version: Python 3.6 (also Python 3.7)
 - AllenNLP version: 0.5.1 (also master)
 - PyTorch version: 0.4.0

**Additional context**
Couldn't we make sure all tests pass under PyTorch 0.4.1 and update this requirement?

**Comment by joelgrus** [comment] 2018-07-30 14:53
#1543 updates the code for Pytorch 0.4.1, hopefully I can get that merged today. then we'll need to do a release.

however, I can't reproduce your issue, for me pytorch 0.4.0 pip installs fine:

```
joelg$ pip install --no-cache-dir torch==0.4.0
Collecting torch==0.4.0
  Downloading https://files.pythonhosted.org/packages/6c/41/5454da652b9cf75f4b5706ef71404352b6131484bb966f05c7899e6ac25d/torch-0.4.0-cp36-cp36m-macosx_10_7_x86_64.whl (8.2MB)
    100% |████████████████████████████████| 8.2MB 10.5MB/s
Installing collected packages: torch
Successfully installed torch-0.4.0
```

**Comment by tomekkorbak** [comment] 2018-07-30 19:43
@joelgrus you're right, I got confused while focusing on PyTorch-AllenNLP compatibility (and cleaning up mess I've done on my OS when debugging this...) and at some point forgot to check Python 3.6 instead of 3.7. So it goes like this: `pip install torch==0.4.0` does fail when in virtualenv with Python 3.7, which is expected since only PyTorch 0.4.1 works under Python 3.7 (a somewhat underdocumented fact...), but indeed works when in virtualenv with Python 3.6.

Sorry to bother you & great to see AllenNLP working under Python 3.7 in #1543!

**Closed** 2018-07-30 19:46 UTC
