### ISSUE TITLE
Different results when running Open IE using online demo vs python code

### ISSUE THREAD

**Issue by Tharu87** [allenai/allennlp#4943] opened 2021-01-29 06:28 UTC
The results from the online demo version of Open IE is different from the results I get when calling the model from python code, even it is using the exact same model stated on the demo page (openie-model.2020.03.26.tar.gz). 

For example, the sentence "Yellowstone National Park is in the United States of America." yields the following results when using the online demo:
                            [ARG1: Yellowstone National Park] [V: is] [ARG2: in the United States of America.]
while calling the model from the code yields no results. Anyone can shed some light on why this might be?

**Comment by AkshitaB** [comment] 2021-01-29 07:23
@Tharu87 Thank you for pointing this out. The issue is caused by the latest update to `SpacyTokenizer`, which tags auxiliary verbs like "is" as `AUX` instead of `VERB`. This should be resolved by this [fix](https://github.com/allenai/allennlp-models/pull/206).

**Closed** 2021-01-29 19:04 UTC

**Comment by Tharu87** [comment] 2021-02-02 00:51
Works like a charm, thank you @AkshitaB!
