### ISSUE TITLE
ELMO Embedder using GPU #0 even when initialized with different cuda id. 

### ISSUE THREAD

**Issue by zpaines** [allenai/allennlp#1865] opened 2018-10-04 18:54 UTC
**Describe the bug**
When running an elmoembedder initialized with a cuda id, it still seems to use gpu 0 as well as whichever gpu it should be.

**To Reproduce**
Steps to reproduce the behavior
1. On a machine with multiple GPUs, initialize multiple `ElmoEmbedders`, one per GPU (`ElmoEmbedder(options_file, weight_file, cuda_id)`).
2. Run all those processes at once (so you should have one elmo process per GPU). 
3. Monitor `nvidia-smi`.
4. You will see two processes per ELMO process, one on each GPU and then one process per ELMO instance on GPU 0. 
![image](https://user-images.githubusercontent.com/13563214/46496027-cd36a880-c7cb-11e8-802d-192a48722613.png)

**Expected behavior**
I would not expect processes to use GPUs other than the one their assigned. Or if they do, some documentation would be great (maybe I missed it somewhere?). 

**System (please complete the following information):**
 - OS: Description:	Ubuntu 16.04.5 LTS
 - Python version: `Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux`
 - AllenNLP version: `0.6.1`
 - PyTorch version: `0.4.1`

**Additional context**
I'm running this on an Amazon p3.16xlarge server.

**Comment by qiuwei** [comment] 2018-10-08 06:50
Duplicate of #1748 

It's a bug of pytorch.

**Closed** 2018-10-08 17:55 UTC
