### ISSUE TITLE
Vocabulary min_count is not logged during training

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#2291] opened 2019-01-06 17:39 UTC
It seems like the `min_count` for `Vocabulary` is not automatically logged to the console---any clue why?

**Comment by nelson-liu** [comment] 2019-01-17 23:38
usually the `from_params` logs all of the things that go in, no? I don't think this happens for `Vocabulary` and `min_count`

**Comment by joelgrus** [comment] 2019-01-17 23:41
the last experiment I ran (which was a month) ago, it was logged

```
2018-12-05T05:53:38.258459505Z	2018-12-05 05:53:38,258 - INFO - allennlp.common.params - vocabulary.min_count = None
```

it's hard to see why it wouldn't be now

**Comment by schmmd** [comment] 2019-01-17 23:43
It's also in https://beaker-internal.allenai.org/ex/ex_rkb1qj35ejqt/tasks which I got from http://model-ci.allennlp.org/ (click on a data point to launch the Beaker experiment).

**Comment by schmmd** [comment] 2019-01-18 17:02
Closing for now--but please re-open if you have a log where the `min_count` is missing.

**Comment by EmilyAlsentzer** [comment] 2019-07-17 17:32
I'm having the same issue. When I don't set `min_count`, it is logged correctly. However, when I do set `min_count`, it disappears from the log. Right now I'm doing the following to set the `min_count`

```
"vocabulary":{
      "min_count":{
          "tokens": 5
      }
  }
```

**Comment by joelgrus** [comment] 2019-07-17 17:50
This is caused by a somewhat subtle bug in our recursive from_params logic. Basically, whenever we pop something out of a `Params` object, we log it *unless it's a dict*, in which case we assume that it's a "Params" blob itself. And indeed we wrap it in `Params` before returning it. (Because Params implements a superset of the `dict` API this doesn't hurt anything, but technically it's the wrong thing to do.)

https://github.com/allenai/allennlp/blob/master/allennlp/common/params.py#L251

Anyway, the reason it's not being logged is because the `pop()` logic assumes it's a params object and that its entries will get logged as they're popped off, which isn't the case here, since it's not a params object, just a plain old dict.

It's not obvious to me what the best solution is here, let me noodle on it.

**Comment by joelgrus** [comment] 2019-07-17 17:58
one simple fix would be to add another parameter `force_logging=False` to `Params.pop` and change the check to 

```
if force_logging or not isinstance(value, dict):
    logger.info(...)
```

and then just anyone who's popping off a dict dict has to supply that parameter. 

ideally you'd like to have it happen programmatically, but I don't see a way for the `Params` object to know the difference

**Comment by joelgrus** [comment] 2019-07-17 18:10
or better still, `keep_as_dict=False`, which forces logging and doesn't wrap the return value in a `Params` object

**Comment by joelgrus** [comment] 2019-07-17 18:31
the logic is also weird in another edge case, which may not ever occur. basically, imagine you had some parameter like

```
readers : List[DatasetReader]
```

with a corresponding params object

```
readers: [{type: "squad"}, {type: "triviaqa"}, ... ]
```

then when you do `params.pop("readers")` you'll log it (because it's not a dict) but then it gets passed to `_check_is_dict` which will convert it into a list of Params objects, which then will get logged again when they get consumed, which I doubt is the intended behavior?

**Comment by matt-gardner** [comment] 2019-07-17 18:41
Is there a way to be smart about this inside `from_params` if we know that the type annotation for the object we're constructing is a `Dict`?  Seems like checking for that would solve this problem.

**Comment by joelgrus** [comment] 2019-07-17 18:45
yes and no. you'd still have to add the extra parameter to `pop()` but you could use the type annotation to determine whether it should be set (but that wouldn't help in this particular case, because `Vocabulary` has a custom from_params)

**Comment by matt-gardner** [comment] 2019-07-17 18:52
Oy, ok, yeah, I think you're right.  Seems like the best thing is to add `keep_as_dict=False` to `pop()`, be smart about it in `from_params`, and add it to custom `from_params` methods as needed.

**Closed** 2019-08-13 17:13 UTC
