### ISSUE TITLE
Simple/Smooth/Integrated Gradient examples are returning `'grad_input_1': [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]`

### ISSUE THREAD

**Issue by cfregly** [allenai/allennlp#4703] opened 2020-10-05 02:36 UTC
## Description

Following the example in this Usage section: 
 https://demo.allennlp.org/sentiment-analysis/MjMxMzE4Mw==

Here is my notebook:
https://github.com/data-science-on-aws/workshop/blob/925387e/07_train/wip/99_AllenNLP_RoBERTa_Prediction.ipynb

## Related issues or possible duplicates

- None

## Environment

OS:  Linux

Python version: 3.6.10

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
absl-py==0.10.0
alabaster==0.7.12
allennlp==1.0.0
allennlp-models==1.0.0
anaconda-client==1.7.2
anaconda-project==0.8.3
argh==0.26.2
asn1crypto==1.3.0
astor==0.8.1
astroid==2.4.2
astropy==4.0.1.post1
astunparse==1.6.3
atomicwrites==1.3.0
attrs==19.3.0
Automat==20.2.0
autopep8==1.4.4
autovizwidget==0.15.0
awscli==1.18.137
awswrangler==1.9.3
Babel==2.8.0
backcall==0.1.0
backports.shutil-get-terminal-size==1.0.0
bcrypt==3.2.0
beautifulsoup4==4.8.2
bitarray==1.2.1
bkcharts==0.2
bleach==3.1.4
blis==0.4.1
bokeh==2.0.1
boto==2.49.0
boto3==1.14.60
botocore==1.17.60
Bottleneck==1.3.2
cached-property==1.5.1
cachetools==4.1.1
catalogue==1.0.0
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
click==7.1.1
cloudpickle==1.3.0
clyent==1.2.2
colorama==0.4.3
conllu==3.0
contextlib2==0.6.0.post1
cryptography==2.8
cycler==0.10.0
cymem==2.0.3
Cython==0.29.15
cytoolz==0.10.1
dask==2.14.0
dataclasses==0.7
decorator==4.4.2
defusedxml==0.6.0
diff-match-patch==20181111
distributed==2.14.0
distro==1.5.0
docker==4.3.1
docker-compose==1.26.2
dockerpty==0.4.1
docopt==0.6.2
docutils==0.15.2
en-core-web-sm==2.2.5
entrypoints==0.3
enum-compat==0.0.3
enum34==1.1.10
environment-kernels==1.1.1
et-xmlfile==1.0.1
fastcache==1.1.0
filelock==3.0.12
flake8==3.7.9
Flask==1.1.1
fsspec==0.7.1
future==0.18.2
gast==0.2.2
gevent==1.4.0
glob2==0.7
gmpy2==2.0.8
google-auth==1.21.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
greenlet==0.4.15
grpcio==1.32.0
h5py==2.10.0
hdijupyterutils==0.15.0
HeapDict==1.0.1
html5lib==1.0.1
hypothesis==5.8.3
idna==2.10
imageio==2.8.0
imagesize==1.2.0
importlib-metadata==1.7.0
intervaltree==3.0.2
ipykernel==5.1.4
ipyparallel==6.2.4
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.15.2
jeepney==0.4.3
Jinja2==2.11.1
jmespath==0.9.4
joblib==0.14.1
json5==0.9.4
jsonnet==0.16.0
jsonpickle==1.4.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.2
jupyter-console==6.1.0
jupyter-core==4.6.3
jupyterlab==1.2.6
jupyterlab-server==1.1.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
keyring==21.1.1
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
libarchive-c==2.8
lief==0.9.0
llvmlite==0.31.0
locket==0.2.0
lxml==4.5.0
Markdown==3.2.2
MarkupSafe==1.1.1
matplotlib==3.1.3
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
mock==4.0.1
more-itertools==8.2.0
mpmath==1.1.0
msgpack==1.0.0
multipledispatch==0.6.0
murmurhash==1.0.2
nb-conda==2.2.1
nb-conda-kernels==2.2.3
nbconvert==5.6.1
nbformat==5.0.4
networkx==2.4
nltk==3.4.5
nose==1.3.7
notebook==6.0.3
numba==0.48.0
numexpr==2.7.1
numpy==1.18.5
numpydoc==0.9.2
nvidia-ml-py==10.418.84
oauthlib==3.1.0
olefile==0.46
opencv-python==4.2.0.32
openpyxl==3.0.3
opt-einsum==3.3.0
overrides==3.0.0
packaging==20.3
pandas==1.0.5
pandocfilters==1.4.2
paramiko==2.7.1
parso==0.5.2
partd==1.1.0
path==13.1.0
pathlib2==2.3.5
pathtools==0.1.2
patsy==0.5.1
pep8==1.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.1.2
pkginfo==1.5.0.1
plac==1.1.3
plotly==4.9.0
pluggy==0.13.1
ply==3.11
preshed==3.0.2
prometheus-client==0.7.1
prompt-toolkit==3.0.4
protobuf==3.13.0
protobuf3-to-dict==0.1.5
psutil==5.7.0
psycopg2==2.7.5
psycopg2-binary==2.8.6
ptyprocess==0.6.0
py==1.8.1
py-rouge==1.1
py4j==0.10.7
pyarrow==1.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyAthena==1.10.7
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.20
pycrypto==2.6.1
pycurl==7.43.0.5
pydocstyle==4.0.1
pyflakes==2.1.1
pygal==2.4.0
Pygments==2.6.1
pykerberos==1.2.1
pylint==2.5.3
PyMySQL==0.10.1
PyNaCl==1.4.0
pyodbc===4.0.0-unsupported
pyOpenSSL==19.1.0
pyparsing==2.4.6
pyrsistent==0.16.0
PySocks==1.7.1
pyspark==2.3.4
pytest==5.4.1
pytest-arraydiff==0.3
pytest-astropy==0.8.0
pytest-astropy-header==0.1.2
pytest-doctestplus==0.5.0
pytest-openfiles==0.4.0
pytest-remotedata==0.3.2
python-dateutil==2.8.1
python-dotenv==0.14.0
python-jsonrpc-server==0.3.4
python-language-server==0.31.10
pytz==2019.3
PyWavelets==1.1.1
pyxdg==0.26
PyYAML==5.3.1
pyzmq==18.1.1
QDarkStyle==2.8
QtAwesome==0.7.0
qtconsole==4.7.2
QtPy==1.9.0
regex==2020.7.14
requests==2.24.0
requests-kerberos==0.12.0
requests-oauthlib==1.3.0
retrying==1.3.3
rope==0.16.0
rsa==4.5
Rtree==0.9.4
ruamel-yaml==0.15.87
s3fs==0.4.0
s3transfer==0.3.3
sacremoses==0.0.43
sagemaker==2.9.2
sagemaker-experiments==0.1.24
sagemaker-pyspark==1.4.0
scikit-image==0.16.2
scikit-learn==0.23.1
scipy==1.4.1
seaborn==0.10.0
SecretStorage==3.1.2
Send2Trash==1.5.0
sentencepiece==0.1.91
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.15.0
smdebug==0.9.3
smdebug-rulesconfig==0.1.5
snowballstemmer==2.0.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==2.0
spacy==2.2.4
sparkmagic==0.15.0
Sphinx==3.0.4
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sphinxcontrib-websupport==1.2.1
spyder==4.1.2
spyder-kernels==1.9.0
SQLAlchemy==1.3.13
sqlalchemy-redshift==0.8.1
srsly==1.0.2
statsmodels==0.11.0
stepfunctions==2.0.0rc1
sympy==1.5.1
tables==3.6.1
tblib==1.6.0
tenacity==6.2.0
tensorboard==2.1.1
tensorboard-plugin-wit==1.7.0
tensorboardX==2.1
tensorflow==2.1.0
tensorflow-estimator==2.1.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
texttable==1.6.2
thinc==7.4.0
threadpoolctl==2.1.0
tokenizers==0.7.0
toml==0.10.1
toolz==0.10.0
torch==1.5.1
torch-model-archiver==0.1.1
torchserve==0.1.1
tornado==6.0.4
tqdm==4.44.1
traitlets==4.3.3
transformers==2.11.0
typed-ast==1.4.1
typing-extensions==3.7.4.1
ujson==1.35
unicodecsv==0.14.1
urllib3==1.25.10
wasabi==0.8.0
watchdog==0.10.2
wcwidth==0.1.9
webencodings==0.5.1
websocket-client==0.57.0
Werkzeug==1.0.1
widgetsnbextension==3.5.1
word2number==1.1
wrapt==1.12.1
wurlitzer==2.0.0
xlrd==1.2.0
XlsxWriter==1.2.8
xlwt==1.3.0
yapf==0.28.0
zict==2.0.0
zipp==3.1.0
```

</p>
</details>

## Steps to reproduce
```
!pip install -q allennlp==1.0.0
!pip install -q allennlp-models==1.0.0
```
```
from allennlp.predictors.predictor import Predictor

predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/sst-roberta-large-2020.06.08.tar.gz")

sentence = "a very well-made, funny and entertaining picture."

inputs = {"sentence": sentence}

from allennlp.interpret.saliency_interpreters import SimpleGradient

simple_gradient_interpreter = SimpleGradient(predictor)

simple_gradient_interpretation = simple_gradient_interpreter.saliency_interpret_from_json(inputs)

print(simple_gradient_interpretation)
```
OUTPUT
```
{'instance_1': {'grad_input_1': [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}}
```

</p>
</details>

**Comment by cfregly** [comment] 2020-10-05 02:40
```
from allennlp.interpret.saliency_interpreters import SmoothGradient

smooth_gradient_interpreter = SmoothGradient(predictor)

smooth_gradient_interpretation = smooth_gradient_interpreter.saliency_interpret_from_json(inputs)

print(smooth_gradient_interpretation)
```
OUTPUT
```
{'instance_1': {'grad_input_1': [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}}
```

**Comment by cfregly** [comment] 2020-10-05 02:41
```
from allennlp.interpret.saliency_interpreters import IntegratedGradient

integrated_gradient_interpreter = IntegratedGradient(predictor)

integrated_gradient_interpretation = integrated_gradient_interpreter.saliency_interpret_from_json(inputs)

print(integrated_gradient_interpretation)
```
OUTPUT
```
{'instance_1': {'grad_input_1': [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}}
```

**Comment by dirkgr** [comment] 2020-10-09 23:09
Closing as duplicate of https://github.com/allenai/allennlp/issues/4360.

**Closed by dirkgr** 2020-10-09 23:09 UTC
Labels: bug
