### ISSUE TITLE
Allennp Use unspecified GPU

### ISSUE THREAD

**Issue by Charrnander** [allenai/allennlp#2006] opened 2018-11-02 08:48 UTC
**Describe the bug**
I run my code on a serve which has 4 GPUs.
I specify the model to run on  GPU: 1.(Trainer(..., cuda_device=1)
but the thread will also occupy some memory(hundreds of Mbs) of  GPU: 0 .
If the memory of  GPU: 0 was almost full , an out of memory will be occured.
![image](https://user-images.githubusercontent.com/36198692/47901493-11949180-debb-11e8-8eca-ce3a234bbbb6.png)

**Expected behavior**
The thread will only occupy the memory of GPU I specified.

**System:**
 - OS: Linux
 - Python version: 3.6.5
 - AllenNLP version: v0.6.1
 - PyTorch version: 0.4.1
 - IDE: Jupyter Notebook

**Comment by matt-gardner** [comment] 2018-11-02 08:57
Duplicate of #1002; please see the solution there.

**Closed by matt-gardner** 2018-11-02 08:57 UTC
