### ISSUE TITLE
Keyerror when tokenizing text

### ISSUE THREAD

**Issue by raviolli** [allenai/allennlp#4189] opened 2020-05-02 00:35 UTC
**Describe the bug**
When running the sentiment example I get a KeyError:

    pred = self.predictor.predict(sentence=t)
  File "/home/...anaconda2/envs/py3env/lib/python3.7/site-packages/allennlp/predictors/text_classifier.py", line 25, in predict
    return self.predict_json({"sentence": sentence})
  File "/home/.../anaconda2/envs/py3env/lib/python3.7/site-packages/allennlp/predictors/predictor.py", line 66, in predict_json
    return self.predict_instance(instance)
  File "/home/.../anaconda2/envs/py3env/lib/python3.7/site-packages/allennlp/predictors/predictor.py", line 189, in predict_instance
    outputs = self._model.forward_on_instance(instance)
  File "/home/.../anaconda2/envs/py3env/lib/python3.7/site-packages/allennlp/models/model.py", line 141, in forward_on_instance
    return self.forward_on_instances([instance])[0]
  File "/home/.../anaconda2/envs/py3env/lib/python3.7/site-packages/allennlp/models/model.py", line 167, in forward_on_instances
    outputs = self.make_output_human_readable(self(**model_input))
  File "/home/.../anaconda2/envs/py3env/lib/python3.7/site-packages/allennlp/models/basic_classifier.py", line 173, in make_output_human_readable
    for token_id in instance_tokens
  File "/home/.../anaconda2/envs/py3env/lib/python3.7/site-packages/allennlp/models/basic_classifier.py", line 173, in <listcomp>
    for token_id in instance_tokens
  File "/home/.../anaconda2/envs/py3env/lib/python3.7/site-packages/allennlp/data/vocabulary.py", line 665, in get_token_from_index
    return self._index_to_token[namespace][index]
KeyError: 4688

**To Reproduce**
Steps to reproduce the behavior
Setup conda environment for python 3.7.0
pip install allennlp==1.0.0rc3 allennlp-models==1.0.0rc3

from allennlp.predictors.predictor import Predictor
import allennlp_models.sentiment
predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/sst-roberta-large-2020.02.17.tar.gz")
predictor.predict(sentence="a very well-made, funny and entertaining picture.")

**Expected behavior**
Expect to get a KeyError: 

It works fine on 3.6.9

**System (please complete the following information):**
 - OS: Ubuntu

**Comment by matt-gardner** [comment] 2020-05-04 16:00
@raviolli, just to clarify, this is an error that only shows up in python 3.7, and not python 3.6?

**Comment by raviolli** [comment] 2020-05-04 18:01
This only shows up 3.7 it works fine in 3.6

**Comment by matt-gardner** [comment] 2020-05-04 19:03
I'm pretty sure this is a duplicate of https://github.com/allenai/allennlp/issues/4192.  Can you try the solution there (just using a more recent model)?  If that doesn't work, let us know, and I can re-open this issue.

**Closed by matt-gardner** 2020-05-04 19:03 UTC
