### ISSUE TITLE
Special token embeddings using PretrainedTransformer(Mismatched)Embedder

### ISSUE THREAD

**Issue by ZhaofengWu** [allenai/allennlp#3969] opened 2020-03-21 03:04 UTC
Currently `PretrainedTransformerEmbedder` always outputs special token embeddings and `PretrainedTransformerMismatchedEmbedder` always _doesn't_ output them. The former could cause bugs when we expect the embedder to output a sequence of the same length as the input, and the latter could cause bugs e.g. when it is used in conjunction with `ClsPooler` (actually this is what we're doing for SST, so there's a minor bug there and we might need to retrain the model). So we should add a flag to both of them to control this behavior.

The question is, which behavior do we want as the default? I have a slight preference on not outputting them so that they obey the input length == output length contract.

**Comment by matt-gardner** [comment] 2020-03-21 14:36
I think the current behavior is as intended, and there is nothing to fix.  Embedders always output the same number of tokens as the tokenizer provided.  If you didn't have special tokens output from your tokenizer, you should not have them output from your embedder.  If you want to explicitly use the `[CLS]` embedding (say, with a pooler), then you need to use a tokenizer and embedder that use the `[CLS]` embedding.  If you have pre-tokenized input, and you want to use a `[CLS]` embedding, you should do something like `tokenizer.tokenize(' '.join(tokens))`, and use matched tokenization and embedding.

**Comment by ZhaofengWu** [comment] 2020-03-23 18:10
Ok, let's say the current behavior is intended. The other way to ask this question is, do we want to add an option that easily support the removal of `[CLS]` in `PretrainedTransformerEmbedder` and its addition in `PretrainedTransformerMismatchedEmbedder`. By default this option behaves the same as right now, but it allows the user to not having to dig into the code to do things like `tokenizer.tokenize(' '.join(tokens))` (which I _think_ could produce different results from `tokenizer.intra_word_tokenize(tokens)`).

**Comment by matt-gardner** [comment] 2020-03-23 18:27
Those options would break the abstraction, where we assume that the output of an `embedder` is always the same length as the output of the `tokenizer`.  I'm not sure what the use case is where you would get benefit from this.  Do you have a concrete example?

**Comment by ZhaofengWu** [comment] 2020-03-23 19:14
Example where we want `[CLS]` for `PretrainedTransformerMismatchedEmbedder`:

SST is pre-tokenized (or at least that's how we're reading it), but we want `[CLS]`. If `PretrainedTransformerMismatchedEmbedder` doesn't give its embedding, the user has to modify the dataset reader to do what you suggested above. I'd say pretrained transformer for SST is a quite common use case since it's in GLUE. I made this mistake when training SST and NLI models thinking `PretrainedTransformerMismatchedEmbedder` returns the `[CLS]` embedding but I was actually using the first real token's embedding.

Plus, even if we do `tokenizer.tokenize(' '.join(tokens))`, it's hard to track the offsets (imagine if some token has leading/trailing whitespaces).

**Comment by matt-gardner** [comment] 2020-03-23 19:30
It sounds like you're taking a suboptimal data reading decision and trying to compensate for it by making our abstractions less clean.

Fundamentally, the mismatched embedder should be used when *what I want to model* is a sequence of words, without special tokens.  The regular embedder should be used when *what I want to model* is a sequence of wordpieces with special tokens.  For the SST case you're describing, you don't really care about words vs. wordpieces, but you want special tokens, so you really want the regular embedder.

Given that, the question is what's the right thing to do on the data side.  It seems like the right thing to do here is in the `DatasetReader` convert from your list of pretokenized words to a list of wordpieces and special tokens, then used matched indexing / embedding.  The only question is how to do that effectively in a general way, with our abstractions.  I can imagine adding a `retokenize` method to our tokenizers, which, given an input list of tokens, returns a modified list.  Perhaps this is common enough these days that's it's worth considering adding this.  I'm not sure.  @dirkgr, any thoughts?

**Comment by dirkgr** [comment] 2020-03-23 20:45
I think special tokens, should never be automatically added anywhere. When and where to put them is a decision for the reader.

I know that the huggingface tokenizers do this, and that there are slight differences for each of the transformers, which makes this a tempting target to abstract away. But I also think there are a ton of problems with it. Offsets don't match anymore, you can't concatenate strings properly, going from token ids back to strings doesn't work, and so on. It breaks many assumptions.

Same thing for token type IDs, for that matter.

This whole issue reminds me a little of SQL database abstractions. In principle, that should be abstracted away. In practice, everyone knows SQL anyways, and it becomes a question of tricking your abstraction into writing the SQL you have in mind. In this case, everyone knows which special tokens go where, and we're trying to finagle an abstraction to do exactly what we already know to do.

**Comment by matt-gardner** [comment] 2020-03-23 20:50
I'm not really sure what you're suggesting doing here.

**Comment by dirkgr** [comment] 2020-03-23 22:59
@ZhaofengWu and I talked on Slack. Let me try to summarize:

The way things need to be is this: Whether you use mismatched or matched indexer/embedder, you get one vector for each token that the reader puts into the input. If you want vectors for special tokens, you have to put special tokens into the input. I think that tracks what with @matt-gardner said above.

Some configurations will add their own special tokens in the indexer, but those have to make sure to strip them back out in the embedder. For example, the matched embedder/indexer adds a `[CLS]` to the beginning and a `[SEP]` to the end of each segment that it processes. This is fine, but the embedder needs to make sure the embeddings for those tokens don't end up in the output.

It may make sense to make this behavior configurable. If the reader already inserts its own `[CLS]`, we might not want the indexer to insert a second one. So then we could set `use_special_tokens=False` in the indexer configuration, and solve the problem that way. The important thing is that regardless of what you set `use_special_tokens` to, you get one vector per token.

**Comment by dirkgr** [comment] 2020-03-23 22:59
@ZhaofengWu, did I capture everything?

**Comment by matt-gardner** [comment] 2020-03-23 23:41
Ok, yes, I agree with what you said there.

**Comment by ZhaofengWu** [comment] 2020-03-23 23:41
I think you meant "the **mis**matched indexer/embedder" adds the special tokens?

**Comment by dirkgr** [comment] 2020-03-23 23:42
> I think you meant "the mismatched indexer/embedder" adds the special tokens?

The matched one does it too if you set `max_length`. The principle is the same for both.

**Comment by ZhaofengWu** [comment] 2020-03-23 23:44
To check my understanding, for pre-tokenized sequence classification class, @dirkgr is suggesting:

1. Reader somehow adds the special tokens. I think the reader will need an instance of a `PretranedTransformerTokenizer` to do this;
2. Use mismatched indexer/embedder. But because currently the mismatched indexer always adds a special token and because we don't want duplicated special tokens, we need to add a flag to control the addition of special tokens in the mismatched indexer

**Comment by matt-gardner** [comment] 2020-03-23 23:54
An alternative option that I think is also consistent with what @dirkgr was saying:

1. Reader adds special tokens by calling `tokens = tokenizer.retokenize(token_list)`, using a `PretrainedTransformerTokenizer` that's configured to add special tokens and split words into wordpieces.  Basically exactly what `intra_word_tokenize` does now, if I'm remembering that function right.  The user is explicitly adding the special tokens by calling `retokenize` with a particular tokenizer.
2. Use matched indexer / embedder.

**Comment by dirkgr** [comment] 2020-08-19 12:47
This discussion keeps coming up. I don't think we'll do anything for 1.x, and we are talking about a few variants for 2.x in another issue already. I'll close this one.

**Closed by dirkgr** 2020-08-19 12:47 UTC
