### ISSUE TITLE
'allennlp.modules.elmo' import changing default CUDA device

### ISSUE THREAD

**Issue by JoaoLages** [allenai/allennlp#2083] opened 2018-11-21 11:18 UTC
I have noticed that just by importing this module my GPU device is automatically switched to 0, although I have set CUDA_VISIBLE_DEVICES to the device that I wanted. I have also checked that this variable is still not equal to zero, but the memory being consumed is on GPU 0 instead, because of this import. 

How can we change this behavior? I have tried to search for the line of code that changes the cuda device but I have not been able, since the code is very deep.

**Comment by matt-gardner** [comment] 2018-11-21 17:45
This appears to be a duplicate of #2058.  As there is an easy work-around, fixing this is not high on our priority list.  If you'd like to see it fixed, helping us diagnose the issue would be much appreciated (that's what #2058 is tracking).

**Closed by matt-gardner** 2018-11-21 17:45 UTC

**Comment by senkey705** [comment] 2018-11-25 12:10
u can setting "export CUDA_VISIBLE_DEVICES=1" in a shell script env.sh then source env.sh before u running the model, i have solving your problem by this way.
