### ISSUE TITLE
Add support for loading and saving models that were created from code

### ISSUE THREAD

**Issue by jgc128** [allenai/allennlp#2311] opened 2019-01-08 20:48 UTC
**Describe the bug**
If a model has an `__init__(self, *args, **kwargs)` method that introduce some additional behavior (note the `*args` or `**kwargs` arguments), `Model.from_params` raises an error `ConfigurationError: 'key "kwargs" is required at location ""'`

**To Reproduce**
Run the code below:
```
from allennlp.common import Params
from allennlp.models import Model
from allennlp.data import Vocabulary

@Model.register('base_model')
class BaseModel(Model):
    def __init__(self, hidden_size: int, vocab: Vocabulary) -> None:
        super().__init__(vocab)

        self.hidden_size = hidden_size
        
@Model.register('second_model')
class SecondModel(BaseModel):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        
        self.new_layer = 128

second_model_params = Params({'type': 'second_model', 'hidden_size': 128})

second_model = Model.from_params(second_model_params, vocab=Vocabulary())
```

**Expected behavior**
An object of the class SecondModel is created

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: 3.6.7
 - AllenNLP version: 0.8.2-unreleased, installed from master
 - PyTorch version: 1.0.0

**Additional context**
In addition, it prevents model inheritance with additional parameters:
```def __init__(self, new_param, *args, **kwargs)```

This is similar to #1480 and removing the `__init__` method allows creating of the model, but in my case I need the `__init__` as it adds some additional functionality.

**Comment by matt-gardner** [comment] 2019-01-08 20:56
Yeah, this is unfortunately expected behavior when using `from_params`.  Maybe we could do some magic in checking for `*args` and `**kwargs` in the default `from_params`, and going to a super class, or something, but that's a bunch of work that's not high on our priority list.  Contributions welcome!

**Comment by matt-gardner** [comment] 2019-01-08 20:57
I should note that the workaround is just to duplicate all of the parameters in the subclass.  Unfortunately verbose, but it works.

**Comment by joelgrus** [comment] 2019-01-08 20:58
isn't another solution just to explicitly implement `from_params` in the subclass?

**Comment by matt-gardner** [comment] 2019-01-08 21:00
You mean something like this?

```python
def from_params(self, params):
    return super().from_params(params)
```

That returns an object of the superclass's type.  If you mean explicitly popping all of the parameters yourself in `from_params`, it's probably a lot easier to just duplicate the constructor parameters.

**Comment by joelgrus** [comment] 2019-01-08 21:15
I see. I'm pretty sure I would like to encourage people to be explicit about their parameters anyway.

**Comment by matt-gardner** [comment] 2019-01-08 21:55
Yeah, I agree that explicit is good.  On the other hand, if someone wants to subclass your new `SingleTaskTrainer` and tweak the constructor a bit, that's a whole lot of boilerplate they have to worry about, when standard python lets you just do `*args, **kwargs`.

**Comment by jgc128** [comment] 2019-01-09 15:02
Thank you - overriding `from_params` in the base class worked!
```
    @classmethod
    def from_params(cls: Type[T], params: Params, **extras):
        extras.update(params)
        return cls(**extras)
```

**Comment by matt-gardner** [comment] 2019-01-09 15:08
Glad it worked for you! I'm pretty sure that will not work in cases where you recursively construct objects in `from_params` - you're just passing a json dictionary to the constructor, which only works for primitive objects.

**Comment by jgc128** [comment] 2019-01-09 15:13
Yeah - in my case I create objects (like Embeddings and LSTMs) beforehand and pass them in the extras; params contains only numerical arguments.

**Comment by matt-gardner** [comment] 2019-01-09 15:22
Why set things up that way? If you are constructing some things yourself, why not just call the constructor directly? What does using our parameter stuff get you in your case?

**Comment by jgc128** [comment] 2019-01-09 18:06
Well, initially I just had creation of the model in the code as described in the tutorial here: https://allennlp.org/tutorials

After I trained the model, I wanted to save it and the most logical choice seemed to be the `archive_model` [function](https://allenai.github.io/allennlp-docs/api/allennlp.models.archival.html#allennlp.models.archival.archive_model). However, it turned out that it requires the `config.json` file, which is, as I understand, cannot be generated automatically if you create model from the code, as the tutorial does. 

Next, I tired to use the `config.json` file, but it quickly got really big and similar to caffe configuration files. There were many repetitions and dependencies. For example, the [config file form this tutorial](https://github.com/allenai/allennlp-as-a-library-example/blob/master/experiments/venue_classifier.json) is quite big, and embedding dim == lstm input size, and if you change lstm size, you'd have to manually change the input size of the classifier keeping in mind that lstm is bi-directional so you'd have to multiple the lstm size by 2.
This seemed not optimal, so I decided to keep only the key parameters in the `config.json` file, and create layers in the code using those parameters. With just one model it worked pretty good - I can just load the parameters and pass them my `create_model` function which would take care of re-using the same parameters in multiple places. 

However, I have several models - one base model and two slight modifications which add some layers in the middle of the base model. These models are implemented as subclasses and accept one or two additional parameters in the `__init__`, so they share most of the parameters. Because I register the derived models (`@Model.register("model_a")`), I can just add `"type":"model_a"` in the `config.json` file and use Model.from_params to automatically create the model of the corresponding class, which is really convenient, as I can create all the underlying layers in the code and just pass them in the `extras`.

So, I guess the real issue here is that there's no way to save and later re-use model if you create it from code (see also #2222). I actually spend a lot of time trying to figure out what is the best way to save the model and its arguments, and this is what I come up with. As mentioned in #2222, a tutorial on how to save and load trained models would be greatly appreciated.

**Comment by matt-gardner** [comment] 2019-01-09 18:53
Ah, ok, yes, that's a really good point, and an omission that hadn't even occurred to me.  We should fix this and make a way to save and load models without config files.  This sounds very tricky, though, because when we load the model we don't know how it's configured without a config file, so the answer is probably just to save and load the state dictionary, assuming that you've constructed the model with the right configuration yourself...

For the verbosity of the config file itself, we actually use `jsonnet` to parse the configuration file, which allows setting and re-using variables.  That might solve most of your issues.

**Comment by jgc128** [comment] 2019-01-10 16:18
That's great! `jsonnet` can solve some problems, but the configuration file would still be pretty big and not easily maintainable. 


>so the answer is probably just to save and load the state dictionary, assuming that you've constructed the model with the right configuration yourself...

You'd have to save the configuration parameters somewhere by yourself. Right now I copy my config file to the serialization dir. It would be great to have a way of automatic creation of the config file for the model create from the code. I understand, although, that it's very tricky and not sure if it is possible ☹️

**Comment by schmmd** [comment] 2019-01-18 21:11
Closing since we're tracking this in #2379

**Closed by schmmd** 2019-01-18 21:11 UTC
