### ISSUE TITLE
Multiple GPU training

### ISSUE THREAD

**Issue by matt-peters** [allenai/allennlp#758] opened 2018-02-02 17:51 UTC
See #749 for a discussion of remaining issues to fully support multiple GPU training.

**Comment by matt-peters** [comment] 2018-02-02 22:29
Illustration of the necessity to use `getattr`:

```python
import torch

class MyModule(torch.nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.layers = []
        for k in range(1):
            self.layers.append(torch.nn.Linear(5, 5))
            self.add_module('layer_{}'.format(k), self.layers[-1])

        self.parameter = torch.nn.Parameter(torch.rand(5))

    def forward(self, x):
        return self.layers[0](x)


model = MyModule()
model.cuda(0)

# replicate to GPUs 0 and 1
replicas = torch.nn.parallel.replicate(model, [0, 1])

# replicas[0] is the model on GPU0
# replicas[1] is the model on GPU1
print("Model replica and location of parameter attribute")
for k in range(2):
    print(k, replicas[k].parameter.get_device())

# except!
print("Location of replicas[1].layers[0].weight ", replicas[1].layers[0].weight.get_device())
print("Location of replicas[1].layers[0].weight using getattr", getattr(replicas[1], 'layer_0').weight.get_device())
```

Running on a multiple GPU machine prints:

```
Model replica and location of parameter attribute
0 0
1 1
Location of replicas[1].layers[0].weight  0
Location of replicas[1].layers[0].weight using getattr 1
```

**Comment by schmmd** [comment] 2018-02-09 19:52
@matt-peters would it help if we supported this today, or is this something you see needing in the near future?

**Comment by matt-peters** [comment] 2018-02-09 20:00
We should prioritize it along with the rest of the multiple GPU work.

**Comment by PetrochukM** [comment] 2018-05-24 14:58
@matt-peters Did you file this bug with https://github.com/pytorch/pytorch/issues?

**Comment by matt-peters** [comment] 2018-05-24 15:49
No, I haven't opened an issue.

**Comment by matt-gardner** [comment] 2018-09-14 20:51
Assigning @joelgrus, because he's working on this.  Just so you know to close this issue when it's done.

**Comment by PetrochukM** [comment] 2018-09-14 22:39
Hi Friends!

Discovered a bug with ``tqdm`` and the distributed package:
```python
from torch import multiprocessing

# DEPENDANCY: This is required for ``DistributedDataParallel``
# https://pytorch.org/docs/stable/nn.html?highlight=distributeddataparallel#torch.nn.parallel.DistributedDataParallel
try:
    multiprocessing.set_start_method('spawn')
except RuntimeError:
    pass

# DEPENDANCY: This is required for ``tqdm``
# https://github.com/tqdm/tqdm/blob/96d8a3c3642474144f53f74331ef2172d1c39496/tqdm/_tqdm.py#L74
mp_lock = multiprocessing.RLock()

import torch
from torch.utils.data import DataLoader

if __name__ == '__main__':
    data_iterator = torch.utils.data.DataLoader([torch.tensor(i) for i in range(10)], num_workers=4)
    for batch in data_iterator:
        pass
```
```
/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
```

**Comment by schmmd** [comment] 2019-03-14 22:47
@joelgrus don't we have multi-GPU training now?  Did you work on this or was it @brendan-ai2?  Would one of you summarize where we are, and if appropriate close this ticket?

**Comment by brendan-ai2** [comment] 2019-03-14 23:48
Yes, we have multi-GPU training.

1. Pass in multiple CUDA device ids to use it.
2. We don't automatically run unit tests with multiple GPUs, so eventual regressions are likely.
3. So far we've called it experimental: https://github.com/allenai/allennlp/blob/e08ade81ff6684869883ce3da66941b9d3a37503/allennlp/training/trainer_base.py#L40
4. We should look more into using `torch.distributed` in the longer term. See https://pytorch.org/docs/stable/distributed.html.

**Closed** 2019-03-15 01:05 UTC
Labels: P3
