### ISSUE TITLE
Attribute error when training a model

### ISSUE THREAD

**Issue by dparolo** [allenai/allennlp#4193] opened 2020-05-04 00:53 UTC
Recently upgraded from 0.9.0 to 1.0.0rc3. When I try to train a model, I get the following error:

AttributeError                            Traceback (most recent call last)
<ipython-input-29-5b7c9aaa5c29> in <module>
     18 )
     19 
---> 20 metrics = trainer.train()

~/engvenv/lib64/python3.6/site-packages/allennlp/training/trainer.py in train(self)
    730         for epoch in range(epoch_counter, self._num_epochs):
    731             epoch_start_time = time.time()
--> 732             train_metrics = self._train_epoch(epoch)
    733 
    734             # get peak of memory usage

~/engvenv/lib64/python3.6/site-packages/allennlp/training/trainer.py in _train_epoch(self, epoch)
    498             batch_group_outputs = []
    499             for batch in batch_group:
--> 500                 batch_outputs = self.batch_outputs(batch, for_training=True)
    501                 batch_group_outputs.append(batch_outputs)
    502                 loss = batch_outputs["loss"]

~/engvenv/lib64/python3.6/site-packages/allennlp/training/trainer.py in batch_outputs(self, batch, for_training)
    404         """
    405         batch = nn_util.move_to_device(batch, self.cuda_device)
--> 406         output_dict = self._pytorch_model(**batch)
    407 
    408         if for_training:

~/engvenv/lib64/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~/text_classifier_w/src/elmo_utils.py in forward(self, tokens, label)
    291                 A scalar loss to be optimised.
    292         """
--> 293         embedded_text = self._text_field_embedder(tokens)
    294         mask = get_text_field_mask(tokens)
    295 

~/engvenv/lib64/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~/engvenv/lib64/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py in forward(self, text_field_input, num_wrapping_dims, **kwargs)
     54         self, text_field_input: TextFieldTensors, num_wrapping_dims: int = 0, **kwargs
     55     ) -> torch.Tensor:
---> 56         if self._token_embedders.keys() != text_field_input.keys():
     57             message = "Mismatched token keys: %s and %s" % (
     58                 str(self._token_embedders.keys()),

AttributeError: 'TextField' object has no attribute 'keys'

What can cause this issue?

**Comment by matt-gardner** [comment] 2020-05-04 16:17
It looks like there's an error in your `elmo_utils` file, which I can't diagnose without more detail.  You might look at our [release notes](https://github.com/allenai/allennlp/releases/tag/v1.0.0.rc1) to see if there are any breaking changes listed there that apply to your code.

**Comment by dparolo** [comment] 2020-05-04 16:26
The only substancial thing I needed to change is the dataset reader, because no default dataset reader suited my needs. I can post my code below, maybe there are some issues here.

@DatasetReader.register("analisi_contratti")
class CdcDatasetReader(DatasetReader):
   

    def __init__(
        self,
        token_indexers: Dict[str, TokenIndexer] = None,
        tokenizer: Tokenizer = None,
        segment_sentences: bool = False,
        max_sequence_length: int = None,
        skip_label_indexing: bool = False,
        **kwargs,
    ) -> None:
        super().__init__(**kwargs)
        self._tokenizer = tokenizer or SpacyTokenizer()
        self._segment_sentences = segment_sentences
        self._max_sequence_length = max_sequence_length
        self._skip_label_indexing = skip_label_indexing
        self._token_indexers = token_indexers or {"tokens": SingleIdTokenIndexer()}
        if self._segment_sentences:
            self._sentence_segmenter = SpacySentenceSplitter()

    @overrides
    def _read(self, file_path):
        df = pd.read_csv(file_path)
        for i, row in df.iterrows():
            #if not row:
            #    continue
            text = row["texts"]
            label = row[df.columns.difference(['texts'])].values
            if label is not None:
                if self._skip_label_indexing:
                    try:
                        label = int(label)
                    except ValueError:
                        raise ValueError(
                            "Labels must be integers if skip_label_indexing is True."
                        )
                #else:
                #    label = str(label)
            instance = self.text_to_instance(text=text, label=label)
            if instance is not None:
                yield instance

    def _truncate(self, tokens):
        
        if len(tokens) > self._max_sequence_length:
            tokens = tokens[: self._max_sequence_length]
        return tokens

    @overrides
    def text_to_instance(
        self, text: str, label: Union[str, int] = None
    ) -> Instance:  # type: ignore
        

        fields: Dict[str, Field] = {}
        if self._segment_sentences:
            sentences: List[Field] = []
            sentence_splits = self._sentence_segmenter.split_sentences(text)
            for sentence in sentence_splits:
                word_tokens = self._tokenizer.tokenize(sentence)
                if self._max_sequence_length is not None:
                    word_tokens = self._truncate(word_tokens)
                sentences.append(TextField(word_tokens, self._token_indexers))
            fields["tokens"] = ListField(sentences)
        else:
            tokens = self._tokenizer.tokenize(text)
            if self._max_sequence_length is not None:
                tokens = self._truncate(tokens)
            fields["tokens"] = TextField(tokens, self._token_indexers)
        if label is not None:
            label_field = ArrayField(array=label)
            fields["label"] = label_field
        return Instance(fields)

**Comment by dparolo** [comment] 2020-05-04 16:27
The only substancial thing I needed to change is the dataset reader, because no default dataset reader suited my needs. I can post my code below, maybe there are some issues here.

class CdcDatasetReader(DatasetReader):
def __init__(
    self,
    token_indexers: Dict[str, TokenIndexer] = None,
    tokenizer: Tokenizer = None,
    segment_sentences: bool = False,
    max_sequence_length: int = None,
    skip_label_indexing: bool = False,
    **kwargs,
) -> None:
    super().__init__(**kwargs)
    self._tokenizer = tokenizer or SpacyTokenizer()
    self._segment_sentences = segment_sentences
    self._max_sequence_length = max_sequence_length
    self._skip_label_indexing = skip_label_indexing
    self._token_indexers = token_indexers or {"tokens": SingleIdTokenIndexer()}
    if self._segment_sentences:
        self._sentence_segmenter = SpacySentenceSplitter()

@overrides
def _read(self, file_path):
    df = pd.read_csv(file_path)
    for i, row in df.iterrows():
        #if not row:
        #    continue
        text = row["texts"]
        label = row[df.columns.difference(['texts'])].values
        if label is not None:
            if self._skip_label_indexing:
                try:
                    label = int(label)
                except ValueError:
                    raise ValueError(
                        "Labels must be integers if skip_label_indexing is True."
                    )
            #else:
            #    label = str(label)
        instance = self.text_to_instance(text=text, label=label)
        if instance is not None:
            yield instance

def _truncate(self, tokens):
    
    if len(tokens) > self._max_sequence_length:
        tokens = tokens[: self._max_sequence_length]
    return tokens

@overrides
def text_to_instance(
    self, text: str, label: Union[str, int] = None
) -> Instance:  # type: ignore
    

    fields: Dict[str, Field] = {}
    if self._segment_sentences:
        sentences: List[Field] = []
        sentence_splits = self._sentence_segmenter.split_sentences(text)
        for sentence in sentence_splits:
            word_tokens = self._tokenizer.tokenize(sentence)
            if self._max_sequence_length is not None:
                word_tokens = self._truncate(word_tokens)
            sentences.append(TextField(word_tokens, self._token_indexers))
        fields["tokens"] = ListField(sentences)
    else:
        tokens = self._tokenizer.tokenize(text)
        if self._max_sequence_length is not None:
            tokens = self._truncate(tokens)
        fields["tokens"] = TextField(tokens, self._token_indexers)
    if label is not None:
        label_field = ArrayField(array=label)
        fields["label"] = label_field
    return Instance(fields)

**Comment by dparolo** [comment] 2020-05-04 16:30
The only substancial thing I needed to modify is the dataset reader, maybe I did something wrong here:

class CdcDatasetReader(DatasetReader):
   
    def __init__(
        self,
        token_indexers: Dict[str, TokenIndexer] = None,
        tokenizer: Tokenizer = None,
        segment_sentences: bool = False,
        max_sequence_length: int = None,
        skip_label_indexing: bool = False,
        **kwargs,
    ) -> None:
        super().__init__(**kwargs)
        self._tokenizer = tokenizer or SpacyTokenizer()
        self._segment_sentences = segment_sentences
        self._max_sequence_length = max_sequence_length
        self._skip_label_indexing = skip_label_indexing
        self._token_indexers = token_indexers or {"tokens": SingleIdTokenIndexer()}
        if self._segment_sentences:
            self._sentence_segmenter = SpacySentenceSplitter()

    @overrides
    def _read(self, file_path):
        df = pd.read_csv(file_path)
        for i, row in df.iterrows():
            #if not row:
            #    continue
            text = row["texts"]
            label = row[df.columns.difference(['texts'])].values
            if label is not None:
                if self._skip_label_indexing:
                    try:
                        label = int(label)
                    except ValueError:
                        raise ValueError(
                            "Labels must be integers if skip_label_indexing is True."
                        )
                #else:
                #    label = str(label)
            instance = self.text_to_instance(text=text, label=label)
            if instance is not None:
                yield instance

    def _truncate(self, tokens):
        """
        truncate a set of tokens using the provided sequence length
        """
        if len(tokens) > self._max_sequence_length:
            tokens = tokens[: self._max_sequence_length]
        return tokens

    @overrides
    def text_to_instance(
        self, text: str, label: Union[str, int] = None
    ) -> Instance:  # type: ignore
        """
        # Parameters
        text : `str`, required.
            The text to classify
        label : `str`, optional, (default = None).
            The label for this text.
        # Returns
        An `Instance` containing the following fields:
            tokens : `TextField`
                The tokens in the sentence or phrase.
            label : `LabelField`
                The label label of the sentence or phrase.
        """

        fields: Dict[str, Field] = {}
        if self._segment_sentences:
            sentences: List[Field] = []
            sentence_splits = self._sentence_segmenter.split_sentences(text)
            for sentence in sentence_splits:
                word_tokens = self._tokenizer.tokenize(sentence)
                if self._max_sequence_length is not None:
                    word_tokens = self._truncate(word_tokens)
                sentences.append(TextField(word_tokens, self._token_indexers))
            fields["tokens"] = ListField(sentences)
        else:
            tokens = self._tokenizer.tokenize(text)
            if self._max_sequence_length is not None:
                tokens = self._truncate(tokens)
            fields["tokens"] = TextField(tokens, self._token_indexers)
        if label is not None:
            label_field = ArrayField(array=label)
            fields["label"] = label_field
        return Instance(fields)

**Comment by matt-gardner** [comment] 2020-05-04 16:34
In your original stack trace, I see this:

```
~/text_classifier_w/src/elmo_utils.py in forward(self, tokens, label)
291 A scalar loss to be optimised.
292 """
--> 293 embedded_text = self._text_field_embedder(tokens)
294 mask = get_text_field_mask(tokens)
295
```

This line then ultimately results in this crash:

```
~/engvenv/lib64/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py in forward(self, text_field_input, num_wrapping_dims, **kwargs)
54 self, text_field_input: TextFieldTensors, num_wrapping_dims: int = 0, **kwargs
55 ) -> torch.Tensor:
---> 56 if self._token_embedders.keys() != text_field_input.keys():
57 message = "Mismatched token keys: %s and %s" % (
58 str(self._token_embedders.keys()),

AttributeError: 'TextField' object has no attribute 'keys'
```

Somehow, either `self._token_embedders` or `text_field_input` is a `TextField` object, which should not happen.  I don't have enough information to diagnose why one of those is a `TextField`.  I would recommend tracing through the code to figure out where that argument comes from and why it's not what it's supposed to be.

**Comment by matt-gardner** [comment] 2020-05-04 16:37
It's possible there's some interaction with the fact that `tokens` is sometimes a list and sometimes not (that would require special handling in your model), but it still shouldn't give you a bare `TextField` anywhere in your model.  That should have been converted to tensors.  Did you write your own data processing code or training loop?

**Comment by dparolo** [comment] 2020-05-04 16:51
My pipeline is the following:

> token_indexer = PretrainedTransformerIndexer(model_name = "Musixmatch/umberto-wikipedia-uncased-v1")

> tokenizer = PretrainedTransformerTokenizer(model_name = "Musixmatch/umberto-wikipedia-uncased-v1")

>reader = CdcDatasetReader(
    tokenizer=tokenizer,
    token_indexers={"tokens": token_indexer},
    max_seq_len = config.max_seq_len
)

cdc_train = reader.read(train_data)
cdc_valid = reader.read(valid_data)

> train_loader = DataLoader(cdc_train, batch_sampler = BucketBatchSampler(cdc_train, batch_size = config.batch_size))
valid_loader = DataLoader(cdc_valid, batch_sampler = BucketBatchSampler(cdc_valid, batch_size = config.batch_size))

> bert_embedder = PretrainedTransformerEmbedder(model_name = "Musixmatch/umberto-wikipedia-uncased-v1")
word_embeddings = BasicTextFieldEmbedder({"tokens": bert_embedder})

> encoder: Seq2VecEncoder = BertPooler(pretrained_model = "Musixmatch/umberto-wikipedia-uncased-v1")

> cl = MyBasicClassifier(vocab,word_embeddings,encoder, num_labels = 14)

> trainer = GradientDescentTrainer(
    model=cl,
    optimizer=optimizer,
    data_loader=cdc_train,
    validation_data_loader=cdc_valid,
    checkpointer = checkpoint,
    #validation_metric="+accuracy",
    cuda_device=0 if USE_GPU else -1,
    num_epochs=10,
    patience = 4
)

metrics = trainer.train()


The error is only at the last step of the process

**Comment by dparolo** [comment] 2020-05-04 16:52
By the way I get the same error when I try using the elmo encoder, so it's not a problem with bert or elmo

**Comment by matt-gardner** [comment] 2020-05-04 17:00
You need to use our `DataLoader`, not the pytorch one: https://github.com/allenai/allennlp/blob/967660a477c04d83be748f5bb8b0b9d862b85fc1/allennlp/data/dataloader.py#L22

We really should rename this to `AllenNlpDataLoader`, so that it's more obvious that it should be used with our code.  If you're using a pytorch `DataLoader`, you *must* use our collate function: https://github.com/allenai/allennlp/blob/967660a477c04d83be748f5bb8b0b9d862b85fc1/allennlp/data/dataloader.py#L17

Closing this, as I'm quite sure that this is the cause of your problem.  If I'm wrong, feel free to keep commenting, and I can re-open the issue.

**Closed by matt-gardner** 2020-05-04 17:00 UTC

**Comment by dparolo** [comment] 2020-05-04 17:07
No, I'm using the allennlp DataLoader. I import it like this:

from allennlp.data.dataloader import DataLoader

**Comment by matt-gardner** [comment] 2020-05-04 17:09
If you're getting a `TextField` object in your model, then it sure seems to be the case that our collate function is not getting called.  I can't think of any other explanation for that.  At this point I'm going to need you to walk through the code and see why you're getting a `TextField` there.  There isn't a whole lot else I can do without more information.

**Comment by dparolo** [comment] 2020-05-04 21:06
Partially solved it. Now I don't have this problem anymore, but there is a new one:

---------------------------------------------------------------------------
ConfigurationError                        Traceback (most recent call last)
<ipython-input-20-61d1bc186770> in <module>
     18 )
     19 
---> 20 metrics = trainer.train()

~/engvenv/lib64/python3.6/site-packages/allennlp/training/trainer.py in train(self)
    730         for epoch in range(epoch_counter, self._num_epochs):
    731             epoch_start_time = time.time()
--> 732             train_metrics = self._train_epoch(epoch)
    733 
    734             # get peak of memory usage

~/engvenv/lib64/python3.6/site-packages/allennlp/training/trainer.py in _train_epoch(self, epoch)
    470 
    471         done_early = False
--> 472         for batch_group in batch_group_generator_tqdm:
    473             if self._distributed:
    474                 # Check whether the other workers have stopped already (due to differing amounts of

~/engvenv/lib64/python3.6/site-packages/tqdm/notebook.py in __iter__(self, *args, **kwargs)
    216     def __iter__(self, *args, **kwargs):
    217         try:
--> 218             for obj in super(tqdm_notebook, self).__iter__(*args, **kwargs):
    219                 # return super(tqdm...) will not catch exception
    220                 yield obj

~/engvenv/lib64/python3.6/site-packages/tqdm/std.py in __iter__(self)
   1125 
   1126         try:
-> 1127             for obj in iterable:
   1128                 yield obj
   1129                 # Update and possibly print the progressbar.

~/engvenv/lib64/python3.6/site-packages/allennlp/common/util.py in lazy_groups_of(iterable, group_size)
    133     iterator = iter(iterable)
    134     while True:
--> 135         s = list(islice(iterator, group_size))
    136         if len(s) > 0:
    137             yield s

~/engvenv/lib64/python3.6/site-packages/allennlp/data/dataloader.py in __iter__(self)
     87     def __iter__(self):
     88         if self._batches_per_epoch is None:
---> 89             yield from super().__iter__()
     90         else:
     91             for i in range(self._batches_per_epoch):

~/engvenv/lib64/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    343 
    344     def __next__(self):
--> 345         data = self._next_data()
    346         self._num_yielded += 1
    347         if self._dataset_kind == _DatasetKind.Iterable and \

~/engvenv/lib64/python3.6/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    383     def _next_data(self):
    384         index = self._next_index()  # may raise StopIteration
--> 385         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    386         if self._pin_memory:
    387             data = _utils.pin_memory.pin_memory(data)

~/engvenv/lib64/python3.6/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     45         else:
     46             data = self.dataset[possibly_batched_index]
---> 47         return self.collate_fn(data)

~/engvenv/lib64/python3.6/site-packages/allennlp/data/dataloader.py in allennlp_collate(instances)
     17 def allennlp_collate(instances: List[Instance]) -> TensorDict:
     18     batch = Batch(instances)
---> 19     return batch.as_tensor_dict(batch.get_padding_lengths())
     20 
     21 

~/engvenv/lib64/python3.6/site-packages/allennlp/data/batch.py in get_padding_lengths(self)
     57         padding_lengths: Dict[str, Dict[str, int]] = defaultdict(dict)
     58         all_instance_lengths: List[Dict[str, Dict[str, int]]] = [
---> 59             instance.get_padding_lengths() for instance in self.instances
     60         ]
     61         all_field_lengths: Dict[str, List[Dict[str, int]]] = defaultdict(list)

~/engvenv/lib64/python3.6/site-packages/allennlp/data/batch.py in <listcomp>(.0)
     57         padding_lengths: Dict[str, Dict[str, int]] = defaultdict(dict)
     58         all_instance_lengths: List[Dict[str, Dict[str, int]]] = [
---> 59             instance.get_padding_lengths() for instance in self.instances
     60         ]
     61         all_field_lengths: Dict[str, List[Dict[str, int]]] = defaultdict(list)

~/engvenv/lib64/python3.6/site-packages/allennlp/data/instance.py in get_padding_lengths(self)
     80         lengths = {}
     81         for field_name, field in self.fields.items():
---> 82             lengths[field_name] = field.get_padding_lengths()
     83         return lengths
     84 

~/engvenv/lib64/python3.6/site-packages/allennlp/data/fields/text_field.py in get_padding_lengths(self)
     74         if self._indexed_tokens is None:
     75             raise ConfigurationError(
---> 76                 "You must call .index(vocabulary) on a field before determining padding lengths."
     77             )
     78 

ConfigurationError: You must call .index(vocabulary) on a field before determining padding lengths.

Do I need to open a new issue?

**Comment by matt-gardner** [comment] 2020-05-04 21:13
You need the equivalent of these lines somewhere in your training script: https://github.com/allenai/allennlp/blob/967660a477c04d83be748f5bb8b0b9d862b85fc1/allennlp/commands/train.py#L664-L665

**Comment by dparolo** [comment] 2020-05-04 21:21
Worked! Thank you!!!
