### ISSUE TITLE
Running predictions requires --include-package allennlp_models

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#4104] opened 2020-04-20 16:23 UTC
However, according to @matt-gardner:

> This isn't supposed to be necessary; just doing the pip install is supposed to add the models repo as a plugin.

**Comment by schmmd** [comment] 2020-04-24 18:33
@dirkgr I don't believe this is resolved.

```
$ pip freeze | grep allennlp
allennlp==1.0.0rc2
allennlp-models==1.0.0rc2

$ echo '{"sentence": "Did Uriah honestly think he could beat The Legend of Zelda in under three hours?"}' | \
allennlp predict https://storage.googleapis.com/allennlp-public-models/ner-model-2020.02.10.tar.gz -

2020-04-24 11:29:17,684 - INFO - transformers.file_utils - PyTorch version 1.4.0 available.
2020-04-24 11:29:19,145 - INFO - allennlp.models.archival - loading archive file https://storage.googleapis.com/allennlp-public-models/ner-model-2020.02.10.tar.gz from cache at /Users/michael/.allennlp/cache/298798bbebac87143a3b421ff478cca929a5e43926e19f879c053473827e55c6.dad72088b0fc59006a39cb50270a64476d176006a3054327423c35096d8c4265
2020-04-24 11:29:19,146 - INFO - allennlp.models.archival - extracting archive file /Users/michael/.allennlp/cache/298798bbebac87143a3b421ff478cca929a5e43926e19f879c053473827e55c6.dad72088b0fc59006a39cb50270a64476d176006a3054327423c35096d8c4265 to temp dir /var/folders/v5/tlk1sh3d0l94fcmz10vtzmyh0000gn/T/tmphzrrp_cy
Traceback (most recent call last):
  File "/Users/michael/miniconda3/envs/allennlp-rc2/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/Users/michael/miniconda3/envs/allennlp-rc2/lib/python3.7/site-packages/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/Users/michael/miniconda3/envs/allennlp-rc2/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 93, in main
    args.func(args)
  File "/Users/michael/miniconda3/envs/allennlp-rc2/lib/python3.7/site-packages/allennlp/commands/predict.py", line 240, in _predict
    predictor = _get_predictor(args)
  File "/Users/michael/miniconda3/envs/allennlp-rc2/lib/python3.7/site-packages/allennlp/commands/predict.py", line 141, in _get_predictor
    overrides=args.overrides,
  File "/Users/michael/miniconda3/envs/allennlp-rc2/lib/python3.7/site-packages/allennlp/models/archival.py", line 197, in load_archive
    opt_level=opt_level,
  File "/Users/michael/miniconda3/envs/allennlp-rc2/lib/python3.7/site-packages/allennlp/models/model.py", line 386, in load
    model_class: Type[Model] = cls.by_name(model_type)  # type: ignore
  File "/Users/michael/miniconda3/envs/allennlp-rc2/lib/python3.7/site-packages/allennlp/common/registrable.py", line 137, in by_name
    subclass, constructor = cls.resolve_class_name(name)
  File "/Users/michael/miniconda3/envs/allennlp-rc2/lib/python3.7/site-packages/allennlp/common/registrable.py", line 185, in resolve_class_name
    f"{name} is not a registered name for {cls.__name__}. "
allennlp.common.checks.ConfigurationError: crf_tagger is not a registered name for Model. You probably need to use the --include-package flag to load your custom code. Alternatively, you can specify your choices using fully-qualified paths, e.g. {"model": "my_module.models.MyModel"} in which case they will be automatically imported correctly.
2020-04-24 11:29:26,608 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /var/folders/v5/tlk1sh3d0l94fcmz10vtzmyh0000gn/T/tmphzrrp_cy

**Comment by dirkgr** [comment] 2020-04-24 21:56
Weird. It works on my box.

**Comment by schmmd** [comment] 2020-04-24 22:49
I also tried this on allennlp-server3 in a conda environment.

**Comment by fursovia** [comment] 2020-04-25 15:45
In my experience, `1.0.0rc2` version of `allennlp_models` installed via pip does not contain any modules. I solved the issue by installing it from the source.

Probably something happened when packaging/publishing for `PyPI`.

**Comment by epwalsh** [comment] 2020-04-25 17:48
@fursovia could you elaborate what you mean by “doesn’t contain any modules”?

**Comment by fursovia** [comment] 2020-04-25 19:17
@epwalsh Yes, sorry for the incomprehensible explanation

What I did
```bash
pip install allennlp_models==1.0.0rc2
ls /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/allennlp_models
>>> __init__.py	__pycache__	version.py
```

So, there are no `allennlp_models` modules in the directory where the package was installed.

Then I installed the package from source using [poetry](https://python-poetry.org/) 

```
[tool.poetry.dependencies]
python = "^3.6.1"
allennlp = "=1.0.0.rc2"
allennlp-models = { git = "https://github.com/allenai/allennlp-models.git", branch = "master" }
```
Now it works just fine.

**Comment by epwalsh** [comment] 2020-04-25 21:55
@fursovia got it, wow that's really weird. Looking at the logs from GitHub Actions I can confirm that the package wasn't built properly (https://github.com/allenai/allennlp-models/runs/613717551?check_suite_focus=true). Looks like the the plugins module wasn't added either, so that would explain the original issue.

Interestingly when I build the package the same way on my Mac everything looks fine. Looks like it has to do with the `find_packages` function in the `setup.py` working differently in the CI environment.

I think this should fix it though: https://github.com/allenai/allennlp-models/pull/29. I'll confirm on Monday.

**Comment by schmmd** [comment] 2020-04-27 15:09
Could this be related to https://github.com/allenai/allennlp/issues/4104?

**Comment by epwalsh** [comment] 2020-04-28 16:04
I can confirm this is fixed with rc3.

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/8812459/80510123-25457a80-892f-11ea-99b8-2ae59cbcf58b.png">

**Comment by epwalsh** [comment] 2020-04-29 22:24
Closing this per https://github.com/allenai/allennlp/issues/4104#issuecomment-620700104

**Closed by epwalsh** 2020-04-29 22:24 UTC

**Comment by mattgathu** [comment] 2020-06-01 06:46
I'm having this issue with `1.0.0rc5`

```bash
$ pip freeze | grep allennlp                                                                                                  
allennlp==1.0.0rc5
allennlp-models==1.0.0rc5

$ python
Python 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from allennlp_models import pretrained
>>> predictor = pretrained.named_entity_recognition_with_elmo_peters_2018()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ghost/.virtualenvs/melange/lib/python3.8/site-packages/allennlp_models/pretrained.py", line 92, in named_entity_recognition_with_elmo_peters_2018
    predictor = _load_predictor(
  File "/Users/ghost/.virtualenvs/melange/lib/python3.8/site-packages/allennlp_models/pretrained.py", line 21, in _load_predictor
    archive = load_archive(archive_file)
  File "/Users/ghost/.virtualenvs/melange/lib/python3.8/site-packages/allennlp/models/archival.py", line 192, in load_archive
    model = Model.load(
  File "/Users/ghost/.virtualenvs/melange/lib/python3.8/site-packages/allennlp/models/model.py", line 391, in load
    model_class: Type[Model] = cls.by_name(model_type)  # type: ignore
  File "/Users/ghost/.virtualenvs/melange/lib/python3.8/site-packages/allennlp/common/registrable.py", line 137, in by_name
    subclass, constructor = cls.resolve_class_name(name)
  File "/Users/ghost/.virtualenvs/melange/lib/python3.8/site-packages/allennlp/common/registrable.py", line 184, in resolve_class_name
    raise ConfigurationError(
allennlp.common.checks.ConfigurationError: crf_tagger is not a registered name for Model. You probably need to use the --include-package flag to load your custom code. Alternatively, you can specify your choices using fully-qualified paths, e.g. {"model": "my_module.models.MyModel"} in which case they will be automatically imported correctly.
>>> exit()
```

**Comment by epwalsh** [comment] 2020-06-01 15:28
@mattgathu thanks for catching this. This PR should fix it: https://github.com/allenai/allennlp-models/pull/67
