### ISSUE TITLE
allennlp.common.checks.ConfigurationError: "constituency_parser not in acceptable choices for model.type: ['bidaf', 'decomposable_attentio n', 'srl', 'simple_tagger']

### ISSUE THREAD

**Issue by djokester** [allenai/allennlp#1174] opened 2018-05-03 10:45 UTC
Hey! I tried running the constituency parser as shown [here](http://allennlp.org/models)
I got the following error. 
> 2018-05-03 10:41:13,611 - INFO - allennlp.models.archival - extracting archive file /root/.allennlp/datasets/aHR0cHM6Ly9zMy11cy13ZXN0LTIuY
> W1hem9uYXdzLmNvbS9hbGxlbm5scC9tb2RlbHMvZWxtby1jb25zdGl0dWVuY3ktcGFyc2VyLTIwMTguMDMuMTQudGFyLmd6."ce277c3d6dfa03cf002bb8c0d4d27774-85" to t
> emp dir /tmp/tmp5xhsyi6w
> 2018-05-03 10:41:21,917 - PARAM - allennlp.common.params - model.type = constituency_parser
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.5/site-packages/allennlp/run.py", line 13, in <module>
>     main(prog="python -m allennlp.run")
>   File "/usr/local/lib/python3.5/site-packages/allennlp/commands/__init__.py", line 27, in main
>     args.func(args)
>   File "/usr/local/lib/python3.5/site-packages/allennlp/commands/predict.py", line 64, in predict
>     predictor = get_predictor(args)
>   File "/usr/local/lib/python3.5/site-packages/allennlp/commands/predict.py", line 48, in get_predictor
>     archive = load_archive(args.archive_file)
>   File "/usr/local/lib/python3.5/site-packages/allennlp/models/archival.py", line 97, in load_archive
>     cuda_device=cuda_device)
>   File "/usr/local/lib/python3.5/site-packages/allennlp/models/model.py", line 154, in load
>     model = Model.from_params(vocab, model_params)
>   File "/usr/local/lib/python3.5/site-packages/allennlp/models/model.py", line 105, in from_params
>     choice = params.pop_choice("type", cls.list_available())
>   File "/usr/local/lib/python3.5/site-packages/allennlp/common/params.py", line 131, in pop_choice
>     raise ConfigurationError(message)
> allennlp.common.checks.ConfigurationError: "constituency_parser not in acceptable choices for model.type: ['bidaf', 'decomposable_attentio
> n', 'srl', 'simple_tagger']"

**Comment by joelgrus** [comment] 2018-05-03 13:36
I suspect the issue is that you have a very old version of `allennlp`. Can you install the latest?

also your stack trace suggests you are using python 3.5, allennlp requires 3.6.

**Comment by schmmd** [comment] 2018-05-17 18:37
Please re-open if you have further questions!

**Comment by shreyadaing** [comment] 2018-12-12 09:16
Trying to use fine grained ner model. I get following error:

Traceback (most recent call last):
  File "app.py", line 4, in <module>
    archive = load_archive(os.path.abspath('./fine-grained-ner-model-elmo-2018.08.31.tar.gz'))
  File "/home/ubuntu/anaconda3/envs/ner/lib/python3.6/site-packages/allennlp/models/archival.py", line 154, in load_archive
    cuda_device=cuda_device)
  File "/home/ubuntu/anaconda3/envs/ner/lib/python3.6/site-packages/allennlp/models/model.py", line 296, in load
    return cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)
  File "/home/ubuntu/anaconda3/envs/ner/lib/python3.6/site-packages/allennlp/models/model.py", line 243, in _load
    model = Model.from_params(vocab, model_params)
  File "/home/ubuntu/anaconda3/envs/ner/lib/python3.6/site-packages/allennlp/models/model.py", line 217, in from_params
    model = cls.by_name(choice).from_params(vocab, params)
  File "/home/ubuntu/anaconda3/envs/ner/lib/python3.6/site-packages/allennlp/models/crf_tagger.py", line 186, in from_params
    initializer = InitializerApplicator.from_params(params.pop('initializer', []))
  File "/home/ubuntu/anaconda3/envs/ner/lib/python3.6/site-packages/allennlp/nn/initializers.py", line 261, in from_params
    initializers = [(name, Initializer.from_params(init_params)) for name, init_params in params]
  File "/home/ubuntu/anaconda3/envs/ner/lib/python3.6/site-packages/allennlp/nn/initializers.py", line 261, in <listcomp>
    initializers = [(name, Initializer.from_params(init_params)) for name, init_params in params]
  File "/home/ubuntu/anaconda3/envs/ner/lib/python3.6/site-packages/allennlp/nn/initializers.py", line 61, in from_params
    choice = params.pop_choice("type", cls.list_available())
  File "/home/ubuntu/anaconda3/envs/ner/lib/python3.6/site-packages/allennlp/common/params.py", line 183, in pop_choice
    raise ConfigurationError(message)
allennlp.common.checks.ConfigurationError: "zero not in acceptable choices for model.initializer.list.list.type: ['normal', 'uniform', 'orthogonal', 'constant', 'dirac', 'xavier_normal', 'xavier_uniform', 'kaiming_normal', 'kaiming_uniform', 'sparse', 'eye', 'block_orthogonal', 'uniform_unit_scaling']"

**Comment by joelgrus** [comment] 2018-12-12 16:07
what version of allennlp are you using? it looks like the problem is that you're using an old version.

**Comment by shreyadaing** [comment] 2018-12-12 16:08
I am using allennlp 0.5.1

**Comment by schmmd** [comment] 2018-12-12 16:09
@shreyadaing you need to upgrade.  I'm not able to reproduce using:

```
allennlp predict https://s3-us-west-2.amazonaws.com/allennlp/models/fine-grained-ner-model elmo-2018.08.31.tar.gz ner-examples.jsonl
```

**Comment by shreyadaing** [comment] 2018-12-12 16:10
What version should i use?

**Comment by schmmd** [comment] 2019-03-14 22:51
I would use the latest version of AllenNLP (see https://github.com/allenai/allennlp/releases).

I'm closing this issue, since it's about 0.5.1.

**Closed by schmmd** 2019-03-14 22:51 UTC
