### ISSUE TITLE
test-install freeze

### ISSUE THREAD

**Issue by chsuong** [allenai/allennlp#3367] opened 2019-10-16 17:03 UTC
**System:**
 - OS: OSX (High Sierra)
 - Python version: 3.7
 - AllenNLP version: 0.9.0

**Question**
The terminal freezes for hours after I run the command "allennlp test-install" after installing allenlp via pip in a conda environment as instructed [here](https://github.com/allenai/allennlp). Why is this happening? Is there another way to run unit tests or check whether it was installed correctly?: 

```
(allennlp) MacBook-Pro:code_data$ allennlp test-install
2019-10-16 10:37:03,783 - INFO - pytorch_pretrained_bert.modeling - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2019-10-16 10:37:05,651 - INFO - pytorch_transformers.modeling_bert - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2019-10-16 10:37:05,665 - INFO - pytorch_transformers.modeling_xlnet - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2019-10-16 10:37:06,233 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-10-16 10:37:06,234 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-10-16 10:37:06,236 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-10-16 10:37:06,237 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-10-16 10:37:06,379 - INFO - allennlp.commands.test_install - Changing directory to /anaconda3/envs/allennlp/lib/python3.7/site-packages
2019-10-16 10:37:06,380 - INFO - allennlp.commands.test_install - Running tests at /anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp
============================= test session starts ==============================
platform darwin -- Python 3.7.4, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: /anaconda3/envs/allennlp/lib/python3.7/site-packages
plugins: flaky-3.6.1
collected 1482 items / 11 deselected / 1471 selected                           

allennlp/tests/commands/configure_test.py .                              [  0%]
allennlp/tests/commands/docstring_help_test.py s                         [  0%]
allennlp/tests/commands/dry_run_test.py ......                           [  0%]
allennlp/tests/commands/elmo_test.py ...........                         [  1%]
allennlp/tests/commands/evaluate_test.py .....                           [  1%]
allennlp/tests/commands/find_learning_rate_test.py ..s...                [  2%]
allennlp/tests/commands/fine_tune_test.py ........                       [  2%]
allennlp/tests/commands/main_test.py ...                                 [  2%]
allennlp/tests/commands/make_vocab_test.py .......                       [  3%]
allennlp/tests/commands/no_op_train_test.py .                            [  3%]
allennlp/tests/commands/predict_test.py .........                        [  3%]
allennlp/tests/commands/print_results_test.py ..                         [  4%]
allennlp/tests/commands/test_install_test.py .                           [  4%]
allennlp/tests/commands/train_test.py ........                           [  4%]
allennlp/tests/common/configuration_test.py ......                       [  5%]
allennlp/tests/common/file_utils_test.py ......                          [  5%]
allennlp/tests/common/from_params_test.py ...............                [  6%]
allennlp/tests/common/params_test.py .........x.........                 [  7%]
allennlp/tests/common/registrable_test.py ..............                 [  8%]
allennlp/tests/common/test_util.py .......                               [  9%]
allennlp/tests/data/dataset_test.py ...                                  [  9%]
allennlp/tests/data/instance_test.py .                                   [  9%]
allennlp/tests/data/vocabulary_test.py ..........................        [ 11%]
allennlp/tests/data/dataset_readers/babi_reader_test.py .....            [ 11%]
allennlp/tests/data/dataset_readers/ccgbank_test.py ..                   [ 11%]
allennlp/tests/data/dataset_readers/conll2000_dataset_reader_test.py ... [ 11%]
.                                                                        [ 12%]
allennlp/tests/data/dataset_readers/conll2003_dataset_reader_test.py ... [ 12%]
.                                                                        [ 12%]
allennlp/tests/data/dataset_readers/copynet_test.py .....                [ 12%]
allennlp/tests/data/dataset_readers/dataset_reader_test.py ....          [ 12%]
allennlp/tests/data/dataset_readers/event2mind_test.py ....              [ 13%]
allennlp/tests/data/dataset_readers/interleaving_dataset_reader_test.py . [ 13%]
.                                                                        [ 13%]
allennlp/tests/data/dataset_readers/language_modeling_dataset_test.py .. [ 13%]
                                                                         [ 13%]
allennlp/tests/data/dataset_readers/lazy_dataset_reader_test.py ..       [ 13%]
allennlp/tests/data/dataset_readers/masked_language_modeling_test.py ..  [ 13%]
allennlp/tests/data/dataset_readers/multiprocess_dataset_reader_test.py . [ 13%]
.....                                                                    [ 14%]
allennlp/tests/data/dataset_readers/next_token_lm_test.py ..             [ 14%]
allennlp/tests/data/dataset_readers/ontonotes_ner_test.py ...            [ 14%]
allennlp/tests/data/dataset_readers/penn_tree_bank_reader_test.py ....   [ 14%]
allennlp/tests/data/dataset_readers/quora_paraphrase_test.py ..          [ 14%]
allennlp/tests/data/dataset_readers/seq2seq_test.py .........            [ 15%]
allennlp/tests/data/dataset_readers/sequence_tagging_test.py ...         [ 15%]
allennlp/tests/data/dataset_readers/simple_language_modeling_test.py ... [ 15%]
.                                                                        [ 15%]
allennlp/tests/data/dataset_readers/snli_reader_test.py ..               [ 16%]
allennlp/tests/data/dataset_readers/srl_dataset_reader_test.py ......    [ 16%]
allennlp/tests/data/dataset_readers/stanford_sentiment_tree_bank_test.py . [ 16%]
.....                                                                    [ 16%]
allennlp/tests/data/dataset_readers/text_classification_json_test.py ... [ 17%]
...ss                                                                    [ 17%]
allennlp/tests/data/dataset_readers/universal_dependencies_dataset_reader_test.py . [ 17%]
.                                                                        [ 17%]
allennlp/tests/data/dataset_readers/universal_dependencies_multilingual_dataset_reader_test.py . [ 17%]
.                                                                        [ 17%]
allennlp/tests/data/dataset_readers/coreference/coref_reader_test.py ..  [ 17%]
allennlp/tests/data/dataset_readers/coreference/winobias_reader_test.py . [ 17%]
.                                                                        [ 18%]
allennlp/tests/data/dataset_readers/dataset_utils/ontonotes_test.py ...  [ 18%]
allennlp/tests/data/dataset_readers/dataset_utils/span_utils_test.py ... [ 18%]
.........                                                                [ 19%]
allennlp/tests/data/dataset_readers/dataset_utils/text2sql_utils_test.py . [ 19%]
......                                                                   [ 19%]
allennlp/tests/data/dataset_readers/reading_comprehension/drop_test.py . [ 19%]
....                                                                     [ 19%]
allennlp/tests/data/dataset_readers/reading_comprehension/qangaroo_test.py . [ 19%]
..                                                                       [ 20%]
allennlp/tests/data/dataset_readers/reading_comprehension/quac_test.py . [ 20%]
.                                                                        [ 20%]
allennlp/tests/data/dataset_readers/reading_comprehension/squad_test.py . [ 20%]
...                                                                      [ 20%]
allennlp/tests/data/dataset_readers/reading_comprehension/triviaqa_test.py . [ 20%]
.                                                                        [ 20%]
allennlp/tests/data/dataset_readers/reading_comprehension/util_test.py . [ 20%]
.                                                                        [ 20%]
allennlp/tests/data/dataset_readers/semantic_parsing/atis_test.py ..     [ 20%]
allennlp/tests/data/dataset_readers/semantic_parsing/grammar_based_text2sql_test.py s [ 20%]
                                                                         [ 20%]
allennlp/tests/data/dataset_readers/semantic_parsing/nlvr_test.py ....   [ 21%]
allennlp/tests/data/dataset_readers/semantic_parsing/template_text2sql_test.py . [ 21%]
                                                                         [ 21%]
allennlp/tests/data/dataset_readers/semantic_parsing/wikitables_test.py . [ 21%]
.                                                                        [ 21%]
allennlp/tests/data/fields/adjacency_field_test.py ......                [ 21%]
allennlp/tests/data/fields/array_field_test.py ........                  [ 22%]
allennlp/tests/data/fields/index_field_test.py .....                     [ 22%]
allennlp/tests/data/fields/knowledge_graph_field_test.py .........       [ 23%]
allennlp/tests/data/fields/label_field_test.py .......                   [ 23%]
allennlp/tests/data/fields/list_field_test.py ..............             [ 24%]
allennlp/tests/data/fields/metadata_field_test.py ..                     [ 24%]
allennlp/tests/data/fields/multilabel_field_test.py ..........           [ 25%]
allennlp/tests/data/fields/production_rule_field_test.py .......         [ 26%]
allennlp/tests/data/fields/sequence_label_field_test.py ........         [ 26%]
allennlp/tests/data/fields/span_field_test.py .......                    [ 27%]
allennlp/tests/data/fields/text_field_test.py .............              [ 27%]
allennlp/tests/data/iterators/basic_iterator_test.py ...............     [ 28%]
allennlp/tests/data/iterators/bucket_iterator_test.py .......            [ 29%]
allennlp/tests/data/iterators/homogeneous_iterator_test.py ..            [ 29%]
allennlp/tests/data/iterators/multiprocess_iterator_test.py`
```

**Comment by schmmd** [comment] 2019-10-17 21:50
I'm not sure--maybe you're running out of a system resource?  I will try this locally, but I don't expect I'll be able to reproduce the same problem as we run this frequently before releases.

**Comment by schmmd** [comment] 2019-10-17 22:34
I was able to reproduce this freeze.  It might be because we changed our instructions from python 3.6 to 3.7.

**Comment by schmmd** [comment] 2019-10-17 22:46
This freezes in a 3.6 conda environment too.

**Comment by schmmd** [comment] 2019-10-17 22:50
This exact test runs for all of our Master Commits, including our last release (http://build.allennlp.org/viewLog.html?buildId=20145&buildTypeId=AllenNLP_AllenNLPCommits) so it's likely something system dependent on Mac OS.

**Comment by schmmd** [comment] 2019-10-18 15:40
I think this is the root problem.  PyTorch is looking for a fix: https://github.com/pytorch/examples/issues/370

**Comment by brendan-ai2** [comment] 2019-10-18 23:13
So, given that this is a real bug, I'm partial to pinning away from 1.3.0 and waiting for a fix from PyTorch. As @schmmd notes, they are actively working on it. Since it only came out eight days ago we probably don't have any hard dependencies on it yet. @DeNeutoy, @matt-gardner do either of you rely on 1.3.0 yet?

**Comment by schmmd** [comment] 2019-10-18 23:18
If that fixes it, makes sense to me.

**Comment by soumith** [comment] 2019-10-22 19:02
`pip install torch` will fix this now. Sorry for the delay, root-causing it and issuing new binaries took time.

**Comment by brendan-ai2** [comment] 2019-11-07 02:04
Fixed with @soumith's work (Thanks!) and the most recent pin.

**Closed by brendan-ai2** 2019-11-07 02:04 UTC
