### ISSUE TITLE
Shuffling + bucketing are incompatible with lazy dataset reading

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#3966] opened 2020-03-20 23:05 UTC
**System (please complete the following information):**
 - OS: OS X
 - Python version: 3.6.10
 - AllenNLP version: hash 4749fc3
 - PyTorch version: (if you installed it yourself): 1.4.0

**Question**
Is it possible to shuffle a lazily-read dataset with the new dataloaders?

Hi!

I'm working with a dataset that won't fit in main memory, so I'd like to lazily read it. However, it seems like the PyTorch DataLoader (understandably) gets mad at me when I set `"lazy": true` while still providing a `BatchSampler`:

```
ValueError: DataLoader with IterableDataset: expected unspecified batch_sampler option, but got batch_sampler=<allennlp.data.samplers.$ucket_batch_sampler.BucketBatchSampler object at 0x7f70493ba820>
```

So I removed the `BatchSampler` and set `"shuffle": true` in the data loader, but it also complains that:

```
ValueError: DataLoader with IterableDataset: expected unspecified shuffle option, but got shuffle=True
```

I guess this makes sense, since the loader doesn't get random access to the dataset. Is there any way to lazily read and still shuffle data? I'm not sure if this was always the behavior, or if this is new with the new dataloaders...can someone remind me?

**Comment by matt-gardner** [comment] 2020-03-20 23:35
Yeah, this is a new issue with the data loader code, and we don't have a great solution yet.  @dirkgr, did you have a list somewhere of potential solutions to this problem?  I kind of remember that, but not sure if I'm just remembering it wrong.

**Comment by matt-gardner** [comment] 2020-03-20 23:36
Related: #3819

**Comment by dirkgr** [comment] 2020-03-21 00:13
I don't have a list, just a way to do it in principle. We'll need a data loader that reads in a pool of instances, and then selects out of it randomly. I have not cast this idea in terms of the APIs we have though.

**Comment by JohnGiorgi** [comment] 2020-03-21 13:50
If you can fit your raw dataset into memory (a text file with one document per line, ~750K documents total) but cannot fit the `Instances` into memory like me, something like this works: https://discourse.allennlp.org/t/how-to-shuffle-the-data-each-batch-when-lazy-true/233

**Comment by DeNeutoy** [comment] 2020-03-24 18:16
@nelson-liu This was a trade-off in order to be able to use the pytorch data loaders. A simple work around (actually what I think should be the recommended solution until Pytorch figures it out) is to sort your instances in your dataset reader by something that will approximate bucketing in chunks, before yielding them individually. This way you get a reasonable approximation to bucketing and you can just use the vanilla basic iterator that pytorch provides.

Also note that this is a fundamental restriction with pytorch `IterableDatasets` (that you can't use samplers or batch samplers with them currently).

**Comment by nelson-liu** [comment] 2020-03-26 20:42
Thanks for the responses, @JohnGiorgi and @DeNeutoy . I just wanted simple shuffling, so I think the suggestion of loading the entire dataset into memory and `random.shuffle`ing it before yielding batches is a good one! I'm closing this issue for now, since there seems to be another one that addresses the broader problem (#3924)

**Comment by ud2195** [comment] 2020-06-03 11:39
has this problem been solved? facing a similar issue!
`ValueError: DataLoader with IterableDataset: expected unspecified batch_sampler option, but got batch_sampler=<allennlp.data.samplers.bucket_batch_sampler.BucketBatchSampler object at 0x7f1ad63b3d68>`

**Comment by matt-gardner** [comment] 2020-06-03 21:02
The `BucketBatchSampler` is not currently compatible with lazy datasets.  This is on our radar for things to do (@epwalsh, did you say you were thinking about this? I don't see an issue open for it), but we have no ETA yet.  You'll have to use a different sampler for now.

**Comment by epwalsh** [comment] 2020-06-03 21:04
What I'm working on right now is improving the `BucketBatchSampler` for distributed training, but I'll start thinking about this as well.

**Comment by matt-gardner** [comment] 2020-06-03 21:15
In any case, I think we should re-open this issue and mark it as for the 1.1 milestone for now.  I'll update the issue name to cover shuffling and bucketing with lazy datasets.  We've solved lazy + distributed, and you're working on bucketing + distributed, but we haven't solved shuffling or bucketing with lazy yet.

**Comment by ud2195** [comment] 2020-06-04 09:49
@matt-gardner @epwalsh can you please suggest some other data sampler that i can use with `lazy=true` ?

**Comment by matt-gardner** [comment] 2020-06-04 16:38
Thanks @JohnGiorgi. Yes, for now the recommended solution is either what @JohnGiorgi suggested just above, or what he suggested [farther up in the thread](https://github.com/allenai/allennlp/issues/3966#issuecomment-602046006).

**Comment by ud2195** [comment] 2020-06-04 18:54
@JohnGiorgi Thank you so much :)

**Comment by ud2195** [comment] 2020-06-05 11:30
@JohnGiorgi @matt-gardner 
using john's code snippet along with `lazy=true` in my config file allennlp was reading instances from my data indefinitely and when i removed `num_workers`  from the snippet and incorporated it in my config file it read my instances pretty quickly and training started. 

How is the above scenario possible?
this is my understanding of `num_workers`:-
pytorch's `num_workers` parameter helps us in loading the next batch of data. like when the main process is done with the passes and the main process is ready for another batch the worker process already has it queued up in memory so the main process doesnt have to read data from disk.
so initially in my config when i mentioned num_workers = 1 then why did it keep reading my instances from dataset indefinitely,more than an hour to be precise?(here main process is only involved in forward and backward passes. Worker process is loading the batches)
when in my config i mentioned `num_workers` = 0 (default) then it read my instances so quickly!. (here only main process is doing all the work forward passes,backward passes,loading the other batch)
-----------------------------
this is what happened when `num_workers` was set to 1
![Screenshot from 2020-06-05 13-44-20](https://user-images.githubusercontent.com/42403625/83871511-ce14a000-a74d-11ea-8dc3-e96c080157d0.png)

this is what happened when `num_workers` was set to 0
![Screenshot from 2020-06-05 14-50-15](https://user-images.githubusercontent.com/42403625/83871579-f00e2280-a74d-11ea-8b8c-41e6d1d7d48f.png)

**Comment by epwalsh** [comment] 2020-06-05 16:58
@ud2195 I'm looking into that.

**Comment by epwalsh** [comment] 2020-06-05 17:28
@ud2195 could you share your full config? I'm trying to reproduce this

**Comment by ud2195** [comment] 2020-06-05 17:33
config when i removed `num_workers`  : 
```
local transformer_model = "roberta-large";
local transformer_dim = 1024;
local cls_is_last_token = false;

{
  "dataset_reader":{
    "type": "snli",
    "lazy": true,
    "tokenizer": {
      "type": "pretrained_transformer",
      "model_name": transformer_model,
      "add_special_tokens": false
    },
    "token_indexers": {
      "tokens": {
        "type": "pretrained_transformer",
        "model_name": transformer_model,
        "max_length": 40
      }
    }
  },
  "train_data_path": "/content/cnli_train_5L.jsonl",
  "validation_data_path": "/content/cnli_val_5L.jsonl",
  
  "model": {
    "type": "basic_classifier",
    "text_field_embedder": {
      "token_embedders": {
        "tokens": {
          "type": "pretrained_transformer",
          "model_name": transformer_model,
          "max_length": 40
        }
      }
    },
    "seq2vec_encoder": {
       "type": "cls_pooler",
       "embedding_dim": transformer_dim,
       "cls_is_last_token": cls_is_last_token
    },
    "feedforward": {
      "input_dim": transformer_dim,
      "num_layers": 1,
      "hidden_dims": transformer_dim,
      "activations": "tanh"
    },
    "dropout": 0.1,
    "namespace": "tags"
  },
  "data_loader": {
        "batch_size": 8,
        
        "drop_last": true,
    },
  "trainer": {
    "num_epochs": 10,
    "cuda_device" : 0,
    "validation_metric": "+accuracy",
    "learning_rate_scheduler": {
      "type": "slanted_triangular",
      "cut_frac": 0.06
    },
    "optimizer": {
      "type": "huggingface_adamw",
      "lr": 2e-5,
      "weight_decay": 0.1,
    }
  }
}
```
config file when i set `num_workers`=1 : 
```
local transformer_model = "roberta-large";
local transformer_dim = 1024;
local cls_is_last_token = false;

{
  "dataset_reader":{
    "type": "snli",
    "lazy": true,
    "tokenizer": {
      "type": "pretrained_transformer",
      "model_name": transformer_model,
      "add_special_tokens": false
    },
    "token_indexers": {
      "tokens": {
        "type": "pretrained_transformer",
        "model_name": transformer_model,
        "max_length": 40
      }
    }
  },
  "train_data_path": "/content/cnli_train_5L.jsonl",
  "validation_data_path": "/content/cnli_val_5L.jsonl",
  
  "model": {
    "type": "basic_classifier",
    "text_field_embedder": {
      "token_embedders": {
        "tokens": {
          "type": "pretrained_transformer",
          "model_name": transformer_model,
          "max_length": 40
        }
      }
    },
    "seq2vec_encoder": {
       "type": "cls_pooler",
       "embedding_dim": transformer_dim,
       "cls_is_last_token": cls_is_last_token
    },
    "feedforward": {
      "input_dim": transformer_dim,
      "num_layers": 1,
      "hidden_dims": transformer_dim,
      "activations": "tanh"
    },
    "dropout": 0.1,
    "namespace": "tags"
  },
  "data_loader": {
        "batch_size": 8,
        "num_workers": 1,
        "drop_last": true,
    },
  "trainer": {
    "num_epochs": 10,
    "cuda_device" : 0,
    "validation_metric": "+accuracy",
    "learning_rate_scheduler": {
      "type": "slanted_triangular",
      "cut_frac": 0.06
    },
    "optimizer": {
      "type": "huggingface_adamw",
      "lr": 2e-5,
      "weight_decay": 0.1,
    }
  }
}

```

**Comment by epwalsh** [comment] 2020-06-05 18:23
I think I know what's going on. It's due to this: https://github.com/huggingface/tokenizers/issues/187

**Comment by epwalsh** [comment] 2020-06-05 18:28
@ud2195 could you open a separate issue for this? I want to make sure we keep tracking it.

**Comment by ud2195** [comment] 2020-06-05 18:49
@epwalsh sure ill do so, did you get the same results as well?

**Comment by epwalsh** [comment] 2020-06-05 19:05
I haven't tried to reproduce your example exactly, but I've seen this before.

**Comment by ud2195** [comment] 2020-06-05 19:23
all right @epwalsh thank you for looking into it , really appreciate it.

**Comment by epwalsh** [comment] 2020-06-05 22:18
@ud2195 okay yeup, just got around to running essentially the same config as yours and it's happening to me to. I went ahead and made an issue for it: https://github.com/allenai/allennlp/issues/4330

**Comment by mateuszpieniak** [comment] 2020-06-09 11:54
I will also mention annoying warnings from PyTorch using `num_workers=0`. In this case, I just don't know whether everything is working properly.


> /lib/python3.6/site-packages/torch/utils/data/dataloader.py:357: UserWarning: Length of IterableDataset <allennlp.data.dataset_readers.dataset_reader._LazyInstances object at 0x7fd162e4dd30> was reported to be 1 (when accessing len(dataloader)), but 1431 samples have been fetched. 

Btw, assuming that it works fine, is there a way to disable it in AllenNLP?

**Comment by epwalsh** [comment] 2020-06-09 13:14
Have you tried on master branch? I believe we fixed that issue.

**Comment by mateuszpieniak** [comment] 2020-06-09 15:44
@epwalsh You're right. It's already fixed on the current master branch. I stopped using the master branch since one beautiful day  `CallbackTrainer` disappeared & my code stopped working ^^

**Comment by matt-gardner** [comment] 2020-06-09 15:48
Have you tried using the `BatchCallback` and `EpochCallback` that are in the current trainer?

**Comment by dirkgr** [comment] 2020-06-11 10:33
I'm moving this to the Performance milestone, since @epwalsh is working on this as part of his performance work. If performance is fine without solving this problem, let's move it back.

**Comment by NicolasAG** [comment] 2020-07-28 18:29
Hi,
I tried to use the `BucketBatchSampler` with distributed training (`"distributed": {"cuda_devices": [0, 1]},`) but it fails. I see from the above discussion that there was some known issue with combinations involving `lazy`, `shuffle`, `distributed` and `BucketBatchSampler`. I wanted to know what is the status on that? and is there another issue / PR tracking the progress made on that problem?

Thank you :)

Below are more details about my current setup and what I observe:

configuration:
- Python: 3.7.8
- torch: 1.5.1
- allennlp: 1.1.0rc1
- CUDA: 10.2

Failing config file:
```jsonnet
{
    ...
    "data_loader": {
        "batch_sampler": {
            "type": "bucket",
            "batch_size": batch_size,
        },
        "batches_per_epoch": buffer_size,
    },
    "validation_data_loader": {
        "batch_sampler": {
            "type": "bucket",
            "batch_size": batch_size,
        },
    },
    ...
    "distributed": {"cuda_devices": [0, 1]},
    ...
}
```

it fails with the following error:
```
 ...
 2020-07-28 16:41:59,925 - INFO - allennlp.training.util - done creating vocab                                                                                         
 0 | 2020-07-28 16:42:04,716 - INFO - allennlp.common.params - random_seed = 14                                                                                        
 0 | 2020-07-28 16:42:04,717 - INFO - allennlp.common.params - numpy_seed = 14                                                                                         
 0 | 2020-07-28 16:42:04,718 - INFO - allennlp.common.params - pytorch_seed = 14                                                                                       
 0 | 2020-07-28 16:42:04,785 - INFO - allennlp.common.checks - Pytorch version: 1.5.1                                                                                  Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/usr/local/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 92, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/allennlp/commands/train.py", line 104, in train_model_from_args
    dry_run=args.dry_run,
  File "/usr/local/lib/python3.7/site-packages/allennlp/commands/train.py", line 158, in train_model_from_file
    dry_run=dry_run,
  File "/usr/local/lib/python3.7/site-packages/allennlp/commands/train.py", line 277, in train_model
    nprocs=num_procs,
  File "/usr/local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.7/site-packages/allennlp/commands/train.py", line 350, in _train_worker
    import_plugins()
  File "/usr/local/lib/python3.7/site-packages/allennlp/common/plugins.py", line 52, in import_plugins
    import_module_and_submodules(module_name)
  File "/usr/local/lib/python3.7/site-packages/allennlp/common/util.py", line 351, in import_module_and_submodules
    import_module_and_submodules(subpackage)
  File "/usr/local/lib/python3.7/site-packages/allennlp/common/util.py", line 338, in import_module_and_submodules
    with push_python_path("."):
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/allennlp/common/util.py", line 316, in push_python_path
    path = Path(path).resolve()
  File "/usr/local/lib/python3.7/pathlib.py", line 1166, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "/usr/local/lib/python3.7/pathlib.py", line 360, in resolve
    base = '' if path.is_absolute() else os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
```

working config files:
(distributed, but no `BucketBatchSampler`)
```jsonnet
{
    ...
    "data_loader": {
        "batch_size": batch_size,
        "batches_per_epoch": buffer_size,
        "shuffle": true,
    },
    "validation_data_loader": {
        "batch_size": batch_size,
        "shuffle": false,
    },
    ...
    "distributed": {"cuda_devices": [0, 1]},
    ...
}
```
or (`BucketBatchSampler` but on a single GPU):
```jsonnet
{
    ...
    "data_loader": {
        "batch_sampler": {
            "type": "bucket",
            "batch_size": batch_size,
        },
        "batches_per_epoch": buffer_size,
    },
    "validation_data_loader": {
        "batch_sampler": {
            "type": "bucket",
            "batch_size": batch_size,
        },
    },
    ...
    "trainer": {
        ...
        cuda_device: 0
    }
    ...
}
```

**Comment by epwalsh** [comment] 2020-07-28 19:02
Hi @NicolasAG, the `BucketBatchSampler` *should* work fine with distributed training, I've never seen this error before. What OS are you running on?

**Comment by NicolasAG** [comment] 2020-07-28 19:43
@epwalsh I am running on Ubuntu most likely. I use the following Dockerfile to create my image:
```Dockerfile
FROM allennlp/models:latest

RUN pip install -U torch torchvision
# make sure this is compiled for CUDA 10.2

WORKDIR /
```

**Comment by epwalsh** [comment] 2020-07-28 21:27
I tried to repro with your Dockerfile, but with no luck. What happens if you just run this from your Docker image:

```python
from allennlp.common.plugins import import_plugins

import_plugins()
```

**Comment by NicolasAG** [comment] 2020-07-28 22:39
This is the output of `import_plugins()`:
```
[nltk_data] Downloading package punkt to /tmp/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /tmp/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
```

I'm having trouble reproducing the "working case" with distributed training. It turns out that I also get the same error without the `BucketBatchSampler` even though it worked once before... I will investigate more but I think this has become unrelated to the original issue so feel free to ignore my previous message.

**Comment by epwalsh** [comment] 2020-07-29 00:17
@NicolasAG gotcha. Yea definitely seems like a separate issue. Feel free to open a new one if you get a change and assign me to it.

~Pete

**Comment by epwalsh** [comment] 2020-09-02 16:25
Shuffling + bucketing in lazy mode are now compatible with the new `DataLoader`. Currently this is only available on the `vision` branch, and is targeted to go out with our 2.0 release (no ETA on that yet) since it involves some minor breaking changes to the data loading / data reading API.

**Closed by epwalsh** 2020-09-02 16:25 UTC
