### ISSUE TITLE
Beginning and end of sentece mismatch when using pre-trained transformers

### ISSUE THREAD

**Issue by nicola-decao** [allenai/allennlp#3435] opened 2019-11-06 18:26 UTC
Related to https://github.com/allenai/allennlp/issues/3434 but different.
Beginning and end of sentence tokens are hardcoded as default in
https://github.com/allenai/allennlp/blob/9a6962f00d2b0d30b81900b4e9764ddc3433f400/allennlp/common/util.py#L43
and
https://github.com/allenai/allennlp/blob/9a6962f00d2b0d30b81900b4e9764ddc3433f400/allennlp/common/util.py#L44
so when using any pre-trained token embedder where there are different tokens it might generate wrong sequences.

Can we make these variable configurable? (e.g., using BERT start and end are `[CLS]` and `[SEP]` and we might want to use those instead of the default one).

**Comment by matt-gardner** [comment] 2019-11-08 02:34
Those are used for certain places in decoding in encoder-decoder models.  They aren't used the same way as `[CLS]` and `[SEP]` tokens.  Are you sure this is what you want?  I'm pretty sure it's not, unless there's some use of `[CLS]` and `[SEP]` in decoders that I'm not aware of.

**Comment by nicola-decao** [comment] 2019-11-08 07:56
You are right. In general, you should not use these tokens unless you want to use a pre-trained projection layer. It might not be a priority but It would be nice if these variables `START_SYMBOL` and `END_SYMBOL` could be configurable. They are indeed used in the `AutoRegressiveSeqDecoder`. I think it is a better idea to maybe add them in the initializer and don't touch `allennlp/allennlp/common/util.py`.

**Comment by matt-gardner** [comment] 2019-11-08 19:45
The reason they are in `common/util.py` instead of in a model constructor or some other place is because when you need this you typically need it in both a `DatasetReader` and a `Model`, and they need to be the same.  It probably doesn't matter what the actual value is, because you'll be adding it in code (not in the data) in both places, so all that matters is that they agree.  This is why we put it in a common place that both the data code and the model code can access.

**Comment by kernelmachine** [comment] 2019-11-08 23:22
Those strings do not seem to be used very often, so presumably others are using other mechanisms to add start and end tokens. Should we try to standardize how we add start/end tokens across all models?

**Comment by schmmd** [comment] 2019-11-08 23:23
```
$ git grep '@start@' | wc -l
      68
$ git grep START_SYMBOL | wc -l
      28
```

**Comment by nicola-decao** [comment] 2019-11-11 11:15
Another comment/issues: if one uses `PretrainedTransformerIndexer` and `PretrainedTransformerTokenizer` both `@start@` and `@end@` are not added to the vocabulary and therefore considered as OOV symbols. This of course is a problem.

**Comment by schmmd** [comment] 2019-11-11 16:12
@nicola-decao we'd warmly welcome a PR for that issue.

**Comment by matt-gardner** [comment] 2019-11-11 17:07
No, this is not a bug.  You are supposed to add those manually to whatever token strings they are needed in your `DatasetReader` (after which they'd get added to your vocab).  We can't add them in the classes you mention, because then they'd get used everywhere, and we only want those tokens when we're doing decoding.

To repeat: those tokens are control tokens that are _only_ used for encoder-decoder models.  They are not general-purpose, use-everywhere tokens.  @schmmd, your `git grep` is misleading, as _all_ of the uses of `'@start@'` outside of the one use in `common/util.py` are in tests.  I'm closing this issue, as there is nothing here to fix.

**Closed by matt-gardner** 2019-11-11 17:07 UTC
Labels: Waiting For Response

**Comment by nicola-decao** [comment] 2019-11-11 17:10
@matt-gardner Ok, I agree.

**Comment by JohnGiorgi** [comment] 2019-11-26 01:07
Sorry, I am still confused on how to use a [`PretrainedTransformerIndexer`](https://allenai.github.io/allennlp-docs/api/allennlp.data.token_indexers.html#pretrained-transformer-indexer) as the encoder of a encoder-decoder model without running into issues because of `START_SYMBOL` and `END_SYMBOL`.

I am using the [`Seq2SeqDatasetReader`](https://allenai.github.io/allennlp-docs/api/allennlp.data.dataset_readers.seq2seq.html) with the [`PretrainedTransformerTokenizer`](https://allenai.github.io/allennlp-docs/api/allennlp.data.tokenizers.html#pretrained-transformer-tokenizer) and `PretrainedTransformerTokenIndexer`. The relevant section of my config looks like:

```jsonnet
local pretrained_transformer_model_name = "bert-base-uncased";

{
    "dataset_reader": {
        "lazy": false,
        "type": "seq2seq",
        "source_tokenizer": {
            "type": "pretrained_transformer",
            "model_name": pretrained_transformer_model_name,
            "max_length": 512,
        },
        "source_token_indexers": {
            "tokens": {
                "type": "pretrained_transformer",
                "model_name": pretrained_transformer_model_name,
            },
        },

...

}
```

I see that the dataloader adds the `START_SYMBOL` and `END_SYMBOL` tokens to the beginning and end of the tokenized string respectively before indexing (relevant lines [here](https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/seq2seq.py#L127-L129)).

However, the `text_id` property is never updated for these symbols. Because `PretrainedTransformerIndexer` expects this attribute to be `not None`, I run into this error at some point during data iteration, when a `START_SYMBOL` is encountered:

```
  File "/lustre03/project/6006286/johnmg/t2t/allennlp/allennlp/data/token_indexers/pretrained_transformer_indexer.py", line 91, in tokens_to_indices
    f"Using PretrainedTransformerIndexer but field text_id is not set for the following token: {token.text}"
KeyError: 'Using PretrainedTransformerIndexer but field text_id is not set for the following token: @start@'
```
@matt-gardner Are you able to point out what I am doing wrong? Any help is appreciated!

**Comment by matt-gardner** [comment] 2019-11-26 14:59
I'm not sure how people do decoding with transformers these days; I don't really have any experience with it.  If you really want to use BERT (or whatever transformer) as the decoder, you probably want to set things up a little differently than we have them, but I'm not really sure in what ways.

With this code, it seems like you have two options:

1. Use a different target indexer (e.g., a `SingleIdTokenIndexer`), which was what we were intending with the seq2seq code anyway.  This way, you would encode with your pretrained transformer, but decode with something simpler.  My intuition is that this is what you *have* to do with our code, because the transformers need different handling during decoding than what we have implemented, but I could be wrong.  (And maybe the `ComposedSeq2Seq` is general enough to handle decoding with transformers; I don't really know.)

2. Find an unused vocabulary item in your pretrained transformer vocab (I believe BERT at least had a number of these special tokens that were reserved for future use) and set the `text_id` to that when you add the `@start@` token in your dataset reader.  You still need to be sure that the model you're using does the right thing during decoding, but this would solve your immediate error.

**Comment by JohnGiorgi** [comment] 2019-11-26 17:06
Thank @matt-gardner, point 1 was exactly the advice I was looking for. I actually only want the pretrained-transformer as encoder, and to keep the decoder as the default LSTM implemented in `SimpleSeq2Seq`.

Using `SpacyTokenizer` + `SingleIdTokenIndexer` as my target tokenizer and token indexer fixed the issue.
