### ISSUE TITLE
Memory too much used by AllenNLP TE model

### ISSUE THREAD

**Issue by JunhaoZhang1992** [allenai/allennlp#486] opened 2017-11-13 06:45 UTC
Hi， 
  I am running AllenNLP TE model.  I find the step of dataset_reader.read(train_data_path) used too memory. 
  The training dataset is 1GB (about 3 million instances), but memory used is 32GB.  
  The model parameters is only 45MB.

  How can I make it more memory efficient to use more data for training?

**Comment by schmmd** [comment] 2017-11-13 17:02
Hi @JunhaoZhang1992 , can you share the exact commands, configuration, and data you are using to train your model, as well as the machine configuration you are running on?  Presently it's hard to troubleshoot your issue.

**Comment by matt-gardner** [comment] 2017-11-14 17:34
@JunhaoZhang1992, there was a brief period where we were loading spacy 2.0 incorrectly - if you were using master a day or two ago, this may have been the cause of the problem.  We pushed a fix for this yesterday.  Care to try it again?

**Closed** 2017-12-07 01:56 UTC
