### ISSUE TITLE
reading-comprehension

### ISSUE THREAD

**Issue by thom-alt** [allenai/allennlp#3561] opened 2019-12-29 00:46 UTC
Hello!

I am a beginner and I have just cloned the repository. Now I would like to use the reading-comprehension component of this project to see how it work. But there is no specific readme which explains step by step how it works. At least I can't find it.

An orientation please?

**Comment by schmmd** [comment] 2020-01-03 23:07
Closing as a duplicate of https://discourse.allennlp.org/t/reading-comprehension/161.

**Closed by schmmd** 2020-01-03 23:07 UTC
