### ISSUE TITLE
how to save examples for pre-process data?

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#2123] opened 2018-11-30 13:22 UTC
after i process for data to get instance, i want to save the information to load for the next trains, i don't want to process data for each train, how to save examples?

**Comment by joelgrus** [comment] 2018-11-30 14:43
there's not really a way to do this inside the library right now. I think we'd like to do this, but getting the design right in a general way is hard.

we've typically handled this by writing a script to preprocess the data and save it to disk, and then modifying the relevant `DatasetReader` to be able to read the preprocessed data.

**Comment by susht3** [comment] 2018-12-01 08:00
> we've typically handled this by writing a script to preprocess the data and save it to disk, and then modifying the relevant `DatasetReader` to be able to read the preprocessed data.

thanks a lot , but i find a problem that,  at allennlp/allennlp/data/tokenizers/word_tokenizer.py,
` def tokenize(self, text: str) -> List[Token]:
        words = self._word_splitter.split_words(text)
        return self._filter_and_stem(words)`

then on allennlp/allennlp/data/tokenizers/word_splitter.py, 
` def split_words(self, sentence: str) -> List[Token]:
        # This works because our Token class matches spacy's.
        return _remove_spaces(self.spacy(sentence))
def _remove_spaces(tokens: List[spacy.tokens.Token]) -> List[spacy.tokens.Token]:
    return [token for token in tokens if not token.is_space]`

it seems that the type of word in splitter is spacy.tokens.Token, but on tokenizer it is a Token from allennlp, is spacy.tokens.Token equal to allennlp Token?

**Comment by matthew-z** [comment] 2018-12-02 17:06
Yes, they are

**Comment by schmmd** [comment] 2018-12-07 21:11
Closing since @joelgrus answered the question and matthew-z answered the follow.  Please re-open if you have more questions!

**Closed by schmmd** 2018-12-07 21:11 UTC

**Comment by nadre** [comment] 2018-12-30 12:20
The datareaders support lazy loading which (besides being more memory efficient) takes away the pain of waiting for the dataset being processed at the beginning. The problem is that the whole dataset usually is needed to extract the vocab. What you can do is extract the vocab once and save it using vocab.save_to_files() and then load from disk instead of using Vocabulary.from_instances(). Hope this helps!
