### ISSUE TITLE
The best way to create two datasets with some fields sharing the same vocab

### ISSUE THREAD

**Issue by taineleau** [allenai/allennlp#1331] opened 2018-06-02 20:35 UTC
Hi,

Could anyone show me the best practice to create two datasets with a portion of fields sharing the same vocab? If using from_params, I could only share the vocab of all fields.

**Comment by matt-gardner** [comment] 2018-06-04 15:29
Can you be more specific about what you're trying to do here?  What do you mean by "two datasets"?  If you give me something more concrete (maybe with some example code of what you tried) I'll be able to help you a lot better.

Without knowing more detail, the best I can do is point you to our [vocabulary tutorial](https://github.com/allenai/allennlp/blob/master/tutorials/notebooks/vocabulary.ipynb).  Vocabularies have as many _namespaces_ as you want, so, yes, you can have some fields share the same vocabulary.

**Comment by taineleau** [comment] 2018-06-05 06:06
I am working on morphology prediction that needs a joint training of TWO datasets. We have to make sure the `POS tagging` fields of these two datasets are the same (i.e., token_to_index should be the same). Currently, we solve it by:

vocab1 = Vocabulary.from_instance(fake_instances + train_instance1)
vocab2 = Vocabulary.from_instance(fake_instances + train_instance2)

`fake_instance` consists of dummy instances that the "pos tagging" filed is the union of two datasets' pos tagging token.

The reason that I don't want to blend the two datasets into one is that I want to have different sampling methods for these two datasets.

**Comment by joelgrus** [comment] 2018-06-05 14:04
here's what I would probably try:

(I assume each dataset has a TextField (with some text) and a LabelField (with the POS tag))

it sounds like you probably have two different dataset readers already (because of the different sampling methods).

in the token_indexers for dataset1, send the tokens to a namespace `tokens1` and similarly in the token_indexers for dataset2, send the tokens to a namespace `tokens2`:

```
reader1 = MyDatasetReader(sampling_method="a", token_indexers={'tokens': SingleIdTokenIndexer(namespace='tokens1')})
reader2 = MyDatasetReader(sampling_method="b", token_indexers={'tokens': SingleIdTokenIndexer(namespace='tokens2')})

instances1 = reader1.read(file1)
instances2 = reader2.read(file2)

vocab = Vocabulary.from_instances(instances1 + instances2)
```

Assuming your dataset reader puts labels in the "labels" namespace, it will automatically be shared, but the tokens will be in separate namespaces. Then you just have one vocabulary. 

Is that the sort of thing you're looking for?

**Comment by matt-gardner** [comment] 2018-06-05 15:10
You could also use the `make_vocab` command to construct the vocabulary as best we can for both datasets, then manually edit it yourself, and pass a pre-existing vocabulary during actual training, using the `directory_path` flag: https://github.com/allenai/allennlp/blob/0c2d5c77f3ee7a48693af822fa74b2dfe3eaa184/allennlp/data/vocabulary.py#L362-L371

It sounds like you've got your own script, though, instead of using our `train` command, so @joelgrus's suggestion should work fine.  But if you still have trouble, you can always just manually specify the vocab using these files.

**Comment by joelgrus** [comment] 2018-06-08 18:29
closing, please re-open if your issue is not resolved

**Closed by joelgrus** 2018-06-08 18:29 UTC

**Comment by taineleau** [comment] 2018-06-10 10:56
Hi,

There're more than one filed for the two datasets and I just want to share the `tagging` filed between them while other fields are using separate vocab.

thanks @matt-gardner. I guess this is what I need.

**Comment by RamanRajarathinam** [comment] 2019-06-07 10:32
@matt-gardner  the link to vocabulary tutorial returns 404 (https://github.com/allenai/allennlp/blob/master/tutorials/notebooks/vocabulary.ipynb). could you pls update the link or give me other link to refer?

**Comment by RamanRajarathinam** [comment] 2019-06-07 10:48
@matt-gardner I have the following json

> {
  "train_data_path": "data/train.csv",
  "validation_data_path": "data/validation.csv",
  "vocabulary": {
    "min_count": {
      "tokens": 10
    }
  },
  "dataset_reader": {
    "type": "classification_data_reader",
    "max_seq_len": 100,
    "tokenizer": {
      "type": "word",
      "word_splitter": {
        "type": "bert-basic",
        "do_lower_case": true
      }
    },
    "token_indexers": {
      "namespace": "tokens",
      "bert": {
        "type": "bert-pretrained",
        "pretrained_model": "bert-base-uncased",
        "do_lowercase": true
      }
    }
  }
}

when I run **allennlp make-vocab experiments/config.json -s vocab_dir --include-package library**

i) The commands runs fine.
ii) It creates a directory **vocab_dir** and inside it has **vocabulary** directory which has labels.txt and non_padded_namespaces.txt 

i.e.
-  vocab_dir
    - vocabulary
        - labels.txt (contains my binary labels 0 and 1)
        - non_padded_namespaces.txt (contains *tags and *labels)

other than this, I don't see vocabulary directory contains any of the information realted to vocabulary tokens. 
- What I am asking is where do you store my dataset tokens?
- Is this expected behavior? if not please help me with this.

**Comment by matt-gardner** [comment] 2019-06-07 17:35
BERT has its own vocabulary, which we don't deal with in allennlp.  So, what you see is expected behavior.

**Comment by RamanRajarathinam** [comment] 2019-06-10 06:44
@matt-gardner I found the solution later that day and forgot to update here. Many thanks for your kind reply.
