### ISSUE TITLE
SNLI dataset reader error

### ISSUE THREAD

**Issue by hoang-ho** [allenai/allennlp#4143] opened 2020-04-25 01:29 UTC
I'm trying to experiment ESIM + ELMo on SNLI. However, there is no SNLI dataset reader. I'm using the config file from allennlp-models: https://github.com/allenai/allennlp-models/blob/v1.0.0.rc1/training_config/nli/esim_elmo.jsonnet. Any suggestion on how to fix this. 

I rab

```bash
allennlp train esim_elmo.jsonnet -s allennlp_elmo_snli
```

and receive the following error:

allennlp.common.checks.ConfigurationError: snli not in acceptable choices for dataset_reader.type: ['conll2003', 'interleaving', 'sequence_tagging', 'sharded', 'babi', 'text_classification_json']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.

**Comment by epwalsh** [comment] 2020-05-01 21:35
Hey @hoang-ho, sorry for the delay on this. This should be fixed now with the latest release (rc3). Please re-open this if you're still having issues.

**Closed by epwalsh** 2020-05-01 21:35 UTC

**Comment by mateuszpieniak** [comment] 2020-05-26 08:05
@epwalsh I just downloaded `1rc4` and there is still no `SNLI` Dataset reader

**Comment by styx97** [comment] 2021-02-28 23:19
Hi, I'm trying to use the snli dataset reader and it still shows the same error 

> `allennlp.common.checks.ConfigurationError: snli not in acceptable choices for dataset_reader.type: ['babi', 'conll2003', 'interleaving', 'multitask', 'sequence_tagging', 'sharded', 'text_classification_json', 'multitask_shim']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.
> `

I am using the latest version of allenai (2.1.0).

**Comment by epwalsh** [comment] 2021-03-01 16:40
@styx97 do you have `allennlp-models` installed?

**Comment by styx97** [comment] 2021-03-01 17:50
My bad, I didn't know it was in allennlp-models, that fixed it! Thanks a lot!

**Comment by styx97** [comment] 2021-04-21 07:43
Hi, I am facing the same error as above while trying to use load_archive to load a locally trained model. 

```

> from allennlp.models.archival import load_archive 
> from allennlp.predictors.predictor import Predictor 
> 
> archive_base = load_archive("models/model.tar.gz")

```

I have allennlp-models installed, (version 2.1.0)

**Comment by epwalsh** [comment] 2021-04-21 20:17
The `load_archive` function does not import plugins. So you either need to call `allennlp.common.plugins.load_plugins()` before `load_archive()`, or just use `Predictor.from_path("models/model.tar.gz")`.

**Comment by styx97** [comment] 2021-04-21 23:34
I can load the predictor from path, but while using it to make predictions, I am getting an error. 

```

> snli_predictor = Predictor.from_path("models/model.tar.gz")
> snli_predictor.predict(
>     premise="Two women are wandering along the shore drinking iced tea.",
>     hypothesis="Two women are sitting on a blanket near some rocks talking about politics."
> )

```

yields 

> `TypeError: predict() got an unexpected keyword argument 'premise'
`

**Comment by epwalsh** [comment] 2021-04-21 23:39
You will need to specify the right predictor subclass to use:

```diff
-snli_predictor = Predictor.from_path("models/model.tar.gz")
+snli_predictor = Predictor.from_path("models/model.tar.gz", predictor_name="textual_entailment")
```

**Comment by styx97** [comment] 2021-04-21 23:41
Thanks a lot!, it's working now.

**Comment by epwalsh** [comment] 2021-04-21 23:43
Great :)

**Comment by sreeshna** [comment] 2022-06-04 06:55
ConfigurationError: coref not in acceptable choices for dataset_reader.type: ['babi', 'conll2003', 'interleaving', 'multitask', 'multitask_shim', 'sequence_tagging', 'sharded', 'text_classification_json']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.

**Comment by sreeshna** [comment] 2022-06-04 06:56
---------------------------------------------------------------------------
ConfigurationError                        Traceback (most recent call last)
Input In [17], in <cell line: 2>()
      1 model_url = 'https://storage.googleapis.com/allennlp-public-models/coref-spanbert-large-2020.02.27.tar.gz'
----> 2 predictor = Predictor.from_path(model_url)

File ~/anaconda3/lib/python3.9/site-packages/allennlp/predictors/predictor.py:366, in Predictor.from_path(cls, archive_path, predictor_name, cuda_device, dataset_reader_to_load, frozen, import_plugins, overrides, **kwargs)
    363 if import_plugins:
    364     plugins.import_plugins()
    365 return Predictor.from_archive(
--> 366     load_archive(archive_path, cuda_device=cuda_device, overrides=overrides),
    367     predictor_name,
    368     dataset_reader_to_load=dataset_reader_to_load,
    369     frozen=frozen,
    370     extra_args=kwargs,
    371 )

File ~/anaconda3/lib/python3.9/site-packages/allennlp/models/archival.py:232, in load_archive(archive_file, cuda_device, overrides, weights_file)
    229 config = Params.from_file(os.path.join(serialization_dir, CONFIG_NAME), overrides)
    231 # Instantiate model and dataset readers. Use a duplicate of the config, as it will get consumed.
--> 232 dataset_reader, validation_dataset_reader = _load_dataset_readers(
    233     config.duplicate(), serialization_dir
    234 )
    235 model = _load_model(config.duplicate(), weights_path, serialization_dir, cuda_device)
    237 # Load meta.

File ~/anaconda3/lib/python3.9/site-packages/allennlp/models/archival.py:268, in _load_dataset_readers(config, serialization_dir)
    262 # Try to use the validation dataset reader if there is one - otherwise fall back
    263 # to the default dataset_reader used for both training and validation.
    264 validation_dataset_reader_params = config.get(
    265     "validation_dataset_reader", dataset_reader_params.duplicate()
    266 )
--> 268 dataset_reader = DatasetReader.from_params(
    269     dataset_reader_params, serialization_dir=serialization_dir
    270 )
    271 validation_dataset_reader = DatasetReader.from_params(
    272     validation_dataset_reader_params, serialization_dir=serialization_dir
    273 )
    275 return dataset_reader, validation_dataset_reader

File ~/anaconda3/lib/python3.9/site-packages/allennlp/common/from_params.py:585, in FromParams.from_params(cls, params, constructor_to_call, constructor_to_inspect, **extras)
    583 as_registrable = cast(Type[Registrable], cls)
    584 default_to_first_choice = as_registrable.default_implementation is not None
--> 585 choice = params.pop_choice(
    586     "type",
    587     choices=as_registrable.list_available(),
    588     default_to_first_choice=default_to_first_choice,
    589 )
    590 subclass, constructor_name = as_registrable.resolve_class_name(choice)
    591 # See the docstring for an explanation of what's going on here.

File ~/anaconda3/lib/python3.9/site-packages/allennlp/common/params.py:324, in Params.pop_choice(self, key, choices, default_to_first_choice, allow_class_names)
    317     key_str = self.history + key
    318     message = (
    319         f"{value} not in acceptable choices for {key_str}: {choices}. "
    320         "You should either use the --include-package flag to make sure the correct module "
    321         "is loaded, or use a fully qualified class name in your config file like "
    322         """{"model": "my_module.models.MyModel"} to have it imported automatically."""
    323     )
--> 324     raise ConfigurationError(message)
    325 return value

ConfigurationError: coref not in acceptable choices for dataset_reader.type: ['babi', 'conll2003', 'interleaving', 'multitask', 'multitask_shim', 'sequence_tagging', 'sharded', 'text_classification_json']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.
