### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by Thidashwe** [allenai/allennlp#3787] opened 2020-02-16 06:54 UTC
Hello everyone, 

I am trying to allocate specific gpus to CNN by using the following comments: 

import os
os.environ["CUDA_DEVICE_ORDER"] = ("PCI_BUS_ID")
os.environ["CUDA_VISIBLE_DEVICES"] = ("2,4")

and it generated an "cuda out of memory error", but I have two free gpu and of course enough memory space as you can see as follow: 

![Capture](https://user-images.githubusercontent.com/46780233/74600325-4427c500-50d3-11ea-8696-897ae6c94e27.JPG)

The comment os.environ["CUDA_VISIBLE_DEVICES"] = ("2,4") didn't work out.

I want to assign specific gpus to the CNN, for example, I have gpu from 0 to 4, and only want to assign gpu 2 and 4 (the empty ones) to the CNN to run training.

Anyone could help please? Thank you in advanced.

My current environment set up is described as follow:
 - OS:  Linux server
 - Python version: 3.7.6
 - PyTorch version: 1.1.0

**Comment by matt-gardner** [comment] 2020-02-16 17:04
I'm pretty sure this is a duplicate of #1090.  Can you look at that issue and see if it solves your problem?

**Comment by Thidashwe** [comment] 2020-02-17 07:28
Thank you Matt, it seems like it re-functions again after I change ["CUDA_VISIBLE_DEVICES"] = ("2,4") into ["CUDA_VISIBLE_DEVICES"] = '4', to index only one gpu.

**Closed** 2020-02-18 17:25 UTC
