### ISSUE TITLE
Length mismatch after openai text_field_embedder

### ISSUE THREAD

**Issue by tingkai-zhang** [allenai/allennlp#2020] opened 2018-11-07 00:27 UTC
**Describe the bug**
Hi, I open this new issue to provide details.
I am implementing [OpenaiGPT for classification task](https://github.com/tingkai-zhang/Generative-Pre-trained-Transformer) using allennlp.

The output shape of `text field embedder` doesn't match with the input.

After text of shape [batch_size, num_timestamp, num_embedding] is forward after [text_filed_embedder](). The number of timestamps shrinks, which differs from the original GPT pytorch implementation.

I check the source code, seems that it returns [batch_size, seq_length, num_embedding].

And the problem comes that when i [add a classifier head](https://github.com/tingkai-zhang/Generative-Pre-trained-Transformer/blob/33e837355973a47db0d2dcf3bf0391aab03c338b/my_library/modules/Heads/ClfHead.py#L18) on top of transformer embedder.
It requires the `h` which is the  output of `text field embedder` has the same number of timestamps as the input

**To Reproduce**

[the project repo](https://github.com/tingkai-zhang/Generative-Pre-trained-Transformer)

The lines of code uses [text field embedder](https://github.com/tingkai-zhang/Generative-Pre-trained-Transformer/blob/33e837355973a47db0d2dcf3bf0391aab03c338b/my_library/models/GPT.py#L55)

[Classifier head](https://github.com/tingkai-zhang/Generative-Pre-trained-Transformer/blob/33e837355973a47db0d2dcf3bf0391aab03c338b/my_library/modules/Heads/ClfHead.py#L18)

**System (please complete the following information):**
 - OS:  Linux
 - Python version:  3.6
 - AllenNLP version:  v0.7.1

**Additional context**

**Comment by joelgrus** [comment] 2018-11-07 00:36
this is by design -- the input to the embedder is the byte pairs (which is in general a longer sequence than the tokens themselves), but the output is one vector per token, which we get by taking the embeddings just for the last byte pair for each token:

https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/openai_transformer_embedder.py#L89

**Comment by tingkai-zhang** [comment] 2018-11-07 01:06
> this is by design -- the input to the embedder is the byte pairs (which is in general a longer sequence than the tokens themselves), but the output is one vector per token, which we get by taking the embeddings just for the last byte pair for each token:
> 
> https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/openai_transformer_embedder.py#L89


OK. So if i provide offsets to forward function,  'the output is one vector per token '. That is, the `seq_length` is the number of token.
If i dont provide offsets, the `seq_length` of output is number of byte pairs, which is a longer sequence.
Am i right?

**Comment by joelgrus** [comment] 2018-11-07 02:30
yes, that's correct.

since you are using the openai token indexer, that should all happen automatically -- it generates the offsets:

https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/openai_transformer_byte_pair_indexer.py#L224

and then based on the `embedder_to_indexer_map` in your config they get passed to the embedder:

https://github.com/tingkai-zhang/Generative-Pre-trained-Transformer/blob/master/experiments/baseline.json#L28

**Comment by tingkai-zhang** [comment] 2018-11-07 03:13
> yes, that's correct.
> 
> since you are using the openai token indexer, that should all happen automatically -- it generates the offsets:
> 
> https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/openai_transformer_byte_pair_indexer.py#L224
> 
> and then based on the `embedder_to_indexer_map` in your config they get passed to the embedder:
> 
> https://github.com/tingkai-zhang/Generative-Pre-trained-Transformer/blob/master/experiments/baseline.json#L28

Thank you! Actually i did both experiments (with/without offsets) before.
But whether i provided `offsets` or not, the **`seq_length` of output  and nonzero part of input** are not match.

Please let me make this a little bit clear.

Suppose we have one tokenized sentence of length 256, each element corresponds to a byte-pair representation.

After being padded by `OpenaiTransformerBytePairIndexer`, it has length 512.

The input of the  `text_field_embedder`  has shape [1, 512].

Because we padded input sentence with zeros, so the `seq_lengh` of **nonzero part of input sentence**  is 256. 

The output of  `text_field_embedder`  should have shape [1,256] (if not providing offsets) or [1, 200] (if providing offsets)

The **`seq_length` of output**  should be 256 or 200

My experiments show me that **`seq_length` of output**  is neither 256 or 200.

**Comment by tingkai-zhang** [comment] 2018-11-07 03:20
To reproduce my result, just download my repo and `python main.py`

It should take 10 seconds to get the same error.

And i set the breakpoint [here ](https://github.com/tingkai-zhang/Generative-Pre-trained-Transformer/blob/d3672df2ce1842fedb87862f2922ab7d596ade63/my_library/modules/Heads/ClfHead.py#L26)to see the input and output of `text field embedder`

In that function, 
x is the padded tokenized sentence of shape [1, 512]
h is the output 

The line `flat = flat[flat.nonzero()]` to get the none zero part of input.

**Comment by tingkai-zhang** [comment] 2018-11-07 03:42
Also, the implementation idea [here](https://github.com/allenai/allennlp/blob/0b852fb2ef1000fa6209815d1c91171a9b093fef/allennlp/modules/token_embedders/openai_transformer_embedder.py#L89) differs from the original one.

It says: 

>      # These embeddings are one per byte-pair, but we want one per original _word_.
        # So we choose the embedding corresponding to the last byte pair for each word,
        # which is captured by the ``offsets`` input.


I also see the code corresponding to phrase ` the last byte pair `. But they took the last hidden representation of each sentence!

Also, the `offset` idea in original implementation is to use classify token to identify the ` the last byte pair `

That's why [here](https://github.com/tingkai-zhang/Generative-Pre-trained-Transformer/blob/b8660db5277a52e658772697077d9dfccbbd2e9b/my_library/modules/Heads/ClfHead.py#L9)is a `clf_token` argument in the function:

**Comment by schmmd** [comment] 2018-11-09 21:14
Closing as this isn't an issue (see #2023 for more discussion).

**Closed by schmmd** 2018-11-09 21:14 UTC
