### ISSUE TITLE
Import errors for Token class after installing AllenNLP via pip.

### ISSUE THREAD

**Issue by rsilveira79** [allenai/allennlp#550] opened 2017-11-29 18:21 UTC
Hello,
I've installed Allennlp using pip, and I'm trying to run some demos and follow tutorials.
Tried to import Token class in several different ways, seems something is broken.
Thanks for your support!

**ERROR**: ModuleNotFoundError: No module named 'allennlp.data. ...
from allennlp.data.tokenizers.token import Token
from allennlp.data.tokenizers import Token

**Comment by schmmd** [comment] 2017-11-29 18:34
@rsilveira79 what version of Python are you using?

```
~ python --version
Python 3.6.0 :: Continuum Analytics, Inc.
```

I'm not able to repeat the problem you are encountering.  Can you supply the logs from `pip install allennlp`?  Can you give me a command you are running and the full stacktrace?

**Comment by matt-gardner** [comment] 2017-11-29 18:35
Seems related: https://github.com/allenai/allennlp/issues/540, https://github.com/allenai/allennlp/issues/538

**Comment by rsilveira79** [comment] 2017-11-29 19:40
I'm running python 3.6.3 on OSX Sierra 10.12.6.
I'm running (https://github.com/allenai/allennlp-as-a-library-example) and wanted to start creating notebooks with new models.
You can see the log of `pip install allennlp` below:
----------
Python 3.6.3 (default, Oct  4 2017, 06:09:15)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)
---------
Requirement already satisfied: allennlp in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages
Requirement already satisfied: tqdm in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from allennlp)
Requirement already satisfied: typing in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from allennlp)
Requirement already satisfied: nltk in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from allennlp)
Requirement already satisfied: pyhocon==0.3.35 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from allennlp)
Requirement already satisfied: awscli>=1.11.91 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from allennlp)
Requirement already satisfied: overrides in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from allennlp)
Requirement already satisfied: sanic==0.6.0 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from allennlp)
Requirement already satisfied: numpy in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from allennlp)
Requirement already satisfied: requests>=2.18 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from allennlp)
Requirement already satisfied: pillow in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from allennlp)
Requirement already satisfied: spacy in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from allennlp)
Requirement already satisfied: tensorboard-pytorch in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from allennlp)
Requirement already satisfied: argparse in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from allennlp)
Requirement already satisfied: jupyter in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from allennlp)
Requirement already satisfied: six in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from nltk->allennlp)
Requirement already satisfied: pyparsing>=2.0.3 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from pyhocon==0.3.35->allennlp)
Requirement already satisfied: botocore==1.8.2 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from awscli>=1.11.91->allennlp)
Requirement already satisfied: docutils>=0.10 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from awscli>=1.11.91->allennlp)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.9 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from awscli>=1.11.91->allennlp)
Requirement already satisfied: rsa<=3.5.0,>=3.1.2 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from awscli>=1.11.91->allennlp)
Requirement already satisfied: PyYAML<=3.12,>=3.10 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from awscli>=1.11.91->allennlp)
Requirement already satisfied: colorama<=0.3.7,>=0.2.5 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from awscli>=1.11.91->allennlp)
Requirement already satisfied: aiofiles>=0.3.0 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from sanic==0.6.0->allennlp)
Requirement already satisfied: websockets>=3.2 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from sanic==0.6.0->allennlp)
Requirement already satisfied: uvloop>=0.5.3 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from sanic==0.6.0->allennlp)
Requirement already satisfied: httptools>=0.0.9 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from sanic==0.6.0->allennlp)
Requirement already satisfied: ujson>=1.35 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from sanic==0.6.0->allennlp)
Requirement already satisfied: idna<2.7,>=2.5 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from requests>=2.18->allennlp)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from requests>=2.18->allennlp)
Requirement already satisfied: certifi>=2017.4.17 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from requests>=2.18->allennlp)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from requests>=2.18->allennlp)
Requirement already satisfied: olefile in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from pillow->allennlp)
Requirement already satisfied: preshed<2.0.0,>=1.0.0 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from spacy->allennlp)
Requirement already satisfied: plac<1.0.0,>=0.9.6 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from spacy->allennlp)
Requirement already satisfied: msgpack-python in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from spacy->allennlp)
Requirement already satisfied: msgpack-numpy in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from spacy->allennlp)
Requirement already satisfied: dill<0.3,>=0.2 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from spacy->allennlp)
Requirement already satisfied: regex==2017.4.5 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from spacy->allennlp)
Requirement already satisfied: murmurhash<0.29,>=0.28 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from spacy->allennlp)
Requirement already satisfied: pathlib in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from spacy->allennlp)
Requirement already satisfied: cymem<1.32,>=1.30 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from spacy->allennlp)
Requirement already satisfied: ftfy<5.0.0,>=4.4.2 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from spacy->allennlp)
Requirement already satisfied: thinc<6.11.0,>=6.10.1 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from spacy->allennlp)
Requirement already satisfied: protobuf in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from tensorboard-pytorch->allennlp)
Requirement already satisfied: jupyter-console in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from jupyter->allennlp)
Requirement already satisfied: qtconsole in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from jupyter->allennlp)
Requirement already satisfied: ipywidgets in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from jupyter->allennlp)
Requirement already satisfied: notebook in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from jupyter->allennlp)
Requirement already satisfied: ipykernel in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from jupyter->allennlp)
Requirement already satisfied: nbconvert in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from jupyter->allennlp)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from botocore==1.8.2->awscli>=1.11.91->allennlp)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from botocore==1.8.2->awscli>=1.11.91->allennlp)
Requirement already satisfied: pyasn1>=0.1.3 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from rsa<=3.5.0,>=3.1.2->awscli>=1.11.91->allennlp)
Requirement already satisfied: html5lib in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from ftfy<5.0.0,>=4.4.2->spacy->allennlp)
Requirement already satisfied: wcwidth in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from ftfy<5.0.0,>=4.4.2->spacy->allennlp)
Requirement already satisfied: termcolor in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from thinc<6.11.0,>=6.10.1->spacy->allennlp)
Requirement already satisfied: wrapt in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from thinc<6.11.0,>=6.10.1->spacy->allennlp)
Requirement already satisfied: cytoolz<0.9,>=0.8 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from thinc<6.11.0,>=6.10.1->spacy->allennlp)
Requirement already satisfied: setuptools in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from protobuf->tensorboard-pytorch->allennlp)
Requirement already satisfied: ipython in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from jupyter-console->jupyter->allennlp)
Requirement already satisfied: jupyter-client in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from jupyter-console->jupyter->allennlp)
Requirement already satisfied: traitlets in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from qtconsole->jupyter->allennlp)
Requirement already satisfied: ipython-genutils in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from qtconsole->jupyter->allennlp)
Requirement already satisfied: pygments in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from qtconsole->jupyter->allennlp)
Requirement already satisfied: jupyter-core in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from qtconsole->jupyter->allennlp)
Requirement already satisfied: widgetsnbextension~=3.0.0 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from ipywidgets->jupyter->allennlp)
Requirement already satisfied: nbformat>=4.2.0 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from ipywidgets->jupyter->allennlp)
Requirement already satisfied: tornado>=4 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from notebook->jupyter->allennlp)
Requirement already satisfied: jinja2 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from notebook->jupyter->allennlp)
Requirement already satisfied: terminado>=0.3.3; sys_platform != "win32" in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from notebook->jupyter->allennlp)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from nbconvert->jupyter->allennlp)
Requirement already satisfied: testpath in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from nbconvert->jupyter->allennlp)
Requirement already satisfied: bleach in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from nbconvert->jupyter->allennlp)
Requirement already satisfied: entrypoints>=0.2.2 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from nbconvert->jupyter->allennlp)
Requirement already satisfied: mistune>=0.7.4 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from nbconvert->jupyter->allennlp)
Requirement already satisfied: webencodings in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from html5lib->ftfy<5.0.0,>=4.4.2->spacy->allennlp)
Requirement already satisfied: toolz>=0.8.0 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from cytoolz<0.9,>=0.8->thinc<6.11.0,>=6.10.1->spacy->allennlp)
Requirement already satisfied: appnope; sys_platform == "darwin" in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from ipython->jupyter-console->jupyter->allennlp)
Requirement already satisfied: pickleshare in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from ipython->jupyter-console->jupyter->allennlp)
Requirement already satisfied: gnureadline; sys_platform == "darwin" and platform_python_implementation == "CPython" in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from ipython->jupyter-console->jupyter->allennlp)
Requirement already satisfied: simplegeneric>0.8 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from ipython->jupyter-console->jupyter->allennlp)
Requirement already satisfied: decorator in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from ipython->jupyter-console->jupyter->allennlp)
Requirement already satisfied: pexpect; sys_platform != "win32" in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from ipython->jupyter-console->jupyter->allennlp)
Requirement already satisfied: pyzmq>=13 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from jupyter-client->jupyter-console->jupyter->allennlp)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from nbformat>=4.2.0->ipywidgets->jupyter->allennlp)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from jinja2->notebook->jupyter->allennlp)
Requirement already satisfied: ptyprocess in /Users/rsilvei/Envs/nlp/lib/python3.6/site-packages (from terminado>=0.3.3; sys_platform != "win32"->notebook->jupyter->allennlp)
Cleaning up...

**Comment by joelgrus** [comment] 2017-11-29 20:34
I just created a new 3.6 virtual env and ran

```
pip install allennlp
pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post3-cp36-cp36m-manylinux1_x86_64.whl torchvison
```

After which I didn't get any error:

```
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
REPL completion using Jedi 0.11.0

In [1]: from allennlp.data.tokenizers.token import Token
   ...:

In [2]: Token
Out[2]: allennlp.data.tokenizers.token.Token

In [3]: Token.__module__
Out[3]: 'allennlp.data.tokenizers.token'
```

🤔

**Comment by joelgrus** [comment] 2017-11-29 20:40
oops, ignore that, I can reproduce, I was doing something really stupid

**Comment by joelgrus** [comment] 2017-11-29 20:45
the issue is almost certainly that the version on PyPI is very old and *predates* the introduction of the `Token` class. 

in the short term the solution is to install the latest master rather than from PyPI.

the real solution is to release to PyPI much more often (which I've suggested elsewhere as well)

**Comment by DeNeutoy** [comment] 2017-11-29 20:51
Well, the real problem is that [the requirements for the allennlp-as-a-libarary](https://github.com/allenai/allennlp-as-a-library-example/blob/master/requirements.txt) example specify a more recent `allennlp` commit, which presumably hasn't been installed. We should update the pip package, though.

**Comment by joelgrus** [comment] 2017-11-29 20:54
in this case yes, but some of our tutorials rely on `Token` as well:

https://github.com/allenai/allennlp/blob/master/tutorials/notebooks/embedding_tokens.ipynb

**Comment by DeNeutoy** [comment] 2017-11-29 20:56
Good point - is this worth doing before the 0.3 release?

**Comment by DeNeutoy** [comment] 2017-11-30 00:04
@rsilveira79 This should be addressed by the latest release(`pip install allennlp --upgrade`). Can you let us know if it isn't?

**Comment by rsilveira79** [comment] 2017-11-30 13:11
Worked like a charm, thanks!

**Closed** 2017-11-30 16:01 UTC

**Comment by SallyAfua** [comment] 2019-04-30 00:04
Hello everyone I have successfully installed allennlp but  when I run (from allennlp.commands.elmo import ElmoEmbedder)  I get the error no module named allennlp.command.

My python version is 3.7 and I have already run (pip install allennlp --upgrade) in my terminal

**Comment by matt-gardner** [comment] 2019-04-30 00:26
There's a typo here somewhere, and I'm not sure if it's in what you typed into the terminal or in what you typed into your comment.  There's isn't a module named `allennlp.command`; it's named `allennlp.commands`.

**Comment by SallyAfua** [comment] 2019-04-30 07:32
Dear Matt,

Salutation!

I think it is a typo error, however I don't know how to fix this error.

I have a deadline to meet tomorrow, I hope I could be assisted.

Thanks for your support.

Kind regards,
Salomey.

**Comment by matt-gardner** [comment] 2019-04-30 12:59
We're not going to be able to help you unless you give us more detail, like the code / command you used, and the full stack trace.

**Comment by SallyAfua** [comment] 2019-04-30 16:03
Hello Mat,
Please find attached a screen shot of the commands in the terminal.


Kind regards,
Salomey

**Comment by matt-gardner** [comment] 2019-04-30 16:29
It appears that the screenshot didn't make its way to github.

**Comment by SallyAfua** [comment] 2019-04-30 16:36
Hello Matt,

I just joined Github yesterday. I need a litlle bit of assistance. Should I
create a new issue and upload the screenshot?

I am lost Matt.

Thanks for your assistance.

Kind regards
Salomey

**Comment by matt-gardner** [comment] 2019-04-30 16:41
It'd probably be easier to just paste in the content of what you were hoping to show with that screenshot.

**Comment by shaharjacob** [comment] 2021-04-13 19:34
I also faced with that problem, the reason was because I had a file called **_allennlp.py_** ... change it to other name :)
