### ISSUE TITLE
Predictor.from_path not loading my trained model

### ISSUE THREAD

**Issue by ud2195** [allenai/allennlp#4319] opened 2020-06-04 12:59 UTC
Hi , After training my Textual entailment model successfully using roBERTa, I am unable to load the same:-

Traceback:-
```
---------------------------------------------------------------------------
---------------------------------------------------------------------------
ConfigurationError                        Traceback (most recent call last)
<ipython-input-56-91de5da48e5e> in <module>()
     10 from allennlp.predictors.predictor import Predictor
     11 get_ipython().system('pip install swifter')
---> 12 predictor = Predictor.from_path("/content/allenepi/model.tar.gz")
     13 labels_dict = predictor._model.vocab.get_index_to_token_vocabulary('labels')
     14 
3 frames
/usr/local/lib/python3.6/dist-packages/allennlp/predictors/predictor.py
 in from_path(cls, archive_path, predictor_name, cuda_device, dataset_reader_to_load, frozen)
    257             predictor_name,
    258             dataset_reader_to_load=dataset_reader_to_load,
--> 259             frozen=frozen,
    260         )
    261 
/usr/local/lib/python3.6/dist-packages/allennlp/predictors/predictor.py in from_archive(cls, archive, predictor_name, dataset_reader_to_load, frozen)
    292         else:
    293             dataset_reader_params = config["dataset_reader"]
--> 294         dataset_reader = DatasetReader.from_params(dataset_reader_params)
    295 
    296         model = archive.model
/usr/local/lib/python3.6/dist-packages/allennlp/common/from_params.py in from_params(cls, params, constructor_to_call, constructor_to_inspect, **extras)
    558                 "type",
    559                 choices=as_registrable.list_available(),
--> 560                 default_to_first_choice=default_to_first_choice,
    561             )
    562             subclass, constructor_name = as_registrable.resolve_class_name(choice)
/usr/local/lib/python3.6/dist-packages/allennlp/common/params.py in pop_choice(self, key, choices, default_to_first_choice, allow_class_names)
    349                 """{"model": "my_module.models.MyModel"} to have it imported automatically."""
    350             )
--> 351             raise ConfigurationError(message)
    352         return value
    353 
ConfigurationError: snli not in acceptable choices for dataset_reader.type: ['conll2003', 'interleaving', 'sequence_tagging', 'sharded', 'babi', 'text_classification_json']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.```



```
```
my config.jsonnet:-
local transformer_model = "roberta-large";
local transformer_dim = 1024;
local cls_is_last_token = false;

{
  "dataset_reader":{
    "type": "snli",
    "tokenizer": {
      "type": "pretrained_transformer",
      "model_name": transformer_model,
      "add_special_tokens": false
    },
    "token_indexers": {
      "tokens": {
        "type": "pretrained_transformer",
        "model_name": transformer_model,
        "max_length": 40
      }
    }
  },
  "train_data_path": "/content/cnli_train_5L.jsonl",
  "validation_data_path": "/content/cnli_val_5L.jsonl",
  
  "model": {
    "type": "basic_classifier",
    "text_field_embedder": {
      "token_embedders": {
        "tokens": {
          "type": "pretrained_transformer",
          "model_name": transformer_model,
          "max_length": 40
        }
      }
    },
    "seq2vec_encoder": {
       "type": "cls_pooler",
       "embedding_dim": transformer_dim,
       "cls_is_last_token": cls_is_last_token
    },
    "feedforward": {
      "input_dim": transformer_dim,
      "num_layers": 1,
      "hidden_dims": transformer_dim,
      "activations": "tanh"
    },
    "dropout": 0.1,
    "namespace": "tags"
  },
  "data_loader": {
    "batch_sampler": {
      "type": "bucket",
      "batch_size" : 4
    }
  },
  "trainer": {
    "num_epochs": 10,
    "cuda_device" : 0,
    "validation_metric": "+accuracy",
    "learning_rate_scheduler": {
      "type": "slanted_triangular",
      "cut_frac": 0.06
    },
    "optimizer": {
      "type": "huggingface_adamw",
      "lr": 2e-5,
      "weight_decay": 0.1,
    }
  }
}

``````
code :-
```
from allennlp.predictors.predictor import Predictor 
predictor = Predictor.from_path("/content/allenepi/model.tar.gz")
```
allennlp and allennlp-model version is **1.0.0rc5**

will really appreciate some help on the same, Thank you

**Comment by matt-gardner** [comment] 2020-06-04 16:44
This looks like a duplicate of #4104, which I thought we already fixed.  You're not supposed to need to do any imports or anything to get the `allennlp-models` models and dataset readers registered.  @epwalsh, any idea why this isn't working in rc5?  Is it because we're not importing everything in `allennlp_modules.__init__`?

@ud2195, a simple workaround is to run `from allennlp_models import pair_classification` before your other lines.

**Comment by ud2195** [comment] 2020-06-04 17:48
@matt-gardner Thanks for replying matt. Model loaded successfully but when running the below function on my dataset i get `KeyError: 'hypothesis'` 
function-
```
def get_labels(hypothesis, premise):
    pred = predictor.predict(
      hypothesis=hypothesis,
      premise=premise
    )
    
    label = labels_dict[np.argmax(pred['label_probs'])]
    return label

```
traceback:-

Traceback (most recent call last):
```

  File "<ipython-input-23-558217224d8c>", line 10, in <module>
    testdata['predicted']=testdata.swifter.apply(lambda x:get_labels(x['hypothesis'],x['sent']))

  File "/home/episourcein.episource.com/espm1854/miniconda3/lib/python3.6/site-packages/swifter/swifter.py", line 343, in apply
    timed = timeit.timeit(wrapped, number=N_REPEATS)

  File "/home/episourcein.episource.com/espm1854/miniconda3/lib/python3.6/timeit.py", line 233, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)

  File "/home/episourcein.episource.com/espm1854/miniconda3/lib/python3.6/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)

  File "<timeit-src>", line 6, in inner

  File "/home/episourcein.episource.com/espm1854/miniconda3/lib/python3.6/site-packages/swifter/swifter.py", line 271, in wrapped
    func, axis=axis, raw=raw, result_type=result_type, args=args, **kwds

  File "/home/episourcein.episource.com/espm1854/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 6878, in apply
    return op.get_result()

  File "/home/episourcein.episource.com/espm1854/miniconda3/lib/python3.6/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()

  File "/home/episourcein.episource.com/espm1854/miniconda3/lib/python3.6/site-packages/pandas/core/apply.py", line 296, in apply_standard
    values, self.f, axis=self.axis, dummy=dummy, labels=labels

  File "pandas/_libs/reduction.pyx", line 618, in pandas._libs.reduction.compute_reduction

  File "pandas/_libs/reduction.pyx", line 128, in pandas._libs.reduction.Reducer.get_result

  File "<ipython-input-23-558217224d8c>", line 10, in <lambda>
    testdata['predicted']=testdata.swifter.apply(lambda x:get_labels(x['hypothesis'],x['sent']))

  File "/home/episourcein.episource.com/espm1854/miniconda3/lib/python3.6/site-packages/pandas/core/series.py", line 871, in __getitem__
    result = self.index.get_value(self, key)

  File "/home/episourcein.episource.com/espm1854/miniconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4405, in get_value
    return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))

  File "pandas/_libs/index.pyx", line 80, in pandas._libs.index.IndexEngine.get_value

  File "pandas/_libs/index.pyx", line 90, in pandas._libs.index.IndexEngine.get_value

  File "pandas/_libs/index.pyx", line 135, in pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/index_class_helper.pxi", line 109, in pandas._libs.index.Int64Engine._check_type

KeyError: 'hypothesis'
```
code:-
```
import swifter
testdata['predicted']=testdata.swifter.apply(lambda x:get_labels(x['hypothesis'],x['sent']))
```

**Comment by matt-gardner** [comment] 2020-06-04 18:04
For that model you have to specify a separate predictor:
```python
predictor = Predictor.from_path(
    "/content/allenepi/model.tar.gz",
    predictor_name="textual-entailment"
)
```

**Comment by ud2195** [comment] 2020-06-04 18:45
thank you so much, really appreciate your prompt replies and the work that you guys do to build such packages :)

**Comment by matt-gardner** [comment] 2020-06-05 22:39
From issue review: A simple solution is to just import default plugins in `allennlp.__init__`.  That has potential speed and memory implications that we want to measure before doing it.  Another solution is to do it when importing `Predictor`, because that's where this issue keeps coming up.

**Comment by epwalsh** [comment] 2020-06-05 23:24
I think importing plugins in `allennlp.__init__.py` could potentially result in some circular import issues. Anyway, here's a one potential solution: https://github.com/allenai/allennlp/pull/4333

**Closed** 2020-06-08 16:24 UTC
Labels: bug
